### ISSUE TITLE
 problem with the new version of ESET-KeyGen

### ISSUE THREAD

**Issue by Pancho1807** [rzc0d3r/ESET-KeyGen#102]
I am having a problem with the new version of ESET-KeyGen_v1.3.2.1_win64.exe. When I try to start it, it automatically close , while the older versions work fine and the antivirus is turned off normally.

https://github.com/rzc0d3r/ESET-KeyGen/assets/161178375/f68d920c-56ce-45bc-89b4-4ab1fd062e6d

**Comment by rzc0d3r** [comment]
You should read the changelogs. Starting from v1.3.2.1 the project became fully console app. You need to call it from the command line.

**Comment by rzc0d3r** [comment]
https://github.com/rzc0d3r/ESET-KeyGen/commit/e7530f16dc92cbe76a4fd7ca3203cdbeb4bd347c

https://github.com/rzc0d3r/ESET-KeyGen/commit/c7f33c00e14382f6395502b81d245b4a06c750bc

**Comment by Pancho1807** [comment]
too complicated, thanks anyway

**Comment by rzc0d3r** [comment]
> too complicated, thanks anyway 

For the average user, reading the description will be enough for you. You don't need to look at the changes in the code.
