### ISSUE TITLE
The code did not return the desizred value

### ISSUE THREAD

**Issue by sinnerion** [rzc0d3r/ESET-KeyGen#103]
![2024-02-25 09 35 05](https://github.com/rzc0d3r/ESET-KeyGen/assets/7335173/bae4bc25-057a-400e-a145-6f38da24dc0e)

**Comment by rzc0d3r** [comment]
Update program to latest version pls.

**Comment by rzc0d3r** [comment]
Стоит подметить, что начиная с версии 1.3.2.1 проект стал полностью консольным. Вам требуется его запускать его через консоль. Также были  переделаны аргументы командной строки. Ознакомится с ними можете тут
