### ISSUE TITLE
Unable to generate key using cli

### ISSUE THREAD

**Issue by AdityaGarg8** [rzc0d3r/ESET-KeyGen#104]
![image](https://github.com/rzc0d3r/ESET-KeyGen/assets/85610623/c14ab9a5-f231-4873-9a31-c7162682d8cd)

**Comment by rzc0d3r** [comment]
https://github.com/rzc0d3r/ESET-KeyGen/actions/runs/8039454034

**Comment by rzc0d3r** [comment]
[v1.3.2.2](https://github.com/rzc0d3r/ESET-KeyGen/releases/tag/v1.3.2.2)
