### ISSUE TITLE
Процесс завершен с кодом выхода 2.

### ISSUE THREAD

**Issue by stringer-popov** [rzc0d3r/ESET-KeyGen#107]
привет Артём форк ошибку стал выдавать:
Процесс завершен с кодом выхода 2.
![рус](https://github.com/rzc0d3r/ESET-KeyGen/assets/125668727/777d1083-66be-4d1c-86c6-7824b2fb31f3)

**Comment by rzc0d3r** [comment]
Отправьте скриншот именно страницы которая появится если нажать на блок с крестиком

**Comment by rzc0d3r** [comment]
В окне eset.yaml

**Comment by stringer-popov** [comment]
отправляю.
![анг](https://github.com/rzc0d3r/ESET-KeyGen/assets/125668727/f43945de-dbf8-44f5-a083-4ea3421510da)

**Comment by stringer-popov** [comment]
14s
Run ACCOUNT=2
Cloning into 'ESET-KeyGen'...

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Get:[1](https://github.com/stringer-popov/ESET-KeyGen-st/actions/runs/8051304561/job/21988873480#step:2:1) file:/etc/apt/apt-mirrors.txt Mirrorlist [142 B]
Hit:2 http://azure.archive.ubuntu.com/ubuntu jammy InRelease
Get:3 http://azure.archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
Hit:4 http://azure.archive.ubuntu.com/ubuntu jammy-backports InRelease
Get:5 http://azure.archive.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Get:6 https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease [3631 B]
Get:7 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [1412 kB]
Get:8 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main Translation-en [277 kB]
Get:9 http://azure.archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [1490 kB]
Get:10 http://azure.archive.ubuntu.com/ubuntu jammy-updates/restricted Translation-en [245 kB]
Get:11 http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1049 kB]
Get:12 http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe Translation-en [237 kB]
Get:13 http://azure.archive.ubuntu.com/ubuntu jammy-security/main amd64 Packages [1192 kB]
Get:14 http://azure.archive.ubuntu.com/ubuntu jammy-security/main Translation-en [217 kB]
Get:15 http://azure.archive.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [1452 kB]
Get:16 http://azure.archive.ubuntu.com/ubuntu jammy-security/restricted Translation-en [239 kB]
Hit:18 https://ppa.launchpadcontent.net/ubuntu-toolchain-r/test/ubuntu jammy InRelease
Get:17 http://azure.archive.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [843 kB]
Get:19 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main arm64 Packages [33.5 kB]
Get:20 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 Packages [131 kB]
Get:21 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main armhf Packages [11.8 kB]
Fetched 9061 kB in 1s (6596 kB/s)
Reading package lists...
Building dependency tree...
Reading state information...
[34](https://github.com/stringer-popov/ESET-KeyGen-st/actions/runs/8051304561/job/21988873480#step:2:35) packages can be upgraded. Run 'apt list --upgradable' to see them.

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
python3-pip is already the newest version (22.0.2+dfsg-1ubuntu0.4).
0 upgraded, 0 newly installed, 0 to remove and 34 not upgraded.
Collecting selenium
  Downloading selenium-4.18.1-py3-none-any.whl (10.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 23.6 MB/s eta 0:00:00
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (2.25.1)
Requirement already satisfied: colorama in /usr/lib/python3/dist-packages (from -r requirements.txt (line 3)) (0.4.4)
Collecting typing-extensions
  Downloading typing_extensions-4.10.0-py3-none-any.whl (33 kB)
Collecting trio~=0.17
  Downloading trio-0.24.0-py3-none-any.whl ([46](https://github.com/stringer-popov/ESET-KeyGen-st/actions/runs/8051304561/job/21988873480#step:2:47)0 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 460.2/460.2 KB 61.0 MB/s eta 0:00:00
Collecting certifi>=2021.10.8
  Downloading certifi-2024.2.2-py3-none-any.whl (163 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 163.8/163.8 KB 60.4 MB/s eta 0:00:00
Requirement already satisfied: urllib3[socks]<3,>=1.26 in /usr/lib/python3/dist-packages (from selenium->-r requirements.txt (line 1)) (1.26.5)
Collecting trio-websocket~=0.9
  Downloading trio_websocket-0.11.1-py3-none-any.whl (17 kB)
Requirement already satisfied: attrs>=20.1.0 in /usr/lib/python3/dist-packages (from trio~=0.17->selenium->-r requirements.txt (line 1)) (21.2.0)
Collecting exceptiongroup
  Downloading exceptiongroup-1.2.0-py3-none-any.whl (16 kB)
Collecting sortedcontainers
  Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Requirement already satisfied: idna in /usr/lib/python3/dist-packages (from trio~=0.17->selenium->-r requirements.txt (line 1)) (3.3)
Collecting outcome
  Downloading outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Collecting sniffio>=1.3.0
  Downloading sniffio-1.3.1-py3-none-any.whl (10 kB)
Collecting wsproto>=0.14
  Downloading wsproto-1.2.0-py3-none-any.whl (24 kB)
Collecting PySocks!=1.5.7,<2.0,>=1.5.6
  Downloading PySocks-1.7.1-py3-none-any.whl (16 kB)
Collecting h11<1,>=0.9.0
  Downloading h11-0.14.0-py3-none-any.whl ([58](https://github.com/stringer-popov/ESET-KeyGen-st/actions/runs/8051304561/job/21988873480#step:2:59) kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 KB 30.3 MB/s eta 0:00:00
Installing collected packages: sortedcontainers, typing-extensions, sniffio, PySocks, outcome, h11, exceptiongroup, certifi, wsproto, trio, trio-websocket, selenium
  Attempting uninstall: certifi
    Found existing installation: certifi 2020.6.20
    Not uninstalling certifi at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'certifi'. No files were found to uninstall.
Successfully installed PySocks-1.7.1 certifi-2024.2.2 exceptiongroup-1.2.0 h11-0.14.0 outcome-1.3.0.post0 selenium-4.18.1 sniffio-1.3.1 sortedcontainers-2.4.0 trio-0.24.0 trio-websocket-0.11.1 typing-extensions-4.10.0 wsproto-1.2.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

███████╗███████╗███████╗████████╗   ██╗  ██╗███████╗██╗   ██╗ ██████╗ ███████╗███╗   ██╗
██╔════╝██╔════╝██╔════╝╚══██╔══╝   ██║ ██╔╝██╔════╝╚██╗ ██╔╝██╔════╝ ██╔════╝████╗  ██║
█████╗  ███████╗█████╗     ██║      █████╔╝ █████╗   ╚████╔╝ ██║  ███╗█████╗  ██╔██╗ ██║
██╔══╝  ╚════██║██╔══╝     ██║      ██╔═██╗ ██╔══╝    ╚██╔╝  ██║   ██║██╔══╝  ██║╚██╗██║   
███████╗███████║███████╗   ██║      ██║  ██╗███████╗   ██║   ╚██████╔╝███████╗██║ ╚████║   
╚══════╝╚══════╝╚══════╝   ╚═╝      ╚═╝  ╚═╝╚══════╝   ╚═╝    ╚═════╝ ╚══════╝╚═╝  ╚═══╝                                                                      
                                                Project Version: v1.3.2.2
                                                Project Devs: rzc0d3r, AdityaGarg8, k0re,
                                                              Fasjeit, alejanpa17, Ischunddu,
                                                              soladify

usage: main.py [-h] (--chrome | --firefox | --edge)
               (--key | --account | --only-update) [--skip-webdriver-menu]
               [--no-headless]
               [--custom-browser-location CUSTOM_BROWSER_LOCATION]
main.py: error: one of the arguments --chrome --firefox --edge is required
Error: Process completed with exit code 2.
![на крестик нажал](https://github.com/rzc0d3r/ESET-KeyGen/assets/125668727/45a6191c-a7ac-4670-92f8-450966c52a83)

**Comment by stringer-popov** [comment]
name: ESET Keys & Accounts Generator (MAIN)

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      account:
        description: 'Number of Accounts to be generated (default = 0)'
        required: false
        default: '0'
      key:
        description: 'Number of Keys to be generated (default = 1)'
        required: false
        default: '1'

jobs:
  GenerateKey:
    runs-on: ubuntu-latest
    steps:
      - name: Generate key
        run: |
          ACCOUNT=${{ github.event.inputs.account }}
          KEY=${{ github.event.inputs.key }}
          git clone https://github.com/rzc0d3r/ESET-KeyGen.git
          cd ESET-KeyGen
          sudo apt update
          sudo apt install python3-pip
          sudo pip install -r requirements.txt
          if [[ ${ACCOUNT} != 0 ]]
          then
          #Initialise chrome driver on 1st run
          python3 main.py --account --cli
          if [[ ${ACCOUNT} != 1 ]]
          then
          #Subsequent runs in parallel
          seq 1 $((ACCOUNT - 1)) | xargs -I {} -P $((ACCOUNT - 1)) python3 main.py --account --cli
          fi
          echo "Account:" >> $GITHUB_STEP_SUMMARY
          cat ./*ACCOUNTS.txt >> $GITHUB_STEP_SUMMARY
          fi
          if [[ ${KEY} != 0 ]]
          then
          #Initialise chrome driver on 1st run
          python3 main.py --cli
          if [[ ${KEY} != 1 ]]
          then
          #Subsequent runs in parallel
          seq 1 $((KEY - 1)) | xargs -I {} -P $((KEY - 1)) python3 main.py --cli
          fi
          echo -e "\nKey:" >> $GITHUB_STEP_SUMMARY
          cat ./*KEYS.txt >> $GITHUB_STEP_SUMMARY
          fi
![урл](https://github.com/rzc0d3r/ESET-KeyGen/assets/125668727/f1110fe5-dee4-43b8-ba34-ca82356748b9)

**Comment by rzc0d3r** [comment]
Синхронизируйте форк (Ну типо на странице форка должна быть кнопка обновить форк)

**Comment by stringer-popov** [comment]
не вижу я кнопку "обновить форк"
![обновить](https://github.com/rzc0d3r/ESET-KeyGen/assets/125668727/35222c14-f253-4e7f-b1c0-a95ac2307d8f)

**Comment by rzc0d3r** [comment]
На основной странице репозитория вашего. Там типо будет написано что ваш  репозиторий устраивает на сколько-то там изменений (commits)

**Comment by stringer-popov** [comment]
благодарю получилось.
