### ISSUE TITLE
The program opens and closes immediately

### ISSUE THREAD

**Issue by itayasaf2002xd** [rzc0d3r/ESET-KeyGen#110]
I am using the latest version and the program just opens the CMD for 1 second and closes immediately on Windows 11 latest version.

**Comment by rzc0d3r** [comment]
Project is fully console app!
Use cmd for run project.

**Comment by itayasaf2002xd** [comment]
> Project is fully console app! Use cmd for run project.

I used the exe one from the release am I doing something wrong?

**Comment by rzc0d3r** [comment]
No. Since version 1.3.2.2 it is impossible to start a project without console. Now you need to use the console to interact with the project

**Comment by itayasaf2002xd** [comment]
> No. Since version 1.3.2.2 it is impossible to start a project without console. Now you need to use the console to interact with the project

Sorry for my ignorance but I am not understanding what I should do.
what commands or steps I should run/do?

In the ReadMe, you said just to run the exe file

like said here and that what I did
![image](https://github.com/rzc0d3r/ESET-KeyGen/assets/158079551/ca50c9f1-2851-4950-bf36-d9f167ee0472)


![image](https://github.com/rzc0d3r/ESET-KeyGen/assets/158079551/48f3ab94-6c6c-444f-9721-e06c0e13de64)

**Comment by rzc0d3r** [comment]
Yes. The .exe already has all the files you need to work and you don't need to install anything. Just download the .exe and use it.

**Comment by itayasaf2002xd** [comment]
> Yes. The .exe already has all the files you need to work and you don't need to install anything. Just download the .exe and use it.

But that is what I did and like I said when I am clicking the exe file it opens CMD for 1 second and then closes it immediately

**Comment by itayasaf2002xd** [comment]
Sir, I am telling you there is a bug with the exe methods I downloaded the exe file from the release and double-clicked it, then it opened CMD for 1 second, and then it closed itself.

I tried the exe it 3 different computers same behavior it is not working

**Comment by rzc0d3r** [comment]
https://github.com/rzc0d3r/ESET-KeyGen/blob/main/wiki%2FKeyGenerator.md

**Comment by rzc0d3r** [comment]
Open cmd: Win+R, cmd
Write full path to project .exe file.
Press Enter

**Comment by itayasaf2002xd** [comment]
I did and I got an error as you can see from my taskbar I have Edge/Chrome/Firefox

![image](https://github.com/rzc0d3r/ESET-KeyGen/assets/158079551/2580f07b-2171-4fa8-85b1-f5c2eb625c59)

**Comment by rzc0d3r** [comment]
Input required run-arguments

**Comment by itayasaf2002xd** [comment]
> Input required run-arguments

But Sir I am running the exe what should I do?

**Comment by rzc0d3r** [comment]
Always launch like this in the future.
Or you can create a shortcut .eche file and write arguments in its settings. This way you will be able to start the project as it was before, just by clicking on it

**Comment by Lobasheff** [comment]
Да, вот все получилось, так и есть создал ярлык и в свойствах переименовать добавил в конце  --chrome --key через пробел, спасибо.

**Comment by mcwebdesign23** [comment]
> > Input required run-arguments
> 
> But Sir I am running the exe what should I do?
> 
> You said " Open cmd: Win+R, cmd Write full path to project .exe file. Press Enter "
> 
> and I did but like you saw above I get this error so again if you say something try to explain what steps I should take to solve it

Hello,

Just run in cmd following command: ESET-KeyGen_v1.3.2.2_win64.exe --chrome --key

**Comment by rzc0d3r** [comment]
Yes

**Comment by itayasaf2002xd** [comment]
> > > Input required run-arguments
> > 
> > 
> > But Sir I am running the exe what should I do?
> > You said " Open cmd: Win+R, cmd Write full path to project .exe file. Press Enter "
> > and I did but like you saw above I get this error so again if you say something try to explain what steps I should take to solve it
> 
> Hello,
> 
> Just run in cmd following command: ESET-KeyGen_v1.3.2.2_win64.exe --chrome --key

Thanks you so much for explaining me what to do to fix the issue

**Comment by itayasaf2002xd** [comment]
This is the solution ESET-KeyGen_v1.3.2.2_win64.exe --chrome --key
