### ISSUE TITLE
Протестируйте проект и обновите дату тестирования

### ISSUE THREAD

**Issue by stringer-popov** [rzc0d3r/ESET-KeyGen#112]
Привет, Артём.
Мне на почту постоянно письма приходят, Протестируйте проект и обновите дату тестирования. Я удаляю эти запуски рабочего процесса, но они снова появляются.
![ключ](https://github.com/rzc0d3r/ESET-KeyGen/assets/125668727/07a24ca0-c052-48ba-8792-a54c4452b96b)
![письмо](https://github.com/rzc0d3r/ESET-KeyGen/assets/125668727/20b134e7-b70a-4886-8f0d-62db823b5df5)
![процессы](https://github.com/rzc0d3r/ESET-KeyGen/assets/125668727/1c64c051-87f2-4473-8844-1bec7f98bb45)
![тест](https://github.com/rzc0d3r/ESET-KeyGen/assets/125668727/f8d320ad-a070-4d68-9efa-cf05e7878ad5)

**Comment by rzc0d3r** [comment]
Удалите test.yml

**Comment by rzc0d3r** [comment]
Ну можно и так. Удалить можно с папки .github/workspace/test.yml

**Comment by stringer-popov** [comment]
спасибо удалил, а что такое test.yml? я его не создавал вроде.

**Comment by rzc0d3r** [comment]
А файл для Github Actions с помощью которого запукается автотестирование проекта. А появился он потому что при создание форка копируются все файлы и настройки
