### ISSUE TITLE
error

### ISSUE THREAD

**Issue by speedfreekz28** [rzc0d3r/ESET-KeyGen#113]
Line 129 Error: Process completed with exit code 2.
Repo worked just fine then just poped up this error what do you think it can be?

**Comment by rzc0d3r** [comment]
I'm not psychic enough to know the lines of code by heart.
Pls send me a screenshot of the log.

**Comment by speedfreekz28** [comment]
![Screenshot 2024-03-06 171346](https://github.com/rzc0d3r/ESET-KeyGen/assets/156520063/69f68a0c-e991-4cad-8f49-4313fd3daed3)

**Comment by rzc0d3r** [comment]
Refork repository
