### ISSUE TITLE
 Execution failed

### ISSUE THREAD

**Issue by hlanr1** [rzc0d3r/ESET-KeyGen#116]
An error occurred while executing the program

![image](https://github.com/rzc0d3r/ESET-KeyGen/assets/34832868/191aede8-51dd-4939-a78e-64fd4461c469)

**Comment by rzc0d3r** [comment]
ONLY ACTIVATION VIA ACCOUNT WORKS NOW, KEYS ARE NOT AVAILABLE!!!
