### ISSUE TITLE
Does not issue a key

### ISSUE THREAD

**Issue by YU-SUT** [rzc0d3r/ESET-KeyGen#119]
Hello. This error appears
![1](https://github.com/rzc0d3r/ESET-KeyGen/assets/154730905/d505985b-1217-4d9e-bd7a-f314f6e2849a)

**Comment by YU-SUT** [comment]
VPN отключен

**Comment by rzc0d3r** [comment]
Я имел ввиду попробуйте с ним

**Comment by rzc0d3r** [comment]
Так как с одобрением запросов очень сильно влияет страна

**Comment by YU-SUT** [comment]
Спасибо огромное. Сработало только с одним из трёх VPN ов.
