### ISSUE TITLE
EBA-ESET-Token interception failed

### ISSUE THREAD

**Issue by goravine** [rzc0d3r/ESET-KeyGen#120]
Command : ESET-KeyGen_v1.4.0.0_win64.exe --edge --business-key

[  INFO  ] EBA-ESET-Token interception...
[ FAILED ] Traceback (most recent call last):
  File "main.py", line 157, in <module>
  File "modules\eset_business_register.py", line 93, in confirmAccount
  File "modules\eset_business_register.py", line 86, in getToken
RuntimeError: Token retrieval error!!!

i tried the other like ESET-KeyGen_v1.4.0.0_win64.exe --small-business-account --edge and it successfully generate username and password, pity eset didnt accept username and password anymore. any solution?

**Comment by rzc0d3r** [comment]
> Command : ESET-KeyGen_v1.4.0.0_win64.exe --edge --business-key
> 
> [ INFO ] EBA-ESET-Token interception... [ FAILED ] Traceback (most recent call last): File "main.py", line 157, in File "modules\eset_business_register.py", line 93, in confirmAccount File "modules\eset_business_register.py", line 86, in getToken RuntimeError: Token retrieval error!!!
> 
> i tried the other like ESET-KeyGen_v1.4.0.0_win64.exe --small-business-account --edge and it successfully generate username and password, pity eset didnt accept username and password anymore. any solution?

I wrote that I have no idea what to do with him. ECET has removed the conversion of such accounts into keys

**Comment by rzc0d3r** [comment]
> i also tried registering at https://eba.eset.com/Account/Register using temp mail and never got the email after 10-20 minutes. maybe that is why?

it happens. Perhaps the text in the email changes and the program does not find the right email.
If I had a "email dump" on hand I would have changed the code
