### ISSUE TITLE
Unable to use --small-business-account

### ISSUE THREAD

**Issue by AdityaGarg8** [rzc0d3r/ESET-KeyGen#121]
<img width="682" alt="Screenshot 2024-03-09 at 10 53 50 AM" src="https://github.com/rzc0d3r/ESET-KeyGen/assets/85610623/5d646b48-c340-4b9d-8ae7-f7b5c7aa5e8f">

**Comment by AdityaGarg8** [comment]
Also, maybe you can try https://www.zenrows.com/blog/selenium-captcha-bypass for captcha.

**Comment by AdityaGarg8** [comment]
btw, how do i use username and password generated by --small-business-account

**Comment by rzc0d3r** [comment]
> btw, how do i use username and password generated by --small-business-account

idk :)

**Comment by rzc0d3r** [comment]
Maybe, I'm just going to turn off that argument down. Because ESET has removed the conversion of such accounts to keys

**Comment by AdityaGarg8** [comment]
It's sad to know when cannot use ci for keys now

**Comment by rzc0d3r** [comment]
Yes. But business accounts give you that option. One business trial-key works for 75 devices. But you need to solve captcha and also the emails come with a very long delay.

And about solving mail through services ah thought about that. But it seems to me that in time it will change to a more complex one. And also it seems to me that they will change the required input data at registration because now it's easy to register

**Comment by goravine** [comment]
> Yes. But business accounts give you that option. One business trial-key works for 75 devices. But you need to solve captcha and also the emails come with a very long delay.
> 
> And about solving mail through services ah thought about that. But it seems to me that in time it will change to a more complex one. And also it seems to me that they will change the required input data at registration because now it's easy to register

i suspect in the future it will ask for phone otp for business account like paypal

**Comment by rzc0d3r** [comment]
> > Yes. But business accounts give you that option. One business trial-key works for 75 devices. But you need to solve captcha and also the emails come with a very long delay.
> > And about solving mail through services ah thought about that. But it seems to me that in time it will change to a more complex one. And also it seems to me that they will change the required input data at registration because now it's easy to register
> 
> i suspect in the future it will ask for phone otp for business account like paypal

I think so, too. So we'll use ESET-HOME accounts for activation. lmao

**Comment by rzc0d3r** [comment]
https://github.com/rzc0d3r/ESET-KeyGen/releases/tag/vv1.4.0.0-restricted
No argument, no problem )
