### ISSUE TITLE
Problem with --business-key

### ISSUE THREAD

**Issue by afterploid** [rzc0d3r/ESET-KeyGen#123]
![Screenshot_1](https://github.com/rzc0d3r/ESET-KeyGen/assets/150049413/37ca37cc-1a27-4576-a851-3f4d6ec6650a)
The problem is that with the --business-key it results in the following error. Tried chrome and edge too
RuntimeError: untilConditionExecute: the code did not return the desired value!

**Comment by rzc0d3r** [comment]
Try vpn

**Comment by afterploid** [comment]
Thanks, it worked!
