### ISSUE TITLE
Google chrome dependency

### ISSUE THREAD

**Issue by fusionneur** [rzc0d3r/ESET-KeyGen#13]
i tried running on latest version as of today but failed

PS C:\Users\<user>\Downloads\ESET-KeyGen> py.exe '.\ESET KeyGen.py'
-- Chrome Driver Auto-Installer v1.1 (061023-1527) by rzc0d3r --

[WinError 3] The system cannot find the path specified: 'C:/Program Files/Google/Chrome/Application'
Press Enter...

I believe the previous approach was much cleaner as it did not require the user to have whole google chrome package installed. I personally don't use google chrome as they're browser is bloated af, nor anything related to infamous google. you should use instead an open source alternative like chromium or maybe firefox engine if possible

**Comment by rzc0d3r** [comment]
thank you for reporting the problem. I don't have any test devices I try to do the best I can.

Special thanks to [alejanpa17](https://github.com/alejanpa17) for trying to fix this problem!

Try re-downloading the project and running it.

**Comment by rzc0d3r** [comment]
My mistake.  I'll fix it.  I will find solutions on how to better determine the location of Google Chrome. Thx!

**Comment by rzc0d3r** [comment]
Try v1.0.8 (121023-0936) release
