### ISSUE TITLE
Business key  - Account confirmation error

### ISSUE THREAD

**Issue by Uj947nXmRqV2nRaWshKtHzTvckUUpD** [rzc0d3r/ESET-KeyGen#131]
PS C:\ESET-KeyGen> python .\main.py --firefox --business-key

███████╗███████╗███████╗████████╗   ██╗  ██╗███████╗██╗   ██╗ ██████╗ ███████╗███╗   ██╗
██╔════╝██╔════╝██╔════╝╚══██╔══╝   ██║ ██╔╝██╔════╝╚██╗ ██╔╝██╔════╝ ██╔════╝████╗  ██║
█████╗  ███████╗█████╗     ██║      █████╔╝ █████╗   ╚████╔╝ ██║  ███╗█████╗  ██╔██╗ ██║
██╔══╝  ╚════██║██╔══╝     ██║      ██╔═██╗ ██╔══╝    ╚██╔╝  ██║   ██║██╔══╝  ██║╚██╗██║
███████╗███████║███████╗   ██║      ██║  ██╗███████╗   ██║   ╚██████╔╝███████╗██║ ╚████║
╚══════╝╚══════╝╚══════╝   ╚═╝      ╚═╝  ╚═╝╚══════╝   ╚═╝    ╚═════╝ ╚══════╝╚═╝  ╚═══╝

                                                Project Version: v1.4.0.1
                                                Project Devs: rzc0d3r, AdityaGarg8, k0re,
                                                              Fasjeit, alejanpa17, Ischunddu,
                                                              soladify, AngryBonk

[  INFO  ] Initializing firefox-webdriver for Windows

[  INFO  ] Mail registration...
[   OK   ] Mail registration completed successfully!

[  INFO  ] Loading EBA-ESET Page...
[   OK   ] Successfully!

[  INFO  ] [STEP 1] Data filling...
[   OK   ] Successfully!

[  INFO  ] [STEP 2] Data filling...
[   OK   ] Successfully!

[  INFO  ] [STEP 3] Data filling...
[   OK   ] Successfully!

[  INFO  ] [STEP 4] Data filling...
[  INFO  ] [STEP 4] Solve the captcha on the page manually!!!
[   OK   ] Successfully!

[  INFO  ] EBA-ESET-Token interception...
[   OK   ] EBA-ESET-Token: bc2bd377-eda1-4c1e-86e0-027ea036c564

[  INFO  ] Account confirmation is in progress...
[ FAILED ] Traceback (most recent call last):
  File "C:\ESET-KeyGen\main.py", line 788, in <module>
    EsetBusinessReg.confirmAccount()
  File "C:\ESET-KeyGen\main.py", line 637, in confirmAccount
    raise RuntimeError('Account confirmation error!!!')
RuntimeError: Account confirmation error!!!

**Comment by Aioloz1971** [comment]
У меня точно такая же ошибка.

**Comment by rzc0d3r** [comment]
> У меня точно такая же ошибка.

Скоро залью обнову

**Comment by rzc0d3r** [comment]
https://github.com/rzc0d3r/ESET-KeyGen/releases/tag/v1.4.1.1

**Comment by Aioloz1971** [comment]
Ну елки-палки:
![IMG_20240312_192802](https://github.com/rzc0d3r/ESET-KeyGen/assets/163140432/bcb4f7b5-1197-4ff3-afa5-8451f314df64)

**Comment by rzc0d3r** [comment]
> Ну елки-палки: ![IMG_20240312_192802](https://private-user-images.githubusercontent.com/163140432/312139171-bcb4f7b5-1197-4ff3-afa5-8451f314df64.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNTc3NzMsIm5iZiI6MTcxMDI1NzQ3MywicGF0aCI6Ii8xNjMxNDA0MzIvMzEyMTM5MTcxLWJjYjRmN2I1LTExOTctNGZmMy1hZmE1LTg0NTFmMzE0ZGY2NC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMlQxNTMxMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OTAyZTEzMzUzOTZjY2M5ZDgxOTcxZDA3MDk4NDNlMmJmZjljYzBhODFhNTUyOWMzMGJjMmQ3NjI2NmRjMjEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.G1joDjxgLXN0qXH5giGhIqdSb2Uwg_jEEdHqquwFQuw)

А ну круто, библиотека только для chrome

**Comment by Aioloz1971** [comment]
Для Firefox не будет?

**Comment by rzc0d3r** [comment]
> Для Firefox не будет?

Я просто выключу ее для всех остальных браузеров. Прийдется перекачать вам снова код. Ха

**Comment by rzc0d3r** [comment]
Надеюсь что будет работать без этой библиотеки

**Comment by Aioloz1971** [comment]
Вот для эксперимента поставил Хром. И-и-и (барабанная дробь):
![IMG_20240312_194054](https://github.com/rzc0d3r/ESET-KeyGen/assets/163140432/757fa664-42fa-41e6-a999-e018fd30207e)

**Comment by rzc0d3r** [comment]
> Вот для эксперимента поставил Хром. И-и-и (барабанная дробь): ![IMG_20240312_194054](https://private-user-images.githubusercontent.com/163140432/312144106-757fa664-42fa-41e6-a999-e018fd30207e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNTg1ODQsIm5iZiI6MTcxMDI1ODI4NCwicGF0aCI6Ii8xNjMxNDA0MzIvMzEyMTQ0MTA2LTc1N2ZhNjY0LTQyZmEtNDFlNi1hOTk5LWUwMThmZDMwMjA3ZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMlQxNTQ0NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZGE1M2E0Yzg3Njg4ZGUzZDRlNmY5YWMzYmY0MTJmNDBmOGJhYzhiZDJmMzFhZTc1ODkyOWFhNTczMWQ2ZWIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8op5lYvxEoiEeb6NH7pnIZ1BujYxzN8UwpNE2wdh2vM)

https://github.com/rzc0d3r/ESET-KeyGen/releases/tag/v1.4.1.1
Ну смотря на вашу ошибку, то ничем это не поможет. Это уже ошибка в самом библиотеке

**Comment by rzc0d3r** [comment]
> Вот для эксперимента поставил Хром. И-и-и (барабанная дробь): ![IMG_20240312_194054](https://private-user-images.githubusercontent.com/163140432/312144106-757fa664-42fa-41e6-a999-e018fd30207e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNTg1ODQsIm5iZiI6MTcxMDI1ODI4NCwicGF0aCI6Ii8xNjMxNDA0MzIvMzEyMTQ0MTA2LTc1N2ZhNjY0LTQyZmEtNDFlNi1hOTk5LWUwMThmZDMwMjA3ZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMlQxNTQ0NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZGE1M2E0Yzg3Njg4ZGUzZDRlNmY5YWMzYmY0MTJmNDBmOGJhYzhiZDJmMzFhZTc1ODkyOWFhNTczMWQ2ZWIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8op5lYvxEoiEeb6NH7pnIZ1BujYxzN8UwpNE2wdh2vM)

Почитал в интернете и узнал, что библиотека не сохраняет нужные ей файлы при сборке в .ехе

**Comment by rzc0d3r** [comment]
Ну да, у меня тоже выдает ошибку

**Comment by Aioloz1971** [comment]
В общем так - после фикса для Хрома ничего не поменялось, та же ошибка, с Firefox-ом же вот:
![IMG_20240312_195727](https://github.com/rzc0d3r/ESET-KeyGen/assets/163140432/debf5994-aed5-42e3-a9cd-646b840c1e9a)

**Comment by rzc0d3r** [comment]
> В общем так - после фикса для Хрома ничего не поменялось, та же ошибка, с Firefox-ом же вот: ![IMG_20240312_195727](https://private-user-images.githubusercontent.com/163140432/312150470-debf5994-aed5-42e3-a9cd-646b840c1e9a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNTk1NjIsIm5iZiI6MTcxMDI1OTI2MiwicGF0aCI6Ii8xNjMxNDA0MzIvMzEyMTUwNDcwLWRlYmY1OTk0LWFlZDUtNDJlMy1hOWNkLTY0NmI4NDBjMWU5YS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMlQxNjAxMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMmMxYmE2ZjYzYjM2ODBlODJkM2JkMGZkZDIxN2E0ZTAxNGE1MDM3NDEyODQzZTc3MjRhYWUyM2IyMjFhOGU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ag3bcUsM-0dtAyqsS1BcxR3pshHDqlWiMz01L03dG5Y)

я вас обрадую. В этой версии уже доступен старый добрый --key аргумент для генерации ESET Smart Security Premium

**Comment by rzc0d3r** [comment]
А проблему с сборкой этой библиотеки я уже решил у себя на компе, сейчас пересоберу релиз

**Comment by Aioloz1971** [comment]
Дополню еще про Pyton - работает и без установленного. Ну если уж совсем честно - у меня портативная сборка Stable Diffusion от Xpuct стоит, там Pyton 3.10.9 где-то внутри запрятан, возможно он и работает.

**Comment by rzc0d3r** [comment]
> why not use english ? :) can i test anything?

yes. I just know Ukrainian and Russian. If I see someone speaking them, I switch to those languages.

**Comment by rzc0d3r** [comment]
> Дополню еще про Pyton - работает и без установленного. Ну если уж совсем честно - у меня портативная сборка Stable Diffusion от Xpuct стоит, там Pyton 3.10.9 где-то внутри запрятан, возможно он и работает.

Необычно. Хотя я также делал когда ставил stable diffusion. Только я устанавливал python вручную чтобы он не перебивал мне основную версию

**Comment by Aioloz1971** [comment]
Да, чуть не забыл. Предыдущие сборки я на рабочем компе запускал, там точно питона нет и всё работало.

**Comment by rzc0d3r** [comment]
> Да, чуть не забыл. Предыдущие сборки я на рабочем компе запускал, там точно питона нет и всё работало.

А так .ехе собраны уже со всем необходимым для корректной работы проекта. Это если вы качаете исходный код и запускаете его, то нужен установленый питон, а так нет.

**Comment by rzc0d3r** [comment]
> > Да, чуть не забыл. Предыдущие сборки я на рабочем компе запускал, там точно питона нет и всё работало.
> 
> А так в .ехе собраны уже со всем необходимым для корректной работы проекта. Это если вы качаете исходный код и запускаете его, то нужен установленый питон, а так нет.

**Comment by rzc0d3r** [comment]
> > В общем так - после фикса для Хрома ничего не поменялось, та же ошибка, с Firefox-ом же вот: ![IMG_20240312_195727](https://private-user-images.githubusercontent.com/163140432/312150470-debf5994-aed5-42e3-a9cd-646b840c1e9a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNTk1NjIsIm5iZiI6MTcxMDI1OTI2MiwicGF0aCI6Ii8xNjMxNDA0MzIvMzEyMTUwNDcwLWRlYmY1OTk0LWFlZDUtNDJlMy1hOWNkLTY0NmI4NDBjMWU5YS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMlQxNjAxMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMmMxYmE2ZjYzYjM2ODBlODJkM2JkMGZkZDIxN2E0ZTAxNGE1MDM3NDEyODQzZTc3MjRhYWUyM2IyMjFhOGU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ag3bcUsM-0dtAyqsS1BcxR3pshHDqlWiMz01L03dG5Y)
> 
> я вас обрадую. В этой версии уже доступен старый добрый --key аргумент для генерации ESET Smart Security Premium

А ну и еще. Генерация ключей через браузер снова стала доступна

**Comment by Aioloz1971** [comment]
Решил проверить еще и --key (через VPN, естественно). И:
![IMG_20240312_203033](https://github.com/rzc0d3r/ESET-KeyGen/assets/163140432/83419964-e7e9-47b4-8dda-08170906a444)

**Comment by Aioloz1971** [comment]
Всё, разобрался. Аргумент --key несовместим с --use-hi2in, использованные вместе выдают вышеописанную ошибку. Без --use-hi2in всё получается.

**Comment by YU-SUT** [comment]
> Всё, разобрался. Аргумент --key, оказывается, несовместим с --use-hi2in, использованные вместе выдают вышеописанную ошибку. Без --use-hi2in всё получится.

Здравствуйте. С аргументом --key ключ одноразовый? Я правильно понял? Заранее спасибо за ответ.

**Comment by rzc0d3r** [comment]
> > Всё, разобрался. Аргумент --key, оказывается, несовместим с --use-hi2in, использованные вместе выдают вышеописанную ошибку. Без --use-hi2in всё получится.
> 
> Здравствуйте. С аргументом --key ключ одноразовый? Я правильно понял? Заранее спасибо за ответ.

Да

**Comment by YU-SUT** [comment]
> > > Всё, разобрался. Аргумент --key, оказывается, несовместим с --use-hi2in, использованные вместе выдают вышеописанную ошибку. Без --use-hi2in всё получится.
> > 
> > 
> > Здравствуйте. С аргументом --key ключ одноразовый? Я правильно понял? Заранее спасибо за ответ.
> 
> Да

Спасибо вам, и всем тем кто вам помогает, за труд. Удачи в жизни и в работе.

**Comment by Aioloz1971** [comment]
> > > Всё, разобрался. Аргумент --key, оказывается, несовместим с --use-hi2in, использованные вместе выдают вышеописанную ошибку. Без --use-hi2in всё получится.
> > 
> > 
> > Здравствуйте. С аргументом --key ключ одноразовый? Я правильно понял? Заранее спасибо за ответ.
> 
> Да

Маленькое добавление - одноразовый, но на два устройства.

**Comment by YU-SUT** [comment]
> > > > Всё, разобрался. Аргумент --key, оказывается, несовместим с --use-hi2in, использованные вместе выдают вышеописанную ошибку. Без --use-hi2in всё получится.
> > > 
> > > 
> > > Здравствуйте. С аргументом --key ключ одноразовый? Я правильно понял? Заранее спасибо за ответ.
> > 
> > 
> > Да
> 
> Маленькое добавление - одноразовый, но на два устройства.

Спасибо. Я и хотел узнать на сколько устройств.
