### ISSUE TITLE
ESET Business KEY  

### ISSUE THREAD

**Issue by WUJASON0078** [rzc0d3r/ESET-KeyGen#134]
Is it normal that ESET Business KEY cannot be used in the ESET Business Account I created?

**Comment by rzc0d3r** [comment]
I haven't checked this.  So no idea.  Can you describe in more detail?

**Comment by WUJASON0078** [comment]
![image](https://github.com/rzc0d3r/ESET-KeyGen/assets/162537612/69caadaf-8e62-463f-a1de-733a5386ba61)

This problem occurs when I add a business key to eset business
