### ISSUE TITLE
Help me please, with my Maxthon Browser, but PORTABLE version, not INSTALABLE version!?

### ISSUE THREAD

**Issue by kokolino2** [rzc0d3r/ESET-KeyGen#137]
Hello!

I am using Maxthon Browser, version 6.1.2.3000 x64bit Portable. Even i am giving he correct path to the real executable, your programme does not work!
It constantly gives me this error message:

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

C:\ESET_KeyGen v1.4.1.1>ESET1411.EXE --chrome --key --use-hi2in
Error loading Python DLL 'C:\Users\pc13\AppData\Local\Temp\_MEI49522\python39.dl
l'.
No error messages generated.
FormatMessageW: The parameter is incorrect.
LoadLibrary: PyInstaller: FormatMessageW failed.
C:\ESET_KeyGen v1.4.1.1>

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

First, I tried by copying all the PYTHON 3.9.0 files into the directory where I copied your executable file "ESET1411.exe". Then I tried with PYTHON 3.8.0 files, but the same error! Again with: "Error loading Python DLL 'C:\Users\pc13\AppData\Local\Temp\_MEI49522\python39.dl
l' 

As if it wants/needs something from Python 3,9.x.

Help me, PLEASE, to solve this problem! I do not want to make an installation (of a browser)! I prefer to use portable version! Not messing my REGISTRY! I hope you understand me!

I use "Windows 7 Ultimate, SP 1".

Have a nice day!!!

Kiril

**Comment by rzc0d3r** [comment]
WINDOWS 7 SUPPORTED ONLY IN WIN32 VERSION

**Comment by rzc0d3r** [comment]
The win32 version is based on Python 3.8, as this is the latest version that supports windows 7.

**Comment by rzc0d3r** [comment]
win64 is based Python 3.10+

**Comment by rzc0d3r** [comment]
And also the project only supports Google Chrome, Microsoft Edge, Firefox. It is impossible to create support for your browser. You can use firefox or chrome portable

**Comment by kokolino2** [comment]
Thank You!

I will try!

Thank You!!!

**Comment by rzc0d3r** [comment]
Also when starting you need to use the argument ```--custom-browser-location "location to browser .exe"``` since you are using a custom browser installation
