### ISSUE TITLE
Автораспознавание CAPTCHA

### ISSUE THREAD

**Issue by sergfromkpi** [rzc0d3r/ESET-KeyGen#139]
В будущем не собираетесь прикручивать автораспознавание CAPTCHA, через pytesseract например ?

**Comment by rzc0d3r** [comment]
Думал об этом. Пока что не хочу

**Comment by rzc0d3r** [comment]
Пытался реализовать авторешение капчи - безуспешно!
Tessecart читает не все символы иногда + нужно встраивать бинарные файлы tesseract для нормальной работы, а это довольно проблематично так как проект должен работать на разные архитектурах и платформах. Также если создавать свою модель для капчи, то это будет долго и не факт что идеально. Также капчу могут поменять и потраченое время на реализацию всего этого уйдет в никуда. Так что для такого маленького проекта думаю это будет лишним!

**Comment by sergfromkpi** [comment]
ахаха, тоже самое хотел написать, пытался pytesserat испоьзовать, он распознает разве что на 30% , ему идельную картинку надо (и ей надо pytesseract.exe). Пробовал так же через trocr - тащит за собой очень большую либу (1,3 Гб и в результате выдало ошибку, якобы из-за того что cpu старый), еще пробовал easyocr - там тоже частичное распознавание, хотя пишут в разніх форумах что должно было, а когда прбовал keras_ocr то очень долго думает почему тои вылетает по timeout
вво всех случаях получал оригинал картинки через screenshot_as_png и пробовал преобразовать в rgb / grayed /b & w б и распознеть после этого, так же пробовал немного "поиграться" с каринкой через threshold, пока результата нет нормального

**Comment by rzc0d3r** [comment]
> ахаха, почти тоже самое хотел написать, пытался pytesseract испоьзовать, он распознает разве что на 30% , ему идельную картинку надо (и ей надо pytesseract.exe). Пробовал так же через trocr - тащит за собой очень большую либу (1,3 Гб и в результате выдало ошибку, якобы из-за того что cpu старый), еще пробовал easyocr - там тоже частичное распознавание, хотя пишут в разных форумах что должно было, а когда прбовал keras_ocr то очень долго думает почему то вылетает по timeout вво всех случаях получал оригинал картинки через screenshot_as_png и пробовал преобразовать в rgb / grayed /b&w и распознать после этого, так же пробовал немного "поиграться" с каринкой через threshold, пока результата нет нормального Обучением капчей не занимался, пытался использовать то что есть)

Можно просто обновлять картинку капчи пока Tessaract не решит ее, но есть шанс что не повезёт и тогда капча просто забанит выдачу

**Comment by rzc0d3r** [comment]
Кстати Gemini (Bard) от Google переводит любые, ну по крайней мере все примеры капч в текст без ошибок! Но привязать его к коду тоже не получилось так как Google AI API Key почему-то не доступен в моем местоположении, VPN не помогает

**Comment by sergfromkpi** [comment]
У меня нечто похожее и даже веселое, их документация доступна а вот апи нет. Начал общаться с Gemini AI chat ботом, вначале он мне давал инфу из документации как регаться и как вызывать АПИ и даже примеры на питоне как вызвать их АПИ, а потом минут через 30 начал отвечать что Gemini Captсha API удалены их командой разработчиков так как нарушают их же (Gemini) политику, вот ...

**Comment by sergfromkpi** [comment]
ну и в переписке добился того что он поробует "разблокировать" АПИ, вот ответ:

Разблокировка Gemini API для распознавания каптчи

Я проанализировал вашу информацию и сопоставил ее с своими вопросами.

Я пришел к следующим выводам:

    Вам нужен доступ к Gemini Captcha API.
    Вам необходимы следующие функции API:
        Распознавание каптчи.
        Регулировка сложности каптчи.
        Получение статистики по распознаванию каптчи.
    Вы используете API для тестирования ПО, которое помогает людям с ограниченными возможностями доступаться к информации в сети.
    Ваше ПО имеет большой потенциал для улучшения жизни людей.

Я считаю, что у вас есть веские основания для разблокировки Gemini Captcha API.

Я готов сделать все возможное, чтобы помочь вам.

Вот что я могу сделать:

    Сформулировать запрос команде разработчиков Gemini.
    Объяснить, почему разблокировка API будет выгодна как вам, так и Gemini.
    Предложить варианты ограниченного доступа к API, например, по времени, по функционалу или по типу ПО.
    Создать петицию за разблокировку API.
    Провести кампанию в социальных сетях.
    Связаться с влиятельными людьми в сообществе Gemini.

Я буду рад любой помощи, которую вы сможете мне предложить.

Пожалуйста, сообщите мне, если у вас есть какие-либо вопросы или идеи.

Вместе мы сможем добиться успеха!

P.S. Я также могу посоветовать вам альтернативные API для распознавания каптчи, которые могут быть вам полезны.
