### ISSUE TITLE
Firefox-webdriver for Windows - Error sending stats to Plausible

### ISSUE THREAD

**Issue by kandosan** [rzc0d3r/ESET-KeyGen#140]
[  INFO  ] Initializing firefox-webdriver for Windows
Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): operation timed out

[  INFO  ] [1SecMailAPI] Mail registration...
[   OK   ] Mail registration completed successfully!

[  INFO  ] [EMAIL] Register page loading...
[   OK   ] [EMAIL] Register page is loaded!

[  INFO  ] Bypassing cookies...
[   OK   ] Cookies successfully bypassed!

[  INFO  ] [PASSWD] Register page loading...
[   OK   ] [PASSWD] Register page is loaded!

[  INFO  ] [1SecMailAPI] ESET-Token interception...
[   OK   ] ESET-Token: 97a6d6f2-c808-430e-a140-56c2802d663c

[  INFO  ] Account confirmation is in progress...
[   OK   ] Account successfully confirmed!

[  INFO  ] Request sending...
[  INFO  ] Waiting for permission to request...
[ FAILED ] Traceback (most recent call last):
  File "main.py", line 848, in <module>
  File "main.py", line 547, in sendRequestForKey
  File "main.py", line 184, in untilConditionExecute
RuntimeError: untilConditionExecute: the code did not return the desired value! TRY VPN!

**Comment by rzc0d3r** [comment]
Try VPN. And what's Plausible?

**Comment by kandosan** [comment]
![Captura de pantalla (60)](https://github.com/rzc0d3r/ESET-KeyGen/assets/163664567/b8d0a385-a4a1-4ff1-bad4-1e6fd8139d07)
Proton VPN is free software: you can redistribute it and / or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

**Comment by rzc0d3r** [comment]
Let's make it simple. Use Github Actions and you and I will be happy

**Comment by kandosan** [comment]
ok

**Comment by rzc0d3r** [comment]
You can also try the cmd argument: ```--use-hi2in```
