### ISSUE TITLE
Failed to execute script 'main' ...

### ISSUE THREAD

**Issue by shniagrcia** [rzc0d3r/ESET-KeyGen#141]
Hello, i got this error message, what should i do?

![Screenshot 2024-03-19 083704](https://github.com/rzc0d3r/ESET-KeyGen/assets/157873139/8dded50e-87dc-4196-877a-212f7fb1b3b6)

**Comment by rzc0d3r** [comment]
Download this version: https://github.com/rzc0d3r/ESET-KeyGen/releases/tag/vv1.4.1.1
Somehow the latest release took the place of the old one :)

**Comment by shniagrcia** [comment]
Thankyou :)
