### ISSUE TITLE
the bot goes too fast

### ISSUE THREAD

**Issue by 1043613lcpsorg** [rzc0d3r/ESET-KeyGen#143]
when i use the bot the bot goes too fast and the registration failed

**Comment by rzc0d3r** [comment]
In github actions?

**Comment by 1043613lcpsorg** [comment]
when i used it in windows power shell

**Comment by rzc0d3r** [comment]
> > In github actions?
> when i used it in windows power shell

To make it easier, I recommend recording a video of what you have going on. Please

**Comment by 1043613lcpsorg** [comment]
I have to go to school

**Comment by rzc0d3r** [comment]
> [2024-03-20 08-01-00.zip](https://github.com/rzc0d3r/ESET-KeyGen/files/14666001/2024-03-20.08-01-00.zip)

EBA ESET started blocking all email api implemented in the project. Use --key argument

**Comment by 1043613lcpsorg** [comment]
ok let me try when I go home

**Comment by rzc0d3r** [comment]
https://github.com/rzc0d3r/ESET-KeyGen/releases/tag/v1.4.2.0

**Comment by 1043613lcpsorg** [comment]
it worked 
![Screenshot 2024-03-20 165847](https://github.com/rzc0d3r/ESET-KeyGen/assets/153699099/07b5dfd9-55eb-4ec8-a92c-9fe04d249de8)
thank you
