### ISSUE TITLE
Аахахаха, чееел, это что ж на сколько прикольную штуку ты сделал что ESET твой профиль в гите внес в список опасных)))

### ISSUE THREAD

**Issue by WWFyb3NsYXYg** [rzc0d3r/ESET-KeyGen#148]
![image](https://github.com/rzc0d3r/ESET-KeyGen/assets/87089735/63831df2-38b4-4b3b-95bf-2120b7c9c156)

**Comment by rzc0d3r** [comment]
Та добавили ещё давно. В самом начале readme.md написано про это. И как это можно убрать
