### ISSUE TITLE
Doesn't work on Win7

### ISSUE THREAD

**Issue by RomaGly55Creations** [rzc0d3r/ESET-KeyGen#149]
[ FAILED ] Traceback (most recent call last):
  File "C:\Users\RomaGly's Studio\Downloads\ESET-KeyGen-1.4.3.0f1\ESET-KeyGen-1.4.3.0f1\main.py", line 888, in (module)
      if platform.release() == '7' and webdriver_installer.get_platform()[0] == 'win': # fix for Windows 7
AttributeError: 'WebDriverInstaller' object has no attribute 'get_platform'

Done even by executables, finishing to unobtainable dll's.
At actual time, 15-16 versions are still maintaned and properly running on older systems.

**Comment by rzc0d3r** [comment]
Funny. After a global code rearrangement, I didn't notice that I was using a non-existent function. Replace line 888 with 
```python
if platform.release() == '7' and webdriver_installer.platform[0] == 'win': # fix for Windows 7
```

**Comment by rzc0d3r** [comment]
Tested on windows 7 and I see that I need to finalize some code sections

**Comment by RomaGly55Creations** [comment]
> Tested on windows 7 and I see that I need to finalize some code sections

That's sounds good!

**Comment by rzc0d3r** [comment]
TRY
[v1.4.3.0f2.zip](https://github.com/rzc0d3r/ESET-KeyGen/files/14749403/v1.4.3.0f2.zip)

**Comment by rzc0d3r** [comment]
Try: https://github.com/rzc0d3r/ESET-KeyGen/releases/tag/v1.4.3.0f2
