### ISSUE TITLE
【FAILED】chrome is not detected on your device

### ISSUE THREAD

**Issue by hlanr1** [rzc0d3r/ESET-KeyGen#15]
I am installing ubuntu 22.04, and the python version is version 3.11. A chrome error will appear when executing the program.
[ FAILED ] Chrome is not detected on your device!

**Comment by rzc0d3r** [comment]
Do you have chrome installed?

**Comment by rzc0d3r** [comment]
I found a way that will always work.  I'll publish it today.

**Comment by rzc0d3r** [comment]
Hahahaha I just didn't remove the test lines of code.  Now in the code the chrome version will always be None regardless of whether chrome is installed or not

**Comment by rzc0d3r** [comment]
Try v1.0.8.1 (131023-1557) (Latest)

**Comment by Fasjeit** [comment]
For me it is working (Ubuntu 22). Thanks.
