### ISSUE TITLE
Cant detect chrome or edge

### ISSUE THREAD

**Issue by Stranger614** [rzc0d3r/ESET-KeyGen#151]
first of all thankyou for this, I've been using this for a while now. 
The issue is it says this and I have chrome and edge both and they are updated.
IDK how to fix it or why does this have this issue now
![image](https://github.com/rzc0d3r/ESET-KeyGen/assets/165376935/9bd5efec-71f3-4c5d-b1b6-9306a58f147e)

**Comment by Stranger614** [comment]
it just auto closes in few seconds after opening

**Comment by rzc0d3r** [comment]
> it just auto closes in few seconds after opening 

Open cmd and write the path to the .exe file then specify the arguments

**Comment by Stranger614** [comment]
Thankyou bro it worked
