### ISSUE TITLE
Key Generation not working

### ISSUE THREAD

**Issue by NewDark** [rzc0d3r/ESET-KeyGen#153]
When i try to generate key it does not work. Image in description. Python requirements installed. I use Python 3.12.2.

![WindowsTerminal_G2aai3Q1Ww](https://github.com/rzc0d3r/ESET-KeyGen/assets/48694024/d63bf61d-9c76-4989-8cb4-768397d5cb61)

I tried to use VPN in 3 different locations but it is not working. 

I can confirm that creating Account works but not key generation.

**Comment by rzc0d3r** [comment]
Use github actions
