### ISSUE TITLE
error tempmail

### ISSUE THREAD

**Issue by HamedAp** [rzc0d3r/ESET-KeyGen#158]
![image](https://github.com/rzc0d3r/ESET-KeyGen/assets/109583222/a04d7b42-4f5a-49b2-bb81-df84e6be1601)

time for load cloudflare captcha is low ! 

increase time please .

**Comment by rzc0d3r** [comment]
Try use main.py from dev branch. And send results pls

**Comment by HamedAp** [comment]
i changed tempmail to 10minutemail i fixed it :
`python main.py --chrome --key --email-api 10minutemail`

but tempmail shown cloudflare captcha and before i click the box , cmd shows use vpn ! 
i can load tempmail website in google chrome well with no problem .

**Comment by rzc0d3r** [comment]
> i changed tempmail to 10minutemail i fixed it :
> `python main.py --chrome --key --email-api 10minutemail`
> 
> but tempmail shown cloudflare captcha and before i click the box , cmd shows use vpn ! 
> i can load tempmail website in google chrome well with no problem . 
> 
> 

Because it gives you eight seconds to do everything. I can't do the captcha solution check because tempmail window is not active, and if I make it active, the captcha doesn't pass.

And I used a delay to change the active window in code

**Comment by rzc0d3r** [comment]
Please make the test for main.py from the dev branch

**Comment by HamedAp** [comment]
> Please make the test for main.py from the dev branch

i used it and everything is ok . 
because its use 1secmail and no captcha !!
