### ISSUE TITLE
error: one of the arguments --chrome --firefox --edge is required

### ISSUE THREAD

**Issue by IBTS90** [rzc0d3r/ESET-KeyGen#162]
I do have Chrome installed but it keeping write the same error:

ESET-KeyGen_v1.4.4.0_win64.exe: error: one of the arguments --chrome --firefox --edge is required

What I'm doing wrong?

Thanks

**Comment by rzc0d3r** [comment]
```ESET-KeyGen_v1.4.4.0_win64.exe --chrome```

The program asks for arguments after the .exe path.
It not error!

**Comment by rzc0d3r** [comment]
https://github.com/rzc0d3r/ESET-KeyGen/blob/main/wiki/CommandLineArguments.md

**Comment by IBTS90** [comment]
So do i need to open the program from "cmd"? I can't double click on the Exe file and lunch it ?

**Comment by IBTS90** [comment]
Oh I understood what you mean, sorry, the think is I just lunch the program and the came straight on that line with the error I have no time to write anything.

**Comment by IBTS90** [comment]
https://github.com/rzc0d3r/ESET-KeyGen/assets/121885706/c5f77e39-76e1-4c24-b9f0-c24841fc6a31

check this out maybe would make more sense XD

**Comment by rzc0d3r** [comment]
> So do i need to open the program from "cmd"? I can't double click on the Exe file and lunch it ?

yes

**Comment by IBTS90** [comment]
Thanks, you can close and delete this post.

**Comment by IBTS90** [comment]
Now i'm gettin this issue as seems got stuck on the address page and one I filled up the captcha is says error and this:

 FAILED ] Traceback (most recent call last):
  File "C:\Users\Mr X\Desktop\ESET-KeyGen-main\main.py", line 965, in <module>
    EsetBusinessReg.createAccount()
  File "C:\Users\Mr X\Desktop\ESET-KeyGen-main\main.py", line 783, in createAccount
    raise RuntimeError('\nESET temporarily blocked your IP, try again later!!! TRY VPN!!!')
RuntimeError:
ESET temporarily blocked your IP, try again later!!! TRY VPN!!!

**Comment by IBTS90** [comment]
thanks all working now you can close the ticket :)
