### ISSUE TITLE
error

### ISSUE THREAD

**Issue by hamechiz** [rzc0d3r/ESET-KeyGen#163]
-- WebDriver Auto-Installer --

[  INFO  ] Google Chrome version: 123.0.6312.106
[  INFO  ] Google Chrome webdriver version: 123.0.6312.105
[   OK   ] The driver has already been updated to the browser version!

[  INFO  ] Initializing chrome-webdriver for Windows

DevTools listening on ws://127.0.0.1:12758/devtools/browser/371e5c21-cc26-4023-9052-4a4035739fa3

[  INFO  ] [1secmail] Mail registration...
[ FAILED ] Traceback (most recent call last):
  File "urllib3\connection.py", line 198, in _new_conn
  File "urllib3\util\connection.py", line 85, in create_connection
  File "urllib3\util\connection.py", line 73, in create_connection
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 793, in urlopen
  File "urllib3\connectionpool.py", line 491, in _make_request
  File "urllib3\connectionpool.py", line 467, in _make_request
  File "urllib3\connectionpool.py", line 1099, in _validate_conn
  File "urllib3\connection.py", line 616, in connect
  File "urllib3\connection.py", line 213, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000013D2BF04070>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests\adapters.py", line 486, in send
  File "urllib3\connectionpool.py", line 847, in urlopen
  File "urllib3\util\retry.py", line 515, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.1secmail.com', port=443): Max retries exceeded with url: /api/v1/?action=genRandomMailbox&count=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000013D2BF04070>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 111, in register
  File "requests\api.py", line 73, in get
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 519, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.1secmail.com', port=443): Max retries exceeded with url: /api/v1/?action=genRandomMailbox&count=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000013D2BF04070>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 930, in <module>
  File "main.py", line 113, in register
RuntimeError: SecEmailAPI: API access error!

**Comment by rzc0d3r** [comment]
Check your internet connection

**Comment by rzc0d3r** [comment]
If stable try use vpn

**Comment by ZilvinasLasauskas** [comment]
I am getting an error:

[  INFO  ] License uploads...
[ FAILED ] Traceback (most recent call last):
  File "main.py", line 959, in <module>
  File "main.py", line 714, in getLicenseData
  File "main.py", line 282, in untilConditionExecute
RuntimeError: untilConditionExecute: the code did not return the desired value! TRY VPN!

The same, if using internet or VPN

**Comment by ZilvinasLasauskas** [comment]
File "main.py", line 959, in <module>

**Comment by ZilvinasLasauskas** [comment]
File "main.py", line 959, in module

**Comment by rzc0d3r** [comment]
> -- WebDriver Auto-Installer --
> 
> [ INFO ] Google Chrome version: 123.0.6312.106 [ INFO ] Google Chrome webdriver version: 123.0.6312.105 [ OK ] The driver has already been updated to the browser version!
> 
> [ INFO ] Initializing chrome-webdriver for Windows
> 
> DevTools listening on ws://127.0.0.1:12758/devtools/browser/371e5c21-cc26-4023-9052-4a4035739fa3
> 
> [ INFO ] [1secmail] Mail registration... [ FAILED ] Traceback (most recent call last): File "urllib3\connection.py", line 198, in _new_conn File "urllib3\util\connection.py", line 85, in create_connection File "urllib3\util\connection.py", line 73, in create_connection TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "urllib3\connectionpool.py", line 793, in urlopen File "urllib3\connectionpool.py", line 491, in _make_request File "urllib3\connectionpool.py", line 467, in _make_request File "urllib3\connectionpool.py", line 1099, in _validate_conn File "urllib3\connection.py", line 616, in connect File "urllib3\connection.py", line 213, in _new_conn urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000013D2BF04070>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "requests\adapters.py", line 486, in send File "urllib3\connectionpool.py", line 847, in urlopen File "urllib3\util\retry.py", line 515, in increment urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.1secmail.com', port=443): Max retries exceeded with url: /api/v1/?action=genRandomMailbox&count=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000013D2BF04070>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "main.py", line 111, in register File "requests\api.py", line 73, in get File "requests\api.py", line 59, in request File "requests\sessions.py", line 589, in request File "requests\sessions.py", line 703, in send File "requests\adapters.py", line 519, in send requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.1secmail.com', port=443): Max retries exceeded with url: /api/v1/?action=genRandomMailbox&count=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000013D2BF04070>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "main.py", line 930, in File "main.py", line 113, in register RuntimeError: SecEmailAPI: API access error!

Sometimes temporarily 1secmail can go away on tech. Maintenance. Just try again later.

**Comment by rzc0d3r** [comment]
And use latest version
