### ISSUE TITLE
GOOD JOB

### ISSUE THREAD

**Issue by gsmtronic** [rzc0d3r/ESET-KeyGen#169]
Hi rzc0d3r

first of all thank you for sharing the Account generator it works like a charm.
after I need your contact I have a project to do with you if you have the time.

**Comment by rzc0d3r** [comment]
Thx.
[My Telegram](https://t.me/rzc0d3r)

**Comment by rzc0d3r** [comment]
> Thx! [My Telegram](https://t.me/rzc0d3r)
