### ISSUE TITLE
процесс завершён с кодом выхода 100

### ISSUE THREAD

**Issue by stringer-popov** [rzc0d3r/ESET-KeyGen#173]
Привет, Артём.
Почему ошибка происходит?
Процесс завершён с кодом выхода 100

![крестик](https://github.com/rzc0d3r/ESET-KeyGen/assets/125668727/62822fe2-af1a-4655-b0d3-3d0d437304d0)
![ошибка](https://github.com/rzc0d3r/ESET-KeyGen/assets/125668727/e102867d-c3d8-436d-8598-146b4aa73b98)

**Comment by amizzo87** [comment]
getting the same issue

**Comment by rzc0d3r** [comment]
This is a global problem with Github servers. At this point, Github should have fixed this bug. Try again

**Comment by stringer-popov** [comment]
теперь такую ошибку выдаёт.
![1](https://github.com/rzc0d3r/ESET-KeyGen/assets/125668727/9c55b72c-7f44-445a-9ad9-ffebb8d5f34e)
![2](https://github.com/rzc0d3r/ESET-KeyGen/assets/125668727/e58156a7-1c71-495e-ab8a-701736082614)

**Comment by stringer-popov** [comment]
name: Generator

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      account:
        description: 'Number of Accounts to be generated (default = 0)'
        required: false
        default: '0'
      key:
        description: 'Number of Keys to be generated (default = 1)'
        required: false
        default: '1'
      mail:
        description: 'Choose the mail provider to generate license'
        required: true
        type: choice
        options:
        - 1secmail
        - hi2in
        - 10minutemail
        default: 1secmail

jobs:
  GenerateKey:
    runs-on: ubuntu-latest
    steps:
      - name: Generate key
        run: |
          ACCOUNT=${{ github.event.inputs.account }}
          KEY=${{ github.event.inputs.key }}
          MAIL=${{ github.event.inputs.mail }}
          git clone https://github.com/rzc0d3r/ESET-KeyGen.git
          cd ESET-KeyGen
          sudo apt update
          sudo apt install python3-pip
          sudo pip install -r requirements.txt
          #Initialise chrome driver
          python3 main.py --chrome --only-update
          
          if [[ (${ACCOUNT} != 0) && (${KEY} != 0) ]]
          then
          (seq 1 $((ACCOUNT)) | xargs -I {} -P $((ACCOUNT)) python3 main.py --chrome --account --email-api ${MAIL} --skip-webdriver-menu) & (seq 1 $((KEY)) | xargs -I {} -P $((KEY)) python3 main.py --chrome --key --email-api ${MAIL} --skip-webdriver-menu)
          echo "Account:" >> $GITHUB_STEP_SUMMARY
          cat ./*ACCOUNTS.txt >> $GITHUB_STEP_SUMMARY
          echo -e "\nKey:" >> $GITHUB_STEP_SUMMARY
          cat ./*KEYS.txt >> $GITHUB_STEP_SUMMARY
          exit
          fi
          
          if [[ ${ACCOUNT} != 0 ]]
          then
          seq 1 $((ACCOUNT)) | xargs -I {} -P $((ACCOUNT)) python3 main.py --chrome --account --email-api ${MAIL} --skip-webdriver-menu
          echo -e "\nAccount:" >> $GITHUB_STEP_SUMMARY
          cat ./*ACCOUNTS.txt >> $GITHUB_STEP_SUMMARY
          fi
          
          if [[ ${KEY} != 0 ]]
          then
          seq 1 $((KEY)) | xargs -I {} -P $((KEY)) python3 main.py --chrome --key --email-api ${MAIL} --skip-webdriver-menu
          echo -e "\nKey:" >> $GITHUB_STEP_SUMMARY
          cat ./*KEYS.txt >> $GITHUB_STEP_SUMMARY
          fi

**Comment by AdityaGarg8** [comment]
Hi2in should be removed since it needs captcha @rzc0d3r

**Comment by rzc0d3r** [comment]
> Hi2in should be removed since it needs captcha @rzc0d3r

7ac5b89b4d2847307c5dcf2f6a65295458affad3

**Comment by rzc0d3r** [comment]
Я добавил новый API почты. Также он работает в Github Actions, быстрее 1secmail :)

**Comment by serjio1914** [comment]
Уважаемое сообщество, подскажите:
раньше получал ключ в формате имя пароль для 5-й версии НОД
теперь --busines-key  дает ключ из 20-ти символов.
Возможно ли получать ключ для старой версии НОД или уже всё?

**Comment by AdityaGarg8** [comment]
> Dear community, please tell me: previously I received a key in the format name password for the 5th version of GCD, now --busines-key gives a key of 20 characters. Is it possible to get a key for the old version of GCD or is that all done?

I guess ESET has stopped giving those keys

**Comment by rzc0d3r** [comment]
> Уважаемое сообщество, подскажите:
> раньше получал ключ в формате имя пароль для 5-й версии НОД
> теперь --busines-key  дает ключ из 20-ти символов.
> Возможно ли получать ключ для старой версии НОД или уже всё?

При глобальном обновлении, сайт выдавал имя и пароль вместо ключа. Сейчас такого нет
