### ISSUE TITLE
Gmail

### ISSUE THREAD

**Issue by dztoshiba43** [rzc0d3r/ESET-KeyGen#180]
Can I use my Gmail to generate a key for ESET HOME Security Premium?

**Comment by rzc0d3r** [comment]
Yes, use command line argument ```--custom-email-api```

**Comment by rzc0d3r** [comment]
READ _Generation using your email provider (Totally manual method, but hyper stable)_: https://github.com/rzc0d3r/ESET-KeyGen/blob/main/wiki/KeyGenerator.md
