### ISSUE TITLE
Obtaining the key and data from the account (login/pass) in which it was created

### ISSUE THREAD

**Issue by AndriiiBut** [rzc0d3r/ESET-KeyGen#182]
I need to get not an empty account or a key, but both. When creating a key (--business-key), the script only produces a key, but no password for the account. Can I get it? Or at least at the last stage of the script, when the browser is open and you are logged into your account, do not close the browser with the script?

**Comment by rzc0d3r** [comment]
## Is that so?

![image](https://github.com/rzc0d3r/ESET-KeyGen/assets/106631540/2511b487-02a0-42f5-a42e-cc3c01469cd9)
![image](https://github.com/rzc0d3r/ESET-KeyGen/assets/106631540/b33c07a1-b34e-47a7-826f-c74411bd18dc)

**Comment by rzc0d3r** [comment]
![image](https://github.com/rzc0d3r/ESET-KeyGen/assets/106631540/fd1bbe64-69a2-4372-abcb-f50858ef063a)
![image](https://github.com/rzc0d3r/ESET-KeyGen/assets/106631540/8272d8b8-2a0b-4e1d-a207-e9933d1c0767)

**Comment by AndriiiBut** [comment]
Yes! Exactly what is needed!

**Comment by rzc0d3r** [comment]
I'll be releasing a global update in a couple hours.

**Comment by rzc0d3r** [comment]
https://github.com/rzc0d3r/ESET-KeyGen/releases/tag/v1.4.7.0

**Comment by AndriiiBut** [comment]
Thank you!
