### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MangoShow** [rzc0d3r/ESET-KeyGen#184]
-- WebDriver Auto-Installer --

[  INFO  ] Google Chrome version: 125.0.6422.60
[  INFO  ] Google Chrome webdriver version: None
[  INFO  ] Google Chrome webdriver not detected, download attempt...

[   OK   ] Found a suitable version for your system!
[  INFO  ] Downloading...
[   OK   ] Google Chrome webdriver was successfully downloaded and unzipped!

[  INFO  ] Initializing chrome-webdriver for Windows
[  INFO  ] Downloaded Google Chrome update is detected! Using new chrome executable file!

[  INFO  ] [developermail] Mail registration...
[   OK   ] Mail registration completed successfully!
[ FAILED ] Traceback (most recent call last):
  File "G:\Users\levas\Desktop\ESET-KeyGen-1.4.7.1\main.py", line 1144, in <module>
    EsetReg.createAccount()
  File "G:\Users\levas\Desktop\ESET-KeyGen-1.4.7.1\main.py", line 793, in createAccount
    exec_js = self.driver.execute_script
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'execute_script'

**Comment by MangoShow** [comment]
В общем, проблема с хромом, т.к у через эдж все гуд

**Comment by rzc0d3r** [comment]
Та я понимаю что гуд. Но ошибка крайне интересная. Обновитесь то последней версии и запустите также как и во время ошибки. И пришлите логи

**Comment by MangoShow** [comment]
Так это и есть [v1.4.7.1] ))

**Comment by MangoShow** [comment]
Вдобавок скажу, что переехал на новый диск с относительно чистой виндой. И в хроме висит чек на ошибку [0x80004005] который, по рекомендации, не убирается переустановкой браузера

**Comment by rzc0d3r** [comment]
> Вдобавок скажу, что переехал на новый диск с относительно чистой виндой. И в хроме висит чек на ошибку [0x80004005] который, по рекомендации, не убирается переустановкой браузера

Windows 7?

**Comment by rzc0d3r** [comment]
> Так это и есть [v1.4.7.1] ))

1.4.8.0 уже :)

**Comment by rzc0d3r** [comment]
> > Так это и есть [v1.4.7.1] ))
> 
> 1.4.8.0 уже :)

А то я же вижу по логам что не совпадает  с текущей

**Comment by MangoShow** [comment]
> > Вдобавок скажу, что сделали на новом диске с относительно чистой виндой. И в хроме посетите чек на ошибку [0x80004005], которая, по рекомендациям, не включается переустановкой браузера
> 
> Windows 7?

Никак нет, Win10

**Comment by MangoShow** [comment]
---- Main Menu ----

1 - Settings
2 - Do it, damn it!
3 - Exit

>>> 2

-- WebDriver Auto-Installer --

[  INFO  ] Google Chrome version: 125.0.6422.60
[  INFO  ] Google Chrome webdriver version: None
[  INFO  ] Google Chrome webdriver not detected, download attempt...

[   OK   ] Found a suitable version for your system!
[  INFO  ] Downloading...
[   OK   ] Google Chrome webdriver was successfully downloaded and unzipped!

[  INFO  ] Initializing chrome-webdriver for Windows
[ FAILED ] Traceback (most recent call last):
  File "main.py", line 273, in main
RuntimeError: Initialization chrome-webdriver error!

Press Enter to exit...

**Comment by MangoShow** [comment]
2 способ:

-- WebDriver Auto-Installer --

[  INFO  ] Google Chrome version: 125.0.6422.60
[  INFO  ] Google Chrome webdriver version: None
[  INFO  ] Google Chrome webdriver not detected, download attempt...

[   OK   ] Found a suitable version for your system!
[  INFO  ] Downloading...
[   OK   ] Google Chrome webdriver was successfully downloaded and unzipped!

[  INFO  ] Initializing chrome-webdriver for Windows
[ FAILED ] Traceback (most recent call last):
  File "G:\Users\levas\Desktop\ESET-KeyGen-1.4.8.0\main.py", line 273, in main
    raise RuntimeError(f'Initialization {browser_name}-webdriver error!')
RuntimeError: Initialization chrome-webdriver error!

**Comment by rzc0d3r** [comment]
Ну так уже понятней. Я это "пофиксил" в 1.4.8.0

**Comment by rzc0d3r** [comment]
Так хоть написало что ошибка является внутренней проблемой в библиотеке, а не у меня)

**Comment by rzc0d3r** [comment]
Ну кстати ошибка взязана скорее всего с корявым обновлением Chrome

**Comment by MangoShow** [comment]
> Ну кстати ошибка связана скорее всего с корявым обновлением Chrome

Тоже на это склоняюсь, других вариантов нет

**Comment by rzc0d3r** [comment]
Просто у меня тоже были с этим проблемы. Я и добавил несколько проверок на корявость обновления.

Можете попробовать использовать ```--custom-browser-location``` пропишите после этого ключа путь .ехе файлу хрома.

У вас их там будет скорее всего 2. Если не лень можете скинуть скрин папки хрома

**Comment by MangoShow** [comment]
![image](https://github.com/rzc0d3r/ESET-KeyGen/assets/123998649/5a1308bc-1343-46aa-a0e8-d5586bf8d352)

**Comment by MangoShow** [comment]
> Просто у меня тоже были с этим проблемы. Я и добавил несколько проверок на корявость обновления.
> 
> Можете попробовать использовать `--custom-browser-location` пропишите после этого ключа путь .ехе файлу хрома.
> 
> У вас их там будет скорее всего 2. Если не лень можете скинуть скрин папки хрома

--custom-browser-location действительно помог, спасибо
