### ISSUE TITLE
Doesn't work on Linux

### ISSUE THREAD

**Issue by slaver666** [rzc0d3r/ESET-KeyGen#187]
Hello. I've tried to run script with Chrome and Firefox web drivers but no success (see screenshots).
![Screenshot_2024-05-22_10-25-29](https://github.com/rzc0d3r/ESET-KeyGen/assets/63472976/971d3e71-7f9a-4f0f-9c88-a8b13b2e7300)
![Screenshot_2024-05-22_10-27-15](https://github.com/rzc0d3r/ESET-KeyGen/assets/63472976/e7a972cb-6212-473c-a008-40a5e0fad5e8)

**Comment by rzc0d3r** [comment]
I'll see what's there soon.  For now, use Github Actions

**Comment by rzc0d3r** [comment]
Please re-download the code of the latest commit (green button: Download) and try again

**Comment by rzc0d3r** [comment]
What system image are you using?
And what version of firefox do you have installed?

**Comment by slaver666** [comment]
Ubuntu 22.04. Firefox 125.0.3

**Comment by slaver666** [comment]
It happens nothing
![Screenshot_2024-05-22_12-14-44](https://github.com/rzc0d3r/ESET-KeyGen/assets/63472976/e934da1a-ae8f-451a-b5c6-a93ca0ae2b93)

**Comment by slaver666** [comment]
![Screenshot_2024-05-22_12-16-08](https://github.com/rzc0d3r/ESET-KeyGen/assets/63472976/b5df3e93-3e95-4aba-85c1-ece181cdb9ae)

**Comment by slaver666** [comment]
![Screenshot_2024-05-22_15-08-23](https://github.com/rzc0d3r/ESET-KeyGen/assets/63472976/afa53268-2d31-4185-ba56-afbd4f4b6fa9)

**Comment by rzc0d3r** [comment]
Installed ubuntu on the VM and as a result terminal does not even open. lmao

**Comment by rzc0d3r** [comment]
lol. I changed language to UK and now terminal is opens

**Comment by rzc0d3r** [comment]
have you had any problems with locales like that?

**Comment by rzc0d3r** [comment]
I can't even run the project code

**Comment by rzc0d3r** [comment]
It's already fixed: ```export PYTHONIOENCODING=utf-8``` on ubuntu terminal

**Comment by slaver666** [comment]
I have no any problems with terminal. Only errors on the screenshots.

**Comment by rzc0d3r** [comment]
![image](https://github.com/rzc0d3r/ESET-KeyGen/assets/106631540/eb80824b-ba3c-4e06-a898-30aefbbe55ab)

**Comment by rzc0d3r** [comment]
Try: [ESET-KeyGen-patch-1.zip](https://github.com/rzc0d3r/ESET-KeyGen/files/15403960/ESET-KeyGen-patch-1.zip)

**Comment by rzc0d3r** [comment]
data filling for Business arguments is also greatly accelerated

**Comment by slaver666** [comment]
Great! Now it's working. May be you can help me with error on the screenshot? I've tried on different hosts with Eset Server Security installed. I've tried different keys. No result. I can't even find that error code explanation. Thanks.

![Screenshot_2024-05-22_16-51-19](https://github.com/rzc0d3r/ESET-KeyGen/assets/63472976/8ba47989-a47e-4ba4-aa06-3748e5c9bd1c)
![Screenshot_2024-05-22_16-54-02](https://github.com/rzc0d3r/ESET-KeyGen/assets/63472976/577f4bc4-37ca-4d3c-9d12-4bbba9b713b9)

**Comment by rzc0d3r** [comment]
> Great! Now it's working. May be you can help me with error on the screenshot? I've tried on different hosts with Eset Server Security installed. I've tried different keys. No result. I can't even find that error code description. Thanks.
> 
> ![Screenshot_2024-05-22_16-51-19](https://private-user-images.githubusercontent.com/63472976/332824791-8ba47989-a47e-4ba4-aa06-3748e5c9bd1c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzODYzOTgsIm5iZiI6MTcxNjM4NjA5OCwicGF0aCI6Ii82MzQ3Mjk3Ni8zMzI4MjQ3OTEtOGJhNDc5ODktYTQ3ZS00YmE0LWFhMDYtMzc0OGU1YzliZDFjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDEzNTQ1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2OWMxZTAxYjMwZWZmMTIzYmFjNGFmMWNkNDFiMzdhNDQ1MGE2YTM4MDQ4Y2M1NzNiZjkwMDg2YmJkYWMxMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BL1G0VfF_9tQ_g5lBWzO9pamn7bTX6C9WO8AZpomC-8) ![Screenshot_2024-05-22_16-54-02](https://private-user-images.githubusercontent.com/63472976/332824828-577f4bc4-37ca-4d3c-9d12-4bbba9b713b9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzODYzOTgsIm5iZiI6MTcxNjM4NjA5OCwicGF0aCI6Ii82MzQ3Mjk3Ni8zMzI4MjQ4MjgtNTc3ZjRiYzQtMzdjYS00ZDNjLTlkMTItNGJiYmE5YjcxM2I5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDEzNTQ1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlY2I2NjJhOTkwODlkYzI5MGY4OGQ4MTU1N2E1YjQyYmE1YzU0YzBlNWVlOGQ1MTU5MjlkNDYyMDYwZDZhZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gIDCD2tEUO3ocKTNUBPC1Ey5YbZKcnoJ7vqzNtWlidc)

ESET started canceling the activation after a while with the business key. There is nothing you and I can do about it

**Comment by rzc0d3r** [comment]
> Great! Now it's working. May be you can help me with error on the screenshot? I've tried on different hosts with Eset Server Security installed. I've tried different keys. No result. I can't even find that error code description. Thanks.
> 
> ![Screenshot_2024-05-22_16-51-19](https://private-user-images.githubusercontent.com/63472976/332824791-8ba47989-a47e-4ba4-aa06-3748e5c9bd1c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzODYzOTgsIm5iZiI6MTcxNjM4NjA5OCwicGF0aCI6Ii82MzQ3Mjk3Ni8zMzI4MjQ3OTEtOGJhNDc5ODktYTQ3ZS00YmE0LWFhMDYtMzc0OGU1YzliZDFjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDEzNTQ1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2OWMxZTAxYjMwZWZmMTIzYmFjNGFmMWNkNDFiMzdhNDQ1MGE2YTM4MDQ4Y2M1NzNiZjkwMDg2YmJkYWMxMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BL1G0VfF_9tQ_g5lBWzO9pamn7bTX6C9WO8AZpomC-8) ![Screenshot_2024-05-22_16-54-02](https://private-user-images.githubusercontent.com/63472976/332824828-577f4bc4-37ca-4d3c-9d12-4bbba9b713b9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzODYzOTgsIm5iZiI6MTcxNjM4NjA5OCwicGF0aCI6Ii82MzQ3Mjk3Ni8zMzI4MjQ4MjgtNTc3ZjRiYzQtMzdjYS00ZDNjLTlkMTItNGJiYmE5YjcxM2I5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDEzNTQ1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlY2I2NjJhOTkwODlkYzI5MGY4OGQ4MTU1N2E1YjQyYmE1YzU0YzBlNWVlOGQ1MTU5MjlkNDYyMDYwZDZhZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gIDCD2tEUO3ocKTNUBPC1Ey5YbZKcnoJ7vqzNtWlidc)

you can also try ESET Endpoint security.

**Comment by rzc0d3r** [comment]
In general, if you just need an antivirus, use the standard ESET Internet Security Premium.

**Comment by rzc0d3r** [comment]
```--firefox --key```

**Comment by rzc0d3r** [comment]
https://www.eset.com/int/business/download/file-security-linux ?

**Comment by slaver666** [comment]
Hmmm! Great. I've checked official site two days ago and the last version was 10.2.41.0.
I'm going to try v.10.3.3.0

**Comment by rzc0d3r** [comment]
I'm gonna install it now and tinker with it.

**Comment by rzc0d3r** [comment]
## First activation after installation 
![image](https://github.com/rzc0d3r/ESET-KeyGen/assets/106631540/78a9eebb-2c5b-49d7-a1a8-f76b6e670663)

**Comment by slaver666** [comment]
I'm still downloading the package. Too slow speed to official download mirror today.

**Comment by rzc0d3r** [comment]
I just noticed that the business key is not just for Endpoint and Server.

**Comment by rzc0d3r** [comment]
For:
* ESET PROTECT Advanced
* ESET LiveGuard Advanced for Endpoint Security + Server Security
* ESET Full Disk Encryption
* ESET Mobile Threat Defense
* ESET Endpoint Security + ESET Server Security

**Comment by slaver666** [comment]
> For:
> 
> * ESET PROTECT Advanced
> * ESET LiveGuard Advanced for Endpoint Security + Server Security
> * ESET Full Disk Encryption
> * ESET Mobile Threat Defense
> * ESET Endpoint Security + ESET Server Security

Yes. I know.
Unfortunately it didn't help me. The same error code. I have no idea. May by Eset somehow blacklisted my IP or even host with antivirus installed.

**Comment by rzc0d3r** [comment]
you press activate with the key?

**Comment by rzc0d3r** [comment]
On Status Overview

**Comment by rzc0d3r** [comment]
Second re-activation was also successful

**Comment by slaver666** [comment]
Yes. I've tried to activate with web-interface and from console.

**Comment by rzc0d3r** [comment]
I apologize for not being able to fully solve your problem! Well, I honestly don't even have an idea

**Comment by rzc0d3r** [comment]
Very good!!

**Comment by rzc0d3r** [comment]
I can close issue?

**Comment by slaver666** [comment]
Sure
