### ISSUE TITLE
привет Артём, форк ошибку 255 выдаёт

### ISSUE THREAD

**Issue by stringer-popov** [rzc0d3r/ESET-KeyGen#188]
Annotations
1 error
GenerateKey
Process completed with exit code 255.
![255](https://github.com/rzc0d3r/ESET-KeyGen/assets/125668727/9540bd11-b781-4353-a1d8-4c1ba1e4a753)

**Comment by rzc0d3r** [comment]
Синхронизируйте ваш форк с моим проектом. Там на странице форка будет кнопка

**Comment by rzc0d3r** [comment]
Вам там напишет что ваш форк старее оригинала на сколько то там коммитов

**Comment by stringer-popov** [comment]
эта что-ли?
![способствовать](https://github.com/rzc0d3r/ESET-KeyGen/assets/125668727/ed6b5c89-b09d-4577-b53b-f85f5305b90d)

**Comment by rzc0d3r** [comment]
Вилка синхронизации

**Comment by stringer-popov** [comment]
эта кнопка?
![вилка синхронизации](https://github.com/rzc0d3r/ESET-KeyGen/assets/125668727/960f6945-4175-4c70-9814-c7179b97a85d)

**Comment by rzc0d3r** [comment]
А это вернет тесты. Ну ладно отменяйте 1 коммит и синхронизируйте

**Comment by rzc0d3r** [comment]
Тогда опять удалите test.yml с папки .github

**Comment by rzc0d3r** [comment]
Я вам потом покажу как можно отключить уведомление о автоматических тестах

**Comment by Xoncia** [comment]
![image](https://github.com/rzc0d3r/ESET-KeyGen/assets/65108569/adde2b00-994c-4939-841a-a26f2d8b3b11)
this?

**Comment by rzc0d3r** [comment]
> ![image](https://github.com/rzc0d3r/ESET-KeyGen/assets/65108569/adde2b00-994c-4939-841a-a26f2d8b3b11)
> this?

yes

**Comment by stringer-popov** [comment]
Артём я удалил test.yml, но он снова появился.
![удалить файл](https://github.com/rzc0d3r/ESET-KeyGen/assets/125668727/26d902d1-c478-4373-8617-ee296911ed1a)

**Comment by rzc0d3r** [comment]
Да я же говорил. Можете его уже удалить. Дальше просто генерирует себе. Вы должны синхронизировать форк регулярно. Для обновлений
