### ISSUE TITLE
[ FAILED ] not enough values to unpack 

### ISSUE THREAD

**Issue by elyeandre** [rzc0d3r/ESET-KeyGen#19]
![image](https://github.com/rzc0d3r/ESET-KeyGen/assets/96169920/ecacb853-767d-4de3-acc1-cfcd882834d2)

**Comment by rzc0d3r** [comment]
My omission.  But still, if I fix it, it will tell you that you do not have chrome installed.  Do you have it installed?

**Comment by rzc0d3r** [comment]
Try v1.0.8.2 (151023-2234) Release

**Comment by elyeandre** [comment]
> My omission. But still, if I fix it, it will tell you that you do not have chrome installed. Do you have it installed?

No, because the older version that I tried did not require a Chrome driver and still works.

**Comment by rzc0d3r** [comment]
does the old version work?

**Comment by rzc0d3r** [comment]
The keys must be universal.  Еset himself wrote.  Even suitable for Android

**Comment by elyeandre** [comment]
> does the old version work?

I tried it yesterday, didn't work

**Comment by rzc0d3r** [comment]
Different devices in different countries and each has its own error. I don't even know how to help you

**Comment by rzc0d3r** [comment]
What information does it freeze on in the console?

**Comment by rzc0d3r** [comment]
When I'm home I'll check if it works.  Perhaps something was changed and because of this it freezes on the pop-up dialogue

**Comment by rzc0d3r** [comment]
The project is working.
