### ISSUE TITLE
Implementing actions

### ISSUE THREAD

**Issue by soujiang** [rzc0d3r/ESET-KeyGen#190]
Hi, I have a question. If you use Chromium to generate passwords and a disposable email account, and there's another repository that does something similar for creating API keys for ElevenLabs, could you take a look to see how actions can be implemented in that other repository? I'm new to this, so I'm not quite sure how to do it or if it's possible. The idea is that, just like in the case of the ESET repository you've created, ElevenLabs API keys can be generated using actions, whether they run on the PC or in the GitHub app.

I've forked the repository where I want to implement actions, so you can take a look if you want. Thanks, bro!

Here is the repository: https://github.com/soujiang/elevenlabs-unleashed

**Comment by rzc0d3r** [comment]
Let's discuss this on telegram, shall we?

**Comment by rzc0d3r** [comment]
[Telegram](https://t.me/rzc0d3r)
