### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ZilvinasLasauskas** [rzc0d3r/ESET-KeyGen#192]
..
[   OK   ] Access to the request was open!
[ FAILED ] Traceback (most recent call last):
  File "modules\EsetTools.py", line 100, in sendRequestForKey
    uCE(self.driver, f"return {CLICK_WITH_BOOL}({GET_EBAV}('ion-button', 'robot', 'license-fork-slide-continue-button'))")
  File "modules\SharedTools.py", line 127, in untilConditionExecute
    raise RuntimeError('untilConditionExecute: the code did not return the desired value! TRY VPN!')
RuntimeError: untilConditionExecute: the code did not return the desired value! TRY VPN!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 359, in main
    EsetKeyG.sendRequestForKey()
  File "modules\EsetTools.py", line 102, in sendRequestForKey
    raise RuntimeError('Access to the request is denied, try again later!')
RuntimeError: Access to the request is denied, try again later!

**Comment by ZilvinasLasauskas** [comment]
the same shit, stops at this step:

![image](https://github.com/rzc0d3r/ESET-KeyGen/assets/51168294/16caaa2b-867b-47e9-a6de-b503304cd794)

**Comment by rzc0d3r** [comment]
I don't know what the hang is related to. But the interesting thing is that everything works but hangs. The error appears randomly and I can't solve it for a long time.

**Comment by rzc0d3r** [comment]
try [ESET-KeyGen-v1.4.9.1-dev.zip](https://github.com/rzc0d3r/ESET-KeyGen/files/15470015/ESET-KeyGen-v1.4.9.1-dev.zip)

**Comment by rzc0d3r** [comment]
Anyway, it turns out the site's been changed a bit. The elements are different.

**Comment by rzc0d3r** [comment]
I'm going to change everything to new

**Comment by ZilvinasLasauskas** [comment]
ok, will wait

**Comment by rzc0d3r** [comment]
Try [ESET-KeyGen-v1.4.9.1-dev2.zip](https://github.com/rzc0d3r/ESET-KeyGen/files/15470430/ESET-KeyGen-v1.4.9.1-dev.zip)

**Comment by ZilvinasLasauskas** [comment]
nothing, hangs at the same step

**Comment by rzc0d3r** [comment]
logs?

**Comment by rzc0d3r** [comment]
> e generation is already stable. I checked the generation of 50 keys.

use github actions

**Comment by Xoncia** [comment]
interesting, could be a different xpath, not sure

**Comment by ZilvinasLasauskas** [comment]
> The generation is already stable. I checked the generation of 50 keys.

well, now it works fine. thanks.
