### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by Aioloz1971** [rzc0d3r/ESET-KeyGen#193]
Привет, Артём! Версия 1.4.9.1 останавливается на этом шаге:
![IMG_20240530_155142](https://github.com/rzc0d3r/ESET-KeyGen/assets/163140432/9422b74c-784b-40c4-9020-079b1643faaf)

**Comment by rzc0d3r** [comment]
Пока да есть проблемы со стабильностью в этом месте. Сообщалось что если уменьшить масштаб страницы, то ошибка должна исчезнуть. Попробуйте уменьшить масштаб страницы с помощью ```Cntrl -``` На странице регистрации

**Comment by rzc0d3r** [comment]
Запускайте в режиме ```--no-headless```

**Comment by rzc0d3r** [comment]
> Пока да есть проблемы со стабильностью в этом месте. Сообщалось что если уменьшить масштаб страницы, то ошибка должна исчезнуть. Попробуйте уменьшить масштаб страницы с помощью `Cntrl -` На странице регистрации

пока что это не делайте! Попробуйте новую версию которую я вам только что скинул

**Comment by Aioloz1971** [comment]
Прочитать ответ не успел. Уменьшение масштаба страницы до 50% помогло.

**Comment by rzc0d3r** [comment]
> Прочитать ответ не успел. Уменьшение масштаба страницы до 50% помогло.

Ничего страшного. попробуйте теперь эту версию но без масштаба

**Comment by rzc0d3r** [comment]
Просто есть проблема в том что нет доступных пока что решений как в коде уменьшить масштаб страницы. хах

**Comment by Aioloz1971** [comment]
Боюсь, что не смогу в этом случае помочь - у меня не установлены ни Python, ни репозиторий гитхабовский...

**Comment by Aioloz1971** [comment]
Но за совет большое спасибо!

**Comment by rzc0d3r** [comment]
> Боюсь, что не смогу в этом случае помочь - у меня не установлены ни Python, ни репозиторий гитхабовский...

Скоро отправлю первую реализацию уменьшения масштаба

**Comment by rzc0d3r** [comment]
> > Боюсь, что не смогу в этом случае помочь - у меня не установлены ни Python, ни репозиторий гитхабовский...
> 
> Скоро отправлю первую реализацию уменьшения масштаба в виде .ехе
