### ISSUE TITLE
error selenium

### ISSUE THREAD

**Issue by XHub157** [rzc0d3r/ESET-KeyGen#194]
C:\активатор>main.py --chrome --key
Traceback (most recent call last):
  File "C:\активатор\main.py", line 1, in <module>
    from modules.WebDriverInstaller import *
  File "C:\активатор\modules\WebDriverInstaller.py", line 1, in <module>
    from .SharedTools import console_log, INFO, OK, ERROR
  File "C:\активатор\modules\SharedTools.py", line 1, in <module>
    from selenium.webdriver import Chrome, ChromeOptions, ChromeService
ModuleNotFoundError: No module named 'selenium'

**Comment by rzc0d3r** [comment]
В cmd:
```
pip uninstall selenium
pip install selenium
```

**Comment by XHub157** [comment]
> В cmd:
> 
> ```
> pip uninstall selenium
> pip install selenium
> ```
The error remains

**Comment by rzc0d3r** [comment]
Значит у вас 2 разных python установлено

**Comment by rzc0d3r** [comment]
pip привязан к 1, а запускаете на втором

**Comment by XHub157** [comment]
сейчас попробую снести python и поставить заново

**Comment by XHub157** [comment]
Всё заработало после удаления второй версии в укромном месте)

**Comment by XHub157** [comment]
[ FAILED ] Traceback (most recent call last):
  File "C:\активатор\main.py", line 359, in main
    EsetKeyG.sendRequestForKey()
  File "C:\активатор\modules\EsetTools.py", line 111, in sendRequestForKey
    exec_js(f"return {GET_EBID}('email')").send_keys(self.email_obj.email)
  File "C:\Users\Yury7\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 231, in send_keys
    self._execute(
  File "C:\Users\Yury7\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yury7\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Yury7\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome-headless-shell=125.0.6422.144)

**Comment by rzc0d3r** [comment]
> [ FAILED ] Traceback (most recent call last): File "C:\активатор\main.py", line 359, in main EsetKeyG.sendRequestForKey() File "C:\активатор\modules\EsetTools.py", line 111, in sendRequestForKey exec_js(f"return {GET_EBID}('email')").send_keys(self.email_obj.email) File "C:\Users\Yury7\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 231, in send_keys self._execute( File "C:\Users\Yury7\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 395, in _execute return self._parent.execute(command, params) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Yury7\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute self.error_handler.check_response(response) File "C:\Users\Yury7\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response raise exception_class(message, screen, stacktrace) selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable (Session info: chrome-headless-shell=125.0.6422.144)

запускаете в режиме ```--no-headless``` и когда появится страница в окне браузера, то сделайте уменьшение масштаба страницы с помощью ```Cntrl + колесико мыши```

**Comment by rzc0d3r** [comment]
Такое уже случалось и не раз.

**Comment by kubiszxc** [comment]
[ FAILED ] Traceback (most recent call last):
  File "main.py", line 291, in main
  File "modules\WebDriverInstaller.py", line 335, in menu
RuntimeError: Google Chrome was not found in the standard catalogs!

**Comment by rzc0d3r** [comment]
> [ FAILED ] Traceback (most recent call last): File "main.py", line 291, in main File "modules\WebDriverInstaller.py", line 335, in menu RuntimeError: Google Chrome was not found in the standard catalogs!

Use another browser or type full path to chrome.exe to ```--custom-browser-location```
