### ISSUE TITLE
error code 255

### ISSUE THREAD

**Issue by speedfreekz28** [rzc0d3r/ESET-KeyGen#195]
main.py: error: one of the arguments --key --account --business-account --business-key --only-webdriver-update --update is required
Error: Process completed with exit code 255.

please help with this code not sure whats going on
thanl you

**Comment by rzc0d3r** [comment]
you left out the mandatory argument in the startup arguments.

**Comment by rzc0d3r** [comment]
always specify the browser to be used and the type of script operation

**Comment by rzc0d3r** [comment]
### Required arguments

Browsers: ```--chrome```, ```--edge```, ```--firefox```
Type of operation: ```--key```, ```--account```, ```--business-account```, ```--business-key```, ```--only-webdriver-update```, ```--update```

**Comment by rzc0d3r** [comment]
https://github.com/rzc0d3r/ESET-KeyGen/blob/main/wiki/CommandLineArguments.md

**Comment by speedfreekz28** [comment]
Thank you for your help
