### ISSUE TITLE
How to decrypt the python code

### ISSUE THREAD

**Issue by AdityaGarg8** [rzc0d3r/ESET-KeyGen#196]
I was thinking a creating an android app from the python code but it seems to be encrypted. How do I decrypt it?

**Comment by rzc0d3r** [comment]
[SourceCode_ESET-KeyGen-v1.4.9.1.zip](https://github.com/user-attachments/files/16280156/SourceCode_ESET-KeyGen-v1.4.9.1.zip)

**Comment by rzc0d3r** [comment]
I will need to change the method of code packing because I can't automate code unpacking because of byte problems.

**Comment by rzc0d3r** [comment]
Use https://github.com/rzc0d3r/PyCompressor

**Comment by AdityaGarg8** [comment]
Thanks!

**Comment by rzc0d3r** [comment]
I removed the encryption and returned the normal source code. I was also able to trick eset antivirus. Now the source code is no longer removed by antivirus when scanning and running!!!

**Comment by AdityaGarg8** [comment]
Lmao
