### ISSUE TITLE
Request for selecting eset version

### ISSUE THREAD

**Issue by 520rahul** [rzc0d3r/ESET-KeyGen#197]
Hi sir,

First of all thanks a ton for such a wonderful utility. I have small request plz insert the option to select version of eset in repo. As i have old pc and i want to run eset nod32 antivirus only but thr repo provided the key for home security premium which is higher version..i will be highly obliged if u would provide the option for selecting the versin. Thanks in advance and kudos for ur work.

**Comment by rzc0d3r** [comment]
As far as I know. During activation you can change the product if it is older than the license in the key

**Comment by rzc0d3r** [comment]
Create ESET HOME accounts and use them for activation, each created account has the possibility to create a license for a specific activirus edition.

**Comment by rzc0d3r** [comment]
Create an account, select activation via ESET HOME account in the antivirus, enter the data and click try free. That's it!

**Comment by 520rahul** [comment]
Thanks u will try this method
