### ISSUE TITLE
ошибка, второй день

### ISSUE THREAD

**Issue by Lobasheff** [rzc0d3r/ESET-KeyGen#198]
![Ошибка](https://github.com/user-attachments/assets/d63afc26-b877-4a1c-93b0-6eab34ec676c)

**Comment by verisat** [comment]
Какие-то проблемы с почтовым сервером. В свойствах ярлыка добавь `--email-api 1secmail`, должно помочь.

Вообще, можно использовать любой аргумент из руководства: --email-api {1secmail, hi2in, 10minutemail, tempmail, guerrillamail, developermail} или вообще --custom-email-api.

**Comment by Lobasheff** [comment]
![Uploading ошибка.jpg…]()

**Comment by Lobasheff** [comment]
при добавлении выходит окно и сразу же закрывается
![ошибка 1](https://github.com/user-attachments/assets/59b2599c-a898-4e8b-a71b-35d2fde82148)

**Comment by Lobasheff** [comment]
Все, разобрался в настройках приложения поменял email-api

**Comment by Lobasheff** [comment]
вопрос закрыт

**Comment by rzc0d3r** [comment]
> Какие-то проблемы с почтовым сервером. В свойствах ярлыка добавь `--email-api 1secmail`, должно помочь.
> 
> Вообще, можно использовать любой аргумент из руководства: --email-api {1secmail, hi2in, 10minutemail, tempmail, guerrillamail, developermail} или вообще --custom-email-api.
> 

Лучший!
