### ISSUE TITLE
Add ESET Internet Security, NOD32 key generator.

### ISSUE THREAD

**Issue by kapi3511** [rzc0d3r/ESET-KeyGen#2]
Is it possible to choose to which ESET edition generate key? Smart Security has (for me) some unnecessary features, that only slows down my potato PCs. Is it even possible?

Thanks in advance :)

**Comment by rzc0d3r** [comment]
Automatically eset gives the best edition. ESET Internet Security Premium features can be disabled in ESET settings

**Comment by kapi3511** [comment]
Okay, I thought this features were annoying like the avast one (for example password manager). Thanks! Awesome script!!!
