### ISSUE TITLE
'list' object has no attribute 'lower'

### ISSUE THREAD

**Issue by its-yuu** [rzc0d3r/ESET-KeyGen#20]
its an error i get in the latest version and some old version that i've tried.

im using this in virtual machine running windows 7 Home premium
google version is 109.0.5414.120
python v3.8.8 with selenium request and colorama installed

**Comment by rzc0d3r** [comment]
My program does not use the lower function. 
To understand the reason, you need to edit 'ESET KeyGen.py': replace line 303 to raise(E). And send the result here

**Comment by its-yuu** [comment]
is this right?

except Exception as E:
    logger.console_log(raise(E), logger.ERROR)

im getting syntax error.

**Comment by rzc0d3r** [comment]
Just raise E

**Comment by its-yuu** [comment]
im getting the input now but cmd is closing after the input so i cant save it. sorry i never learned python before im still in grade school but i managed to fix it by installing new win10 os on vm and run it there. it works smoothly thanks dev.
