### ISSUE TITLE
Проблема с обновой

### ISSUE THREAD

**Issue by MangoShow** [rzc0d3r/ESET-KeyGen#200]
Привет, автор. Такую беду выдает. Браузер эдж, остальное дефолт
![Скриншот 29-07-2024 202354](https://github.com/user-attachments/assets/57eab16d-b42d-4f8a-a052-db7b494af095)

**Comment by rzc0d3r** [comment]
должно заработать, но я пока посмотрю что с обновлением

**Comment by rzc0d3r** [comment]
у вас видимо 2 версии edge на пк

**Comment by rzc0d3r** [comment]
можете также попробывать ввести полный путь к браузеру

**Comment by rzc0d3r** [comment]
> у вас видимо 2 версии edge на пк

считывается главный установленый edge, а не какой-то другой. От оно находит 125 версию на ПК, но библиотека запускает  127 версию браузера

**Comment by MangoShow** [comment]
Да, сработало. Вроде один у меня эдж, но в нем недавно была обнова, мб что-то остаточное

**Comment by rzc0d3r** [comment]
От оно находит его в этих каталогах
![image](https://github.com/user-attachments/assets/983effb8-e287-4337-9e4c-69be73f914e4)

И если edge есть в первой пути, то используется этот, если нет, то по второму пути.

Возможно мне стоит настроить библиотеку так, чтобы она еще переопределяла путь.

Я скоро скину вам тестовую версию

**Comment by MangoShow** [comment]
Хорошо, жду)

**Comment by MangoShow** [comment]
Сейчас глянул. У меня точно один эдж, лежит на втором пути

**Comment by rzc0d3r** [comment]
[ESET-KeyGen-v1.4.9.4.zip](https://github.com/user-attachments/files/16417236/ESET-KeyGen-v1.4.9.4.zip)

**Comment by rzc0d3r** [comment]
Запускайте как вы запускали, когда ошибка появлялась

**Comment by rzc0d3r** [comment]
наверное у вас python не установлен

**Comment by rzc0d3r** [comment]
Давайте вам соберу .ехе

**Comment by rzc0d3r** [comment]
[ESET-KeyGen-v1.4.9.4.exe.zip](https://github.com/user-attachments/files/16417285/ESET-KeyGen-v1.4.9.4.zip)

**Comment by MangoShow** [comment]
![Скриншот 29-07-2024 211448](https://github.com/user-attachments/assets/aa00ee56-4a1e-40f4-a3d4-54c32998e5b3)

**Comment by rzc0d3r** [comment]
По пути который в ошибке есть msedge.exe?

**Comment by MangoShow** [comment]
Так точно

**Comment by rzc0d3r** [comment]
Если честно я немного в недоумении

**Comment by rzc0d3r** [comment]
Не могли вы бы создать сессию в TeamViewer, я смогу подключится и подробно проанализировать проблему конкретно в вашем случае. Это будет самым лучшим способом. Клянусь ничего красть и ломать не буду

**Comment by MangoShow** [comment]
Проверить нужно релизнутую версию или тестовую?

**Comment by MangoShow** [comment]
![image](https://github.com/user-attachments/assets/ded134da-165d-4d22-8e61-4816a23200d6)
Сейчас на чистой виртуалке установил и такая ошибка

**Comment by rzc0d3r** [comment]
На ней видимо нет edge

**Comment by MangoShow** [comment]
Так, на виртуалке все ок, а какие действия будут через удаленку производиться?)

**Comment by rzc0d3r** [comment]
> Так, на виртуалке все ок, а какие действия будут через удаленку производиться?)

Буду изменять код пока не заработает

**Comment by rzc0d3r** [comment]
А то мне вообще не ясно что происходит

**Comment by MangoShow** [comment]
К сожалению, я пожалуй откажусь. Очевидно проблема на моей стороне, т.к на вирт. машине все ок. Главное, что проблема решилась `--skip-webdriver-menu`
Спасибо!

**Comment by rzc0d3r** [comment]
Ладно. Удачи!
