### ISSUE TITLE
business-account no work...

### ISSUE THREAD

**Issue by tka4ev** [rzc0d3r/ESET-KeyGen#201]
Приветствую, ещё пару дней назад всё работало нормально, а сегодня такая картина.

![Error](https://github.com/user-attachments/assets/ef98fdf9-fa15-42c4-b36c-c2d7c3395729)

**Comment by rzc0d3r** [comment]
Они придумали какой-то ESET PROTECT Hub

**Comment by rzc0d3r** [comment]
Нужно с нуля переделывать Business генерацию

**Comment by rzc0d3r** [comment]
Походу все

**Comment by rzc0d3r** [comment]
Для регистрации нужен Регистрационный номер компании (CRN)

**Comment by rzc0d3r** [comment]
А еще VAT номер

**Comment by rzc0d3r** [comment]
Вообщем зарегистироватся можно, только от потом сгенерировать ключ нельзя. Возможность есть, но оно не работает

**Comment by slybunda** [comment]
its now blocked by ESET.

**Comment by rzc0d3r** [comment]
В будущем добавлю
