### ISSUE TITLE
Crash on the attempt of generating the key...

### ISSUE THREAD

**Issue by cYpxHSx** [rzc0d3r/ESET-KeyGen#202]
Hello. I frequently use your keygen and I'm happy about it. But I just happened to face a problem. I haven't seen a discussion about it, so I decided to do it.

So, I have updated to the latest version and tried to generate a key. But when the keygen proceeds to do its work, it suddenly closes the program. I tried a few more times, but the result was the same.

Here is the screenshot;

![prob](https://github.com/user-attachments/assets/97603b81-9e67-40e5-ac24-303f49d547a0)

Hope that helps. I'll use GitHub action for now, but I want to use the EXE once this problem is solved.

**Comment by rzc0d3r** [comment]
This issue was resolved in 1.4.9.6, but the release had to be delayed due to the presence of firefox issues

**Comment by rzc0d3r** [comment]
At this moment, I recommend using command line arguments:

```--skip-webdriver-update --custom-browser-location "full path to firefox.exe"```

**Comment by cYpxHSx** [comment]
Okay, thank you very much. I'll keep it in mind and await the next update. I already licensed my ESET through Github actions, so it's no problem.

Keep up the good work.
