### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by Lobasheff** [rzc0d3r/ESET-KeyGen#205]
![Ошибка](https://github.com/user-attachments/assets/5031d03a-bf94-4817-8bb2-0c613e91f688)
Сегодня такую ошибку выдал

**Comment by MaKeSter333** [comment]
+

**Comment by andyndim** [comment]
As I see, the button for obtaining a trial key is missing on the eset account page. Without this, no one can get the key.

**Comment by roobert74** [comment]
> same thing

Me too !

**Comment by rzc0d3r** [comment]
Только активация через аккаунт работает

**Comment by rzc0d3r** [comment]
https://github.com/rzc0d3r/ESET-KeyGen/releases/tag/v1.5.0.0
