### ISSUE TITLE
Error Generate using Github

### ISSUE THREAD

**Issue by ChandraOrbit** [rzc0d3r/ESET-KeyGen#206]
I get an error I generate by using the Generate action on github

```
[  INFO  ] Sending a request for a license...
[ FAILED ] Traceback (most recent call last):
  File "/home/runner/work/ESET-KeyGen/ESET-KeyGen/ESET-KeyGen/main.py", line 329, in main
    EK_obj.sendRequestForKey()
  File "/home/runner/work/ESET-KeyGen/ESET-KeyGen/ESET-KeyGen/modules/EsetTools.py", line 116, in sendRequestForKey
    exec_js(f"return {GET_EBID}('email')").send_keys(self.email_obj.email)
AttributeError: 'NoneType' object has no attribute 'send_keys'

cat: './*KEYS.txt': No such file or directory
Error: Process completed with exit code 1.
##[debug]Finishing: Generate key
```

**Comment by rzc0d3r** [comment]
Now works only creating account

**Comment by roobert74** [comment]
> Now works only creating account
I create an account,but i have the same error.

**Comment by rzc0d3r** [comment]
> > Now works only creating account
> > I create an account,but i have the same error.

screenshot?

**Comment by rzc0d3r** [comment]
https://github.com/rzc0d3r/ESET-KeyGen/actions/runs/10288242851

**Comment by sunbin1949** [comment]
> https://github.com/rzc0d3r/ESET-KeyGen/actions/runs/10288242851

It works to create accounts, but at the very least in my case, it shows that they have no subscription, I even tried using the accounts you have created here. Is this something to do with having ESET being already installed (it did not do this, before today), or is it just not working?

**Comment by rzc0d3r** [comment]
https://github.com/rzc0d3r/ESET-KeyGen/releases/tag/v1.5.0.0

**Comment by sunbin1949** [comment]
You are a legend!!
