### ISSUE TITLE
I'm absolute newbee, help me please

### ISSUE THREAD

**Issue by Vagabung** [rzc0d3r/ESET-KeyGen#21]
![image](https://github.com/rzc0d3r/ESET-KeyGen/assets/148178155/141c333e-f978-4883-8c94-92f37cd5c499)
how can i fix it? i updated chrome and selenium to latest version

**Comment by its-yuu** [comment]
did u install the python libraries?. 
if not go to cmd and type " pip install selenium request colorama " 
or the provided code in description(i think u should set the path first)

if pip doesn't work u should set the PATH first of pip, in windows environment variables (u can see how to do this in internet)

**Comment by Vagabung** [comment]
still not work

**Comment by rzc0d3r** [comment]
chromedriver.exe is exists inside project folder?

**Comment by rzc0d3r** [comment]
Try using cmd to add chromedriver.exe to PATH.

```
setx PATH "%PATH%;%0"
```

**Comment by Vagabung** [comment]
same again(

**Comment by Vagabung** [comment]
chromedriver.exe yes

**Comment by rzc0d3r** [comment]
Try [pre-release v1.0.8.3-181023-0013](https://github.com/rzc0d3r/ESET-KeyGen/releases/tag/pre-release-v1.0.8.3-181023-0013)
