### ISSUE TITLE
App stuck on "License uploads"

### ISSUE THREAD

**Issue by shniagrcia** [rzc0d3r/ESET-KeyGen#213]
Hello again, I'm having a problem, the app is stuck on this screen, i'm using --edge --endpoint-key --email-api 10minutemail

![1](https://github.com/user-attachments/assets/dc33e755-7355-441d-8b27-d79c81ec96dd)

![2](https://github.com/user-attachments/assets/89bd6467-2c97-44d4-b7e3-3193b18bd96a)

![3](https://github.com/user-attachments/assets/1b085f28-5efe-4d60-a6f3-18e776aa4c1b)

**Comment by rzc0d3r** [comment]
In fact, everything was written to you in the console. The letter with the key never arrived.

**Comment by shniagrcia** [comment]
> In fact, everything was written to you in the console. The letter with the key never arrived.

Now I use --protecthub-account to get the endpoint key manually

So, is there no way for me to get the endpoint key automatically?

**Comment by rzc0d3r** [comment]
> > In fact, everything was written to you in the console. The letter with the key never arrived.
> 
> Now I use --protecthub-account to get the endpoint key manually
> 
> So, is there no way for me to get the endpoint key automatically?

Use ```--endpoint-key``` together with ```--custom-email-api``` it is much more stable.

**Comment by shniagrcia** [comment]
Thankyou mate!

![4](https://github.com/user-attachments/assets/9f734ff0-adea-4361-86bf-33b6cdf4232a)

![5](https://github.com/user-attachments/assets/70f0b947-9792-43cc-9e58-e512d6d41097)
