### ISSUE TITLE
 small business key

### ISSUE THREAD

**Issue by pinkyellowed** [rzc0d3r/ESET-KeyGen#217]
keep in mind im fairly new to this. I ran the GitHub actions workflow and made the account etc, but i noticed its only a trial version as i logged into the home version. 
i want to get the small business key hoping that its like a serializer premium.
how do i run this commands? i uninstalled eset but i still have the random acc/email/key etc associated
should i restart this process and do it through terminal and not fork it ? 
OS Sonoma 14.6.1

**Comment by rzc0d3r** [comment]
The program gives both a key and an account with trial access
