### ISSUE TITLE
test & update

### ISSUE THREAD

**Issue by pinkyellowed** [rzc0d3r/ESET-KeyGen#218]
i'm very new to this bare with me .
i ran the test and update after it failed, it failed.
i changed the main branch to macos latest
and changed the push changes to checkout code
and im still not working, im getting a invaild exit code.

(note this isnt a issue for me ? as the app is working perfectly fine and is running)
<img width="827" alt="Screenshot 2024-09-05 at 12 57 30 PM" src="https://github.com/user-attachments/assets/2e1a40c7-a1e0-4622-8269-2e7abc7c2ddb">

**Comment by rzc0d3r** [comment]
You need to add the token to the project's secret variables in its settings. Generate a token with permission to write project files, you can generate it in your gitHub account settings

**Comment by rzc0d3r** [comment]
![IMG_20240905_230031](https://github.com/user-attachments/assets/4757c399-ef0a-407d-9e49-6530c52dec73)

**Comment by rzc0d3r** [comment]
![IMG_20240905_230430](https://github.com/user-attachments/assets/3e603bf7-5266-45ae-b3ae-1f15a57c4e2e)

After the ```secrets.``` You must specify the name of the variable you created in the project secrets. If mine is called PAT, then I specify that.

**Comment by rzc0d3r** [comment]
> You need to add the token to the project's secret variables in its settings. Generate a token with permission to write project files, you can generate it in your gitHub account settings

https://github.com/settings/personal-access-tokens/new

Repository permissions:
* Read access to metadata
* Read and Write access to actions and code
