### ISSUE TITLE
vpn through own dns

### ISSUE THREAD

**Issue by pinkyellowed** [rzc0d3r/ESET-KeyGen#219]
i tried config'n the vpn through my own dns and it doesnt allow my internet to function at all with any vpn protcols on - it sometimes works if i change the protocol and some times it doesnt. i tried hard wiring it through the system settings but it doesnt filter through my dns server i pick

Is there a way for the vpn to use my dns server

**Comment by rzc0d3r** [comment]
There is no proxy and vpn configuration option in the program, alas. I do not deal with such problems!
