### ISSUE TITLE
Use telegram to automatically return the key

### ISSUE THREAD

**Issue by hlanr1** [rzc0d3r/ESET-KeyGen#22]
Can it be used with telegram? It means that directly through telegram, input the command and the key will be automatically generated.

**Comment by rzc0d3r** [comment]
Make Telegram integration?  Well, for this I need to create a bot.  The problem here is that one bot = one device.  And creating a public one will be problematic.  I suggest this option: deploy the telegram server manually and use it

**Comment by hlanr1** [comment]
Good idea, can you please provide a tutorial on how to use telegram to connect to ESET-KeyGen?

**Comment by rzc0d3r** [comment]
The plan is as follows:

1. Receive a token from BotFather

2. Save the token to the program.

3. Installing some telegram API library.

4. Creating a trigger for the key creation command.

5. Listening to input data from telegrams.

6. Execution of the algorithm for obtaining the key and write outputs not to the console but to pm in TG

**Comment by rzc0d3r** [comment]
I'll add this to my notes thank you.

**Comment by hlanr1** [comment]
Looking forward to your success
