### ISSUE TITLE
test update error code 255, was error code 1 

### ISSUE THREAD

**Issue by pinkyellowed** [rzc0d3r/ESET-KeyGen#220]
the update im getting is getting a error for generate key and update the test time
main.py: error: argument --email-api: invalid choice: 'devleropmail' (choose from '1secmail', '10minutemail', 'guerrillamail', 'developermail', 'mailticking')
Error: Process completed with exit code 255.

i noticed developermail is spelt incorrect?

i had a look on the update test.yml file, line 2 has developermail spelt as devleropmail im not sure if this is the issue but i keep pushing the updates it was initial first a error code  exit 1. fetching the API and now its error code 255 btw

**Comment by rzc0d3r** [comment]
I don't have any typos

**Comment by rzc0d3r** [comment]
send me a link to the file

**Comment by pinkyellowed** [comment]
main.py: error: argument --email-api: invalid choice: 'devleropmail' (choose from '1secmail', '10minutemail', 'guerrillamail', 'developermail', 'mailticking')
Error: Process completed with exit code 255.
this is what i get in the test update ( i cant login to the eset portal either) 
https://github.com/pinkyellowed/ESET-KeyGen/commit/0844c1adce8c3efde859ab83d010c2ff985b9076
line 22

**Comment by Gingermuffinman** [comment]
@pinkyellowed I think the problem regards typos is you`ve forked @rzc0d3r project and incorrectly spell it in a commit.

**Comment by rzc0d3r** [comment]
> main.py: error: argument --email-api: invalid choice: 'devleropmail' (choose from '1secmail', '10minutemail', 'guerrillamail', 'developermail', 'mailticking') Error: Process completed with exit code 255. this is what i get in the test update ( i cant login to the eset portal either) [pinkyellowed@0844c1a](https://github.com/pinkyellowed/ESET-KeyGen/commit/0844c1adce8c3efde859ab83d010c2ff985b9076) line 22

Delete you fork, and create new fork again!

**Comment by pinkyellowed** [comment]
wtf thats weird, the test updated worked post edit for 2 days until yesterday, cant i edit the fork ?
