### ISSUE TITLE
Hangs on 5th step

### ISSUE THREAD

**Issue by ZilvinasLasauskas** [rzc0d3r/ESET-KeyGen#226]
Hangs on step:
[  INFO  ] [developermail] ESET-HOME-Token interception...

**Comment by rzc0d3r** [comment]
Use another Email API!

**Comment by ZilvinasLasauskas** [comment]
Hi

The page 

https://github.com/rzc0d3r/ESET-KeyGen

is not valid anymore?

Is there some other place for eset key gen project?

 

Zilvinas
