### ISSUE TITLE
error in latest release

### ISSUE THREAD

**Issue by karpiyon** [rzc0d3r/ESET-KeyGen#239]
Thanks for this method.
I get the following error when running ESET-KeyGen_v1.5.0.2_win64.exe:

[ FAILED ] Traceback (most recent call last):
  File "modules\EsetTools.py", line 102, in sendRequestForKey
  File "selenium\webdriver\remote\webdriver.py", line 414, in execute_script
  File "selenium\webdriver\remote\webdriver.py", line 354, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 229, in check_response
selenium.common.exceptions.JavascriptException: Message: javascript error: Cannot read properties of undefined (reading 'click')

**Comment by rzc0d3r** [comment]
**Always use the latest version of the project!!!**
Also don't ignore the warning that a new version is available, use the ```--update``` argument to download the latest version without going to the browser!

**Comment by ucuperror** [comment]
> **Always use the latest version of the project!!!** Also don't ignore the warning that a new version is available, use the `--update` argument to download the latest version without going to the browser!

![Screenshot 2024-11-22 201125](https://github.com/user-attachments/assets/fcedf68f-386a-4d74-9837-d501fe27baca)

Update already but still error like this. when generate key
