### ISSUE TITLE
Update authorization failed

### ISSUE THREAD

**Issue by ZilvinasLasauskas** [rzc0d3r/ESET-KeyGen#242]
eset blocks the generated license keys in one day after entering

**Comment by Gingermuffinman** [comment]
Generated trial keys myself and they all work fine, don't see why a blocker would be imposed.

**Comment by ZilvinasLasauskas** [comment]
> Generated trial keys myself and they all work fine, don't see why a blocker would be imposed, its possible that theirs a delay in the Eset server module registering the key/updates but after 30 minutes or restart of device it should be fine.

Yes, generated keys are accepted, but run the "update" in eset UI the next day and you will see "Update authorization failed" because of blocked/invalid key.

**Comment by Gingermuffinman** [comment]
> > Generated trial keys myself and they all work fine, don't see why a blocker would be imposed, its possible that theirs a delay in the Eset server module registering the key/updates but after 30 minutes or restart of device it should be fine.
> 
> Yes, generated keys are accepted, but run the "update" in eset UI the next day and you will see "Update authorization failed" because of blocked/invalid key.

Had no problems here at all

**Comment by ZilvinasLasauskas** [comment]
Again, every new key generated is accepted and if you doing update the same day, all good. But the next day the update does not work :-(
![Capture](https://github.com/user-attachments/assets/5850b013-7fc1-43f3-92c6-fbb65b4ab830)

**Comment by AdityaGarg8** [comment]
This happens when you share a key with someone. Make sure the generated key is exclusively with you.
