### ISSUE TITLE
No key or account generate

### ISSUE THREAD

**Issue by Piradoxlanieve** [rzc0d3r/ESET-KeyGen#245]
Hi!

It has always worked for me with Firefox or Chrome but now I get this error either with --key or account I have the latest version.

Sorry my english
`  Project Version: v1.5.2.4
                                                Project Devs: rzc0d3r, AdityaGarg8, k0re,
                                                              Fasjeit, alejanpa17, Ischunddu,
                                                              soladify, AngryBonk, Xoncia,
                                                              Anteneh13

-- Updater --

[   OK   ] Project up to date!!!

-- WebDriver Auto-Installer --

[  INFO  ] Mozilla Firefox version: 127.0
[  INFO  ] Mozilla Firefox webdriver version: 0.35.0
[   OK   ] The webdriver has already been updated to the latest version!

-- Browsers Initializer --

[  INFO  ] Initializing Mozilla Firefox for Windows

-- KeyGen --

[  INFO  ] [developermail] Mail registration...
[   OK   ] Mail registration completed successfully!

[  INFO  ] [EMAIL] Register page loading...
[   OK   ] [EMAIL] Register page is loaded!

[  INFO  ] Bypassing cookies...
[   OK   ] Cookies successfully bypassed!

[  INFO  ] [PASSWD] Register page loading...
[   OK   ] [PASSWD] Register page is loaded!

[  INFO  ] [developermail] ESET-HOME-Token interception...
[   OK   ] ESET-HOME-Token: 7509d36d-846e-4ab0-9e65-85c63ee21318

[  INFO  ] Account confirmation is in progress...
[ FAILED ] Traceback (most recent call last):
  File "main.py", line 329, in main
  File "modules\EsetTools.py", line 74, in confirmAccount
  File "modules\SharedTools.py", line 115, in untilConditionExecute
RuntimeError: untilConditionExecute: the code did not return the desired value! TRY VPN!`

**Comment by Gingermuffinman** [comment]
Maybe you should try a different --email -api

**Comment by Piradoxlanieve** [comment]
just generated a key for me right now

**Comment by rzc0d3r** [comment]
The site gives some bugs, try it until it works.

**Comment by Piradoxlanieve** [comment]
Thanks
