### ISSUE TITLE
Make the software installable 

### ISSUE THREAD

**Issue by AdityaGarg8** [rzc0d3r/ESET-KeyGen#249]
I was wondering if there could be a way to make this software installable. Then we could just run a command, say esetkeygen in command prompt and the software opens!

**Comment by AdityaGarg8** [comment]
And the updater could update the software as well

**Comment by AdityaGarg8** [comment]
Btw developermail seems to be broken:

```
ESET KeyGen v1.5.2.7 by rzc0d3r

-- Browsers Initializer --

[  INFO  ] Initializing Google Chrome for Linux

-- KeyGen --

[  INFO  ] [developermail] Mail registration...
[ FAILED ] Mail registration was not completed, try using a different Email API!
```

**Comment by AdityaGarg8** [comment]
I see we can add software to `%localappdata%\Microsoft\WindowsApps` and rename it as `esetkeygen`

Now the updater has to somehow install it there

**Comment by AdityaGarg8** [comment]
We probably could make the updater check for `%localappdata%\Microsoft\WindowsApps\esetkeygen`, and if it exists, make it update that.

**Comment by AdityaGarg8** [comment]
Ok so this is the plan I have in mind:

1. Add a --install argument that puts the binary as `%localappdata%\Microsoft\WindowsApps\esetkeygen`
2. The --update when run, will first check presence of `%localappdata%\Microsoft\WindowsApps\esetkeygen`. If present, it will update the binary there, else will follow the older way.



On macOS , the path becomes `/usr/local/bin/esetkeygen`. You will need root access on macOS for this, also the updater should make the new binary executable (chmod a+x)

**Comment by AdityaGarg8** [comment]
I'm not very good at python, so will need your help

**Comment by rzc0d3r** [comment]
> Итак, вот какой план у меня в голове:
> 
> 1. Добавьте аргумент --install, который помещает двоичный файл как`%localappdata%\Microsoft\WindowsApps\esetkeygen`
> 2. При запуске --update сначала проверит наличие `%localappdata%\Microsoft\WindowsApps\esetkeygen`. Если он присутствует, он обновит двоичный файл там, в противном случае будет следовать старому способу.
> 
> На macOS путь становится `/usr/local/bin/esetkeygen`. Для этого вам понадобится root-доступ на macOS, также программа обновления должна сделать новый исполняемый файл (chmod a+x)

During the upgrade, a copy of the executable will be created and control will be transferred to it, since you cannot overwrite files while the main executable is running.

**Comment by rzc0d3r** [comment]
This is necessary in case the .exe from the installation folder is launched

**Comment by AdityaGarg8** [comment]
> > Итак, вот какой план у меня в голове:
> > 
> > 1. Добавьте аргумент --install, который помещает двоичный файл как`%localappdata%\Microsoft\WindowsApps\esetkeygen`
> > 2. При запуске --update сначала проверит наличие `%localappdata%\Microsoft\WindowsApps\esetkeygen`. Если он присутствует, он обновит двоичный файл там, в противном случае будет следовать старому способу.
> > 
> > На macOS путь становится `/usr/local/bin/esetkeygen`. Для этого вам понадобится root-доступ на macOS, также программа обновления должна сделать новый исполняемый файл (chmod a+x)
> 
> During the upgrade, a copy of the executable will be created and control will be transferred to it, since you cannot overwrite files while the main executable is running.

I guess you can invoke a power shell command to replace the old exe with new one. Anyways, I just had an idea and thought the software would be very convenient like this.

**Comment by AdityaGarg8** [comment]
We can do this as well.

Create a separate exe named updater, it can simply update the software.

**Comment by AdityaGarg8** [comment]
Also, the need for checks whether esetkeygen.exe is there or not gets eliminated

**Comment by AdityaGarg8** [comment]
So whenever software checks for update, it can instruct the user to use the updater app if they have it installed.

**Comment by AdityaGarg8** [comment]
And if user uses the --install argument, the keygen and updater shall be simultaneously installed

**Comment by rzc0d3r** [comment]
Then the updater will be a separate file and will weigh quite a lot

**Comment by rzc0d3r** [comment]
And then it is better to release releases in the form of Zip files, which will contain both the keygen and the updater itself

**Comment by rzc0d3r** [comment]
And who will update the updater)

**Comment by AdityaGarg8** [comment]
Well seems more complex than I thought 😅

**Comment by AdityaGarg8** [comment]
I'll close this

**Comment by rzc0d3r** [comment]
It can be done as I wrote earlier, just via control transfer

**Comment by rzc0d3r** [comment]
We'll hold off on that for now.

**Comment by AdityaGarg8** [comment]
> We'll hold off on that for now.

I thought it was impossible. You can reopen this if you wanna work on this I guess.

**Comment by rzc0d3r** [comment]
> > We'll hold off on that for now.
> 
> I thought it was impossible. You can reopen this if you wanna work on this I guess.

![image](https://github.com/user-attachments/assets/4330fda7-aa00-4460-8600-3899e4f5386c)

**Comment by rzc0d3r** [comment]
The beginning has been made

**Comment by rzc0d3r** [comment]
![image](https://github.com/user-attachments/assets/f93b3aa9-996d-41be-9b54-3055b79fba29)

---

![image](https://github.com/user-attachments/assets/7673e26b-924c-4879-84c2-9f3efc49a23f)

**Comment by AdityaGarg8** [comment]
Nice!

**Comment by AdityaGarg8** [comment]
```batch
@echo off

:: Fetch the latest release page
curl -sL https://github.com/rzc0d3r/ESET-KeyGen/releases/latest > temp.html

:: Extract the line containing the release title
for /f "tokens=*" %%i in ('findstr /c:"<title>Release" temp.html') do set "var1=%%i"

:: Extract the version number from the line
for /f "tokens=2 delims= " %%i in ("%var1%") do set "version=%%i"

:: Display the version number
echo Latest Release Version: %version%

:: Clean up the temporary file
del temp.html
```

This batch script can fetch the latest version of the software from your repo. We can use this as an updater by using curl to download the software.

**Comment by AdityaGarg8** [comment]
I've finally made a small but useful batch script that downloads the latest version:

```batch
@echo off

echo Press Enter to start
pause >nul

:: Check if system is 32bit or 64bit

if "%PROCESSOR_ARCHITECTURE%" == "AMD64" (
    set "arch=64"
) else if "%PROCESSOR_ARCHITECTURE%" == "x86" (
    set "arch=32"
)

:: Fetch the latest release page
curl -sL https://github.com/rzc0d3r/ESET-KeyGen/releases/latest > %temp%\eset.html

:: Extract the line containing the release title
for /f "tokens=*" %%i in ('findstr /c:"<title>Release" %temp%\eset.html') do set "var1=%%i"

:: Extract the version number from the line
for /f "tokens=2 delims= " %%i in ("%var1%") do set "version=%%i"

:: Display the version number
echo.
echo Latest Release Version: %version%
echo.
echo Updating ESET Keygen
echo.
curl -#L https://github.com/rzc0d3r/ESET-KeyGen/releases/download/%version%/ESET-KeyGen_%version%_win%arch%.exe > %localappdata%\Microsoft\WindowsApps\esetkeygen.exe
echo.
echo Press enter to exit...

:: Clean up the temporary file
del %temp%\eset.html
```

Save it with `.bat` as file extension and see it work!

Also, I guess something like this should be able to run the batch script from the keygen:

```python
import subprocess
import os
import sys

# Path to your batch script
batch_script = r"%localappdata%\Microsoft\WindowsApps\updateeset.bat"

# Start the batch script
subprocess.Popen(batch_script, shell=True, env=os.environ)

# Terminate the Python program
sys.exit()
```

It immediately terminates the software after batch script is executed.

**Comment by AdityaGarg8** [comment]
As long as you don't change the versioning system and name of the binaries, the batch script will work just fine. Although, in other cases changes won't be difficult as well.

**Comment by AdityaGarg8** [comment]
This updater can also be used as an installer as well since it just downloads and puts the software at its place.

**Comment by rzc0d3r** [comment]
We will need to add a config file containing all the startup arguments so that a person can customize it to their liking, rather than having to change the settings each time

**Comment by rzc0d3r** [comment]
For this file you need to locate it in the file system, on windows this is easy to do as my install algorithm moves everything to a folder and everything can be stored there. But on macOS it's more complicated, I need to select a folder for it

**Comment by AdityaGarg8** [comment]
> We will need to add a config file containing all the startup arguments so that a person can customize it to their liking, rather than having to change the settings each time

Tbh I don't really find adding a config file useful. After all, most people just need to generate keys. Although, you can add a "Do you want to update" prompt instead of asking the user to run again using --update

**Comment by AdityaGarg8** [comment]
> For this file you need to locate it in the file system, on windows this is easy to do as my install algorithm moves everything to a folder and everything can be stored there. But on macOS it's more complicated, I need to select a folder for it

You can make a `$HOME/.esetconfig` file as a config.

**Comment by AdityaGarg8** [comment]
But again, I don't think a config is actually needed, since it's something like, "oh my antivirus expired, let me quickly get a keg for the next 30 days"

**Comment by rzc0d3r** [comment]
> But again, I don't think a config is actually needed, since it's something like, "oh my antivirus expired, let me quickly get a key for the next 30 days" and forget this even existed.

People wrote to me in chat that they were tired of changing the settings every time :)

**Comment by rzc0d3r** [comment]
I've tried to make everything convenient by creating a menu.

**Comment by AdityaGarg8** [comment]
> > But again, I don't think a config is actually needed, since it's something like, "oh my antivirus expired, let me quickly get a key for the next 30 days" and forget this even existed.
> 
> People wrote to me in chat that they were tired of changing the settings every time :)

Oh, I see. Such configs I guess will make sense in installation cases then.

**Comment by AdityaGarg8** [comment]
> For this file you need to locate it in the file system, on windows this is easy to do as my install algorithm moves everything to a folder and everything can be stored there. But on macOS it's more complicated, I need to select a folder for it

For configs, you can also use `$HOME/Library/Application Support/ESET Keygen`

**Comment by AdityaGarg8** [comment]
> > For this file you need to locate it in the file system, on windows this is easy to do as my install algorithm moves everything to a folder and everything can be stored there. But on macOS it's more complicated, I need to select a folder for it
> 
> For configs, you can also use `$HOME/Library/Application Support/ESET Keygen`

replace ESET Keygen with the name of the folder you want.

**Comment by AdityaGarg8** [comment]
If you are planning to use the batch script I made for updates, I can add the option for downloading the config as well to them. Also, I haven’t tested the hack of terminating the program after invoking the updater yet since I don't know how to integrate this into your code.

**Comment by rzc0d3r** [comment]
Why don't we go to Telegram? I don't feel comfortable writing a lot of text here..

**Comment by AdityaGarg8** [comment]
Ok 😅

**Comment by AdityaGarg8** [comment]
I messaged you in your personal telegram as mentioned in the readme
