### ISSUE TITLE
RuntimeError: Request sending error on ArcoLinux (Arch)

### ISSUE THREAD

**Issue by linasas** [rzc0d3r/ESET-KeyGen#251]
Hi, using KeyGen quite a while without problems on my terminal in Arcolinux but few months ago the strange error appeared. I have python-selenium, python-requests and colorama as per reqs, tried reinstalling but no hope... and sorry, still in the learning process... Thx for your time. 
![image](https://github.com/user-attachments/assets/1de7c59b-d168-4310-ac14-4d80a0235f9d)

**Comment by rzc0d3r** [comment]
Try
```
pip uninstall selenium
pip install selenium
```

**Comment by linasas** [comment]
yeah, tried that but could not do it through pip, get error: externally-managed-environment and an offer to use usual arch way to install packages which does not include the missing file... Anyway solved the problem by downloading getattribute.js and isdisplayed.js files from source and using VPN the problem was solved ;)

**Comment by rzc0d3r** [comment]
That's the whole problem with linux, very different system configurations and it's impossible to just solve everything for everyone.
You should have run ```python -m pip install %module_name%``` to install modules or ```python-pip install %module_name%```
