### ISSUE TITLE
Assembly executable?

### ISSUE THREAD

**Issue by e-t-l** [rzc0d3r/ESET-KeyGen#26]
Is this still available to download as an exe?

**Comment by rzc0d3r** [comment]
No. I removed the ability to download assemblies because it is not convenient for me.  Perhaps I will add assemblies only for significant releases.

**Comment by rzc0d3r** [comment]
https://github.com/rzc0d3r/ESET-KeyGen/releases/download/v1.0.9.0-191023-2057/ESET-KeyGen_v1.0.9.0-191023-2057_win32.exe

**Comment by e-t-l** [comment]
"Chrome is not detected on your device..."

The last executable (that I downloaded, at least), which was `ESET-KeyGen_v1.0.6.1_win32.exe`, installed Chrome as part of the process. Does it not do that anymore?

**Comment by rzc0d3r** [comment]
It installs the driver automatically. Better send the location of the installed chrome. I will add this path to the program and then everything will work
