### ISSUE TITLE
Error chromedrive

### ISSUE THREAD

**Issue by leandrocombr** [rzc0d3r/ESET-KeyGen#3]
@Debian:~/ESET-KeyGen$ python3.9 ESET\ KeyGen.py
Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x55fb84bc84e3 <unknown>
#1 0x55fb848f7c76 <unknown>
#2 0x55fb84920d78 <unknown>
#3 0x55fb8491d029 <unknown>
#4 0x55fb8495bccc <unknown>
#5 0x55fb8495b47f <unknown>
#6 0x55fb84952de3 <unknown>
#7 0x55fb849282dd <unknown>
#8 0x55fb8492934e <unknown>
#9 0x55fb84b883e4 <unknown>
#10 0x55fb84b8c3d7 <unknown>
#11 0x55fb84b96b20 <unknown>
#12 0x55fb84b8d023 <unknown>
#13 0x55fb84b5b1aa <unknown>
#14 0x55fb84bb16b8 <unknown>
#15 0x55fb84bb1847 <unknown>
#16 0x55fb84bc1243 <unknown>
#17 0x7ff2a1e2bea7 start_thread

Press Enter...

@Debian:~/ESET-KeyGen$ /usr/bin/google-chrome
Starting ChromeDriver 114.0.5735.90 (386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052}) on port 9515
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.

How to solve?

**Comment by rzc0d3r** [comment]
I take it you have Linux?

**Comment by rzc0d3r** [comment]
I will try to port the program to linux.

**Comment by rzc0d3r** [comment]
try version 1.0.5 (I successfully tested on debian12)

**Comment by leandrocombr** [comment]
I'm using Debian 11

What would this version 1.0.5 be?

**Comment by rzc0d3r** [comment]
Just Redownload repository

**Comment by leandrocombr** [comment]
@Debian:~/ESET-KeyGen$ python3.9 ESET\ KeyGen.py
[*] Initializing driver for Linux
Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x55b3e098d4e3 <unknown>
#1 0x55b3e06bcc76 <unknown>
#2 0x55b3e06e5d78 <unknown>
#3 0x55b3e06e2029 <unknown>
#4 0x55b3e0720ccc <unknown>
#5 0x55b3e072047f <unknown>
#6 0x55b3e0717de3 <unknown>
#7 0x55b3e06ed2dd <unknown>
#8 0x55b3e06ee34e <unknown>
#9 0x55b3e094d3e4 <unknown>
#10 0x55b3e09513d7 <unknown>
#11 0x55b3e095bb20 <unknown>
#12 0x55b3e0952023 <unknown>
#13 0x55b3e09201aa <unknown>
#14 0x55b3e09766b8 <unknown>
#15 0x55b3e0976847 <unknown>
#16 0x55b3e0986243 <unknown>
#17 0x7f295b86eea7 start_thread

Press Enter...

Do I need to do another procedure?

```
Debian:~/ESET-KeyGen$ ls -lha
total 22M
drwxr-xr-x  4 leandro leandro 4,0K jul 23 12:39  .
drwxr-xr-x 14 leandro leandro 4,0K jul 23 12:38  ..
-rwxr-xr-x  1 leandro leandro  15M mai 26 21:10  chromedriver
-rw-r--r--  1 leandro leandro 7,1M mai 31 05:57  chromedriver_linux64.zip
-rw-r--r--  1 leandro leandro  11K jul 23 12:38 'ESET KeyGen.py'
drwxr-xr-x  8 leandro leandro 4,0K jul 23 12:38  .git
drwxr-xr-x  2 leandro leandro 4,0K jul 23 12:38  img
-rw-r--r--  1 leandro leandro 319K mai 26 21:10  LICENSE.chromedriver
-rw-r--r--  1 leandro leandro 1,6K jul 23 12:38  README.md
```

**Comment by rzc0d3r** [comment]
And how did you install chrome? With .reb package?

**Comment by rzc0d3r** [comment]
You should also move chromedriver to /usr/bin

**Comment by leandrocombr** [comment]
```
leandro@Debian:~/ESET-KeyGen$ /usr/bin/chromedriver
Starting ChromeDriver 114.0.5735.90 (386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052}) on port 9515
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
[1690127470,830][SEVERE]: bind() failed: Não foi possível acessar o endereço requisitado (99)
ChromeDriver was started successfully.
^Z
[1]+  Parado                  /usr/bin/chromedriver
leandro@Debian:~/ESET-KeyGen$ /usr/bin/google-chrome
Starting ChromeDriver 114.0.5735.90 (386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052}) on port 9515
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
[1690127474,205][SEVERE]: bind() failed: Não foi possível acessar o endereço requisitado (99)
[1690127474,205][SEVERE]: bind() failed: Endereço já em uso (98)
IPv4 port not available. Exiting...

```

**Comment by rzc0d3r** [comment]
Try running without superuser rights

**Comment by rzc0d3r** [comment]
I had google-chrome-stable

**Comment by leandrocombr** [comment]
Install

wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
apt install ./google-chrome-stable_current_amd64.deb

**Comment by rzc0d3r** [comment]
Version 115?

**Comment by rzc0d3r** [comment]
https://googlechromelabs.github.io/chrome-for-testing/#stable

**Comment by leandrocombr** [comment]
Resolved

sudo apt-get remove google-chrome-stable
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
apt install ./google-chrome-stable_current_amd64.deb
rm  -rf /usr/bin/google-chrome
ln -s /usr/bin/google-chrome-stable /usr/bin/google-chrome

@Debian:~/ESET-KeyGen$ python3.9 ESET\ KeyGen.py
[*] Initializing driver for Linux

[*] [EMAIL] Register page loading...
[+] [EMAIL] Register page is loaded!

[*] [PASSWD] Register page loading...
[+] [PASSWD] Register page is loaded!

[+] ESET Token: 1dd93f2e-ef40-423e-af6d-a56182edce91

[*] ConfirmToken page loading...
[+] ConfirmToken page is loaded!

[*] License page loading...
[+] License page is loaded!

[*] Request sending...
[*] Waiting for permission to request...
[+] Access to the request was open!

[*] Platforms loading...
[+] Windows platform is selected!

[*] Request license page loading...
[*] Sending a request for a license...
[*] Waiting for confirmation of request...
[+] Request was approved!

[*] License uploads...
[+] License is uploaded!

[*] Getting information from the license...
[+] Information successfully received!

License Name: ESET Smart Security Premium
License Out Date: 08/22/2023
License Key: ****-****-****-***

Press Enter...

Thanks a lot for the help!

**Comment by leandrocombr** [comment]
All keys are for 30 days correct?

**Comment by rzc0d3r** [comment]
Yea

**Comment by leandrocombr** [comment]
Do you have telegram?

**Comment by rzc0d3r** [comment]
Yes. The username is the same as on gitHub
