### ISSUE TITLE
"This website dont work"

### ISSUE THREAD

**Issue by VoidDave** [rzc0d3r/ESET-KeyGen#30]
Eset propably hanged something (again) and website is "not working" it happens while registering (this in URL at the time https://login.eset.com/Register/FinalStep) 
crash logs (ignore pycord stuff I integrated your code long time ago and updating it to newest versions, no its not mine mistake it worked 4 days ago and I didn't ): 

Ignoring exception in on_application_command_error
Traceback (most recent call last):
  File "C:\Users\polsk\AppData\Roaming\Python\Python310\site-packages\discord\commands\core.py", line 124, in wrapped
    ret = await coro(arg)
  File "C:\Users\polsk\AppData\Roaming\Python\Python310\site-packages\discord\commands\core.py", line 978, in _invoke
    await self.callback(self.cog, ctx, **kwargs)
  File "E:\dc_bot\eset_cog.py", line 217, in eset
    if not EsetReg.createAccount():
  File "E:\dc_bot\eset_cog.py", line 116, in createAccount
    self.driver.execute_script(f"{GET_EBID}('Email').value='{self.email_obj.get_full_login()}'\ndocument.forms[0].submit()")
  File "C:\Users\polsk\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 404, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
  File "C:\Users\polsk\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 344, in execute
    self.error_handler.check_response(response)
  File "C:\Users\polsk\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: result.webdriverValue.value list is missing or empty in Runtime.callFunctionOn response
  (Session info: chrome=119.0.6045.124)
Stacktrace:
	GetHandleVerifier [0x00007FF7D0C18EF2+54786]
	(No symbol) [0x00007FF7D0B85612]
	(No symbol) [0x00007FF7D0A3A64B]
	(No symbol) [0x00007FF7D0A3EEC1]
	(No symbol) [0x00007FF7D0A414AA]
	(No symbol) [0x00007FF7D0AB5394]
	(No symbol) [0x00007FF7D0A9BE6A]
	(No symbol) [0x00007FF7D0AB4D02]
	(No symbol) [0x00007FF7D0A9BC43]
	(No symbol) [0x00007FF7D0A70941]
	(No symbol) [0x00007FF7D0A71B84]
	GetHandleVerifier [0x00007FF7D0F67F52+3524194]
	GetHandleVerifier [0x00007FF7D0FBD800+3874576]
	GetHandleVerifier [0x00007FF7D0FB5D7F+3843215]
	GetHandleVerifier [0x00007FF7D0CB5086+694166]
	(No symbol) [0x00007FF7D0B90A88]
	(No symbol) [0x00007FF7D0B8CA94]
	(No symbol) [0x00007FF7D0B8CBC2]
	(No symbol) [0x00007FF7D0B7CC83]
	BaseThreadInitThunk [0x00007FFF79F7257D+29]
	RtlUserThreadStart [0x00007FFF7A66AA58+40]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\polsk\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 378, in _run_event
    await coro(*args, **kwargs)
  File "E:\dc_bot\main.py", line 44, in on_application_command_error
    raise error
  File "C:\Users\polsk\AppData\Roaming\Python\Python310\site-packages\discord\bot.py", line 1114, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "C:\Users\polsk\AppData\Roaming\Python\Python310\site-packages\discord\commands\core.py", line 375, in invoke
    await injected(ctx)
  File "C:\Users\polsk\AppData\Roaming\Python\Python310\site-packages\discord\commands\core.py", line 132, in wrapped
    raise ApplicationCommandInvokeError(exc) from exc
discord.errors.ApplicationCommandInvokeError: Application Command raised an exception: WebDriverException: Message: unknown error: result.webdriverValue.value list is missing or empty in Runtime.callFunctionOn response
  (Session info: chrome=119.0.6045.124)
Stacktrace:
	GetHandleVerifier [0x00007FF7D0C18EF2+54786]
	(No symbol) [0x00007FF7D0B85612]
	(No symbol) [0x00007FF7D0A3A64B]
	(No symbol) [0x00007FF7D0A3EEC1]
	(No symbol) [0x00007FF7D0A414AA]
	(No symbol) [0x00007FF7D0AB5394]
	(No symbol) [0x00007FF7D0A9BE6A]
	(No symbol) [0x00007FF7D0AB4D02]
	(No symbol) [0x00007FF7D0A9BC43]
	(No symbol) [0x00007FF7D0A70941]
	(No symbol) [0x00007FF7D0A71B84]
	GetHandleVerifier [0x00007FF7D0F67F52+3524194]
	GetHandleVerifier [0x00007FF7D0FBD800+3874576]
	GetHandleVerifier [0x00007FF7D0FB5D7F+3843215]
	GetHandleVerifier [0x00007FF7D0CB5086+694166]
	(No symbol) [0x00007FF7D0B90A88]
	(No symbol) [0x00007FF7D0B8CA94]
	(No symbol) [0x00007FF7D0B8CBC2]
	(No symbol) [0x00007FF7D0B7CC83]
	BaseThreadInitThunk [0x00007FFF79F7257D+29]
	RtlUserThreadStart [0x00007FFF7A66AA58+40]

i hope my logs will help you with fixing it : ) good work man keep it up

**Comment by rzc0d3r** [comment]
I'll see what happened to the project soon. Thank you for the information.

**Comment by rzc0d3r** [comment]
I'm getting this.

![image_2023-11-13_20-23-51](https://github.com/rzc0d3r/ESET-KeyGen/assets/106631540/d52cf57f-5194-4595-9757-af19d9845225)

**Comment by VoidDave** [comment]
Oh i just found you made update with splits everything into separate files. Is there any significant changes from last version that included everything in one file ? (Im taking about eset functionality)

**Comment by rzc0d3r** [comment]
Nothing has changed in the algorithms. But now it is possible to generate both keys and accounts. You just need to run main.py with the key (command line argument) --account

**Comment by rzc0d3r** [comment]
In the documentation, I've covered everything. I updated it too

**Comment by rzc0d3r** [comment]
### Here's a little help with the Discord bot integration.
main.py
```python
if __name__ == '__main__':
    try:
        chromedriver_path = chrome_driver_installer_menu()
        only_account = False
        if len(sys.argv) > 1 and '--account' in sys.argv:
            logger.console_log('\n-- ESET Account Generator {0} --\n'.format(eset_register.VERSION))
            only_account = True
        else:
            logger.console_log('\n-- ESET KeyGen {0} --\n'.format(eset_keygen.VERSION))
        email_obj = sec_email_api.SecEmail()
        logger.console_log('Mail registration...', logger.INFO)
        email_obj.register()
        logger.console_log('Mail registration completed successfully!\n', logger.OK)
        eset_password = shared_tools.createPassword(6)
        EsetReg = eset_register.EsetRegister(email_obj, eset_password)
        EsetReg.initDriver(chromedriver_path)
        EsetReg.createAccount()
        EsetReg.confirmAccount()
        driver = EsetReg.returnDriver()
        output_line = f'\nEmail: {email_obj.get_full_login()}\nPassword: {eset_password}\n'
        output_filename = 'ESET ACCOUNTS.txt'
        if not only_account:
            EsetKeyG = eset_keygen.EsetKeygen(email_obj, driver)
            EsetKeyG.sendRequestForKey()
            license_name, license_out_date, license_key = EsetKeyG.getLicenseData()
            output_line = f'\nLicense Name: {license_name}\nLicense Out Date: {license_out_date}\nLicense Key: {license_key}\n'
            output_filename = 'ESET KEYS.txt'
        logger.console_log(output_line)
        date = datetime.datetime.now()
        f = open(f"{str(date.day)}.{str(date.month)}.{str(date.year)} - "+output_filename, 'a')
        f.write(output_line)
        f.close()
        driver.quit()
    except Exception as E:
        logger.console_log(str(E), logger.ERROR)
    input('Press Enter...')
```

```python
if len(sys.argv) > 1 and '--account' in sys.argv:
```
Here you can change the condition under which the account generation script will be executed

**Comment by VoidDave** [comment]
Thanks i will reopen this issue if the issue still will persist.
