### ISSUE TITLE
Cannot read properties of undefined (reading 'click')

### ISSUE THREAD

**Issue by veralara** [rzc0d3r/ESET-KeyGen#31]
Hello... Help 
-- Chrome Driver Auto-Installer v1.1.3 (151023-2234) by rzc0d3r --

[  INFO  ] Chrome version: 119.0.6045.159
[  INFO  ] Chrome driver version: 119.0.6045.105

-- ESET KeyGen v1.0.9 (191023-2057) by rzc0d3r --

[  INFO  ] Mail registration...
[   OK   ] Mail registration completed successfully!

[  INFO  ] Initializing driver for Windows

[  INFO  ] [EMAIL] Register page loading...
[   OK   ] [EMAIL] Register page is loaded!

[  INFO  ] [PASSWD] Register page loading...
[   OK   ] [PASSWD] Register page is loaded!

[   OK   ] ESET Token: a7fc0446-d3cb-41f0-940f-b98ace8f3f13

[  INFO  ] Account confirmation is in progress...
[   OK   ] Account successfully confirmed!

[  INFO  ] License page loading...
[   OK   ] License page is loaded!

[  INFO  ] Request sending...
[ FAILED ] Message: javascript error: Cannot read properties of undefined (reading 'click')
  (Session info: chrome=119.0.6045.159)
Stacktrace:
        GetHandleVerifier [0x00007FF6DF5182B2+55298]
        (No symbol) [0x00007FF6DF485E02]
        (No symbol) [0x00007FF6DF3405AB]
        (No symbol) [0x00007FF6DF34509C]
        (No symbol) [0x00007FF6DF34732A]
        (No symbol) [0x00007FF6DF3BB12B]
        (No symbol) [0x00007FF6DF3A20AA]
        (No symbol) [0x00007FF6DF3BAAA4]
        (No symbol) [0x00007FF6DF3A1E83]
        (No symbol) [0x00007FF6DF37670A]
        (No symbol) [0x00007FF6DF377964]
        GetHandleVerifier [0x00007FF6DF890AAB+3694587]
        GetHandleVerifier [0x00007FF6DF8E728E+4048862]
        GetHandleVerifier [0x00007FF6DF8DF173+4015811]
        GetHandleVerifier [0x00007FF6DF5B47D6+695590]
        (No symbol) [0x00007FF6DF490CE8]
        (No symbol) [0x00007FF6DF48CF34]
        (No symbol) [0x00007FF6DF48D062]
        (No symbol) [0x00007FF6DF47D3A3]
        BaseThreadInitThunk [0x00007FFB7FD87344+20]
        RtlUserThreadStart [0x00007FFB804626B1+33]

**Comment by rzc0d3r** [comment]
The update is in development!

I am aware of changes to the site!

**Comment by k0re** [comment]
I've done a fix for myself, but i cant push it. So here's the fix:

modules\shares_tools.py

Add after Line 7 the following:

`GET_EBTN = 'document.getElementsByTagName'`


modules\eset_keygen.py

Change line 21 from :
`        self.driver.execute_script(f"{shared_tools.GET_EBCN}('ion-cui-button ios button button-solid ion-activatable ion-focusable hydrated')[1].click()")`
to look like this:

`        self.driver.execute_script(f"{shared_tools.GET_EBTN}('button')[0].click()")`


Thats it :)

**Comment by rzc0d3r** [comment]
I'm sorry, but I just noticed it now.  I've already made up my mind.) Thank you for your support

**Comment by rzc0d3r** [comment]
[v1.0.9.1 (171123-1541)](https://github.com/rzc0d3r/ESET-KeyGen/releases/tag/v1.0.9.1-171123-1541)
