### ISSUE TITLE
Fix log level to avoid javascript errors showing up in the console

### ISSUE THREAD

**Issue by k0re** [rzc0d3r/ESET-KeyGen#32]
Add this to your modules\eset_register.py after Line 20:

`        driver_options.add_argument("--log-level=3")`

Afterwards it looks like:
`        driver_options.add_experimental_option('excludeSwitches', ['enable-logging'])`
`        driver_options.add_argument("--log-level=3")`

This avoids all javscript errors happening on the ESET Website (At the moment for example a cookiebar error).

**Comment by k0re** [comment]
i mean this error (highlighted in big font):

[  INFO  ] [EMAIL] Register page loading...
[   OK   ] [EMAIL] Register page is loaded!
**[1117/145704.357:INFO:CONSOLE(1140)] "[cookiebar] DIV element #cookiebar is not available!", source: webpack-internal:///2 (1140)**

[  INFO  ] [PASSWD] Register page loading...
[   OK   ] [PASSWD] Register page is loaded!

when you add the --log-level=3 option to the chromedriver, this error is not shown anymore.

**Comment by rzc0d3r** [comment]
I've never seen that before. So I didn't add log-level 3.

**Comment by rzc0d3r** [comment]
I give you permission to make a fork and add your code that I will accept it.

**Comment by rzc0d3r** [comment]
you'll be on the list of contributors

**Comment by k0re** [comment]
I've created a pull request for this.

**Comment by rzc0d3r** [comment]
> I've created a pull request for this.

[New v1.0.9.1 (171123-1640) release comes with your code.](https://github.com/rzc0d3r/ESET-KeyGen/releases/tag/v1.0.9.1-171123-1640)
