### ISSUE TITLE
chrome dependency

### ISSUE THREAD

**Issue by Uj947nXmRqV2nRaWshKtHzTvckUUpD** [rzc0d3r/ESET-KeyGen#38]
I don't use chrome and it shouldn't rely on a full chrome installation as already discussed in another issue. For me it's broken rn.  Btw there's also firefox version of driver https://github.com/mozilla/geckodriver as an alternative to google mofos

PS C:\Users\User\Downloads\ESET-KeyGen> py.exe .\main.py
-- Chrome Driver Auto-Installer v1.1.4 (171123-1640) by rzc0d3r --

[ FAILED ] Traceback (most recent call last):
  File "C:\Users\User\Downloads\ESET-KeyGen\main.py", line 69, in <module>
    chromedriver_path = chrome_driver_installer_menu()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Downloads\ESET-KeyGen\main.py", line 21, in chrome_driver_installer_menu
    raise RuntimeError('Chrome is not detected on your device!')
RuntimeError: Chrome is not detected on your device!

Press Enter...

**Comment by rzc0d3r** [comment]
Add support for Firefox?

**Comment by rzc0d3r** [comment]
TRY IT with ```--firefox``` argument [ESET-KeyGen-1.0.9.2-211123-1059 D.zip](https://github.com/rzc0d3r/ESET-KeyGen/files/13424081/ESET-KeyGen-1.0.9.2-211123-1059.D.zip)

**P.S: Please send logs to do if there are any problems!!!**

**Comment by rzc0d3r** [comment]
Yay. Thank you for the feedback!

**Comment by rzc0d3r** [comment]
[already released it](https://github.com/rzc0d3r/ESET-KeyGen/releases/tag/v1.0.9.2-211123-1059)

**Comment by rzc0d3r** [comment]
Chrome is easier to maintain and support. It executes faster and eats less osu
