### ISSUE TITLE
Termux

### ISSUE THREAD

**Issue by velethon** [rzc0d3r/ESET-KeyGen#39]
Does this work in termux?

**Comment by rzc0d3r** [comment]
No, since selenium does not support arm processors. But you can try to launch the project via GitHub CI. It will execute the code on its server and output the result to your console.

**Comment by VoidDave** [comment]
> No, since selenium does not support arm processors. But you can try to launch the project via GitHub CI. It will execute the code on its server and output the result to your console.

Can you pls share more info how to do it ? Im trying to do it from some time but I cant find anything useful for this
