### ISSUE TITLE
Вот такая ошибка 

### ISSUE THREAD

**Issue by borisorlov21** [rzc0d3r/ESET-KeyGen#41]
![sshot-001](https://github.com/rzc0d3r/ESET-KeyGen/assets/66428911/4a590b37-c943-408b-b8c0-b0a1083cac6f)

**Comment by rzc0d3r** [comment]
Крайне интересная ошибка. Что у вас было в окне браузера?

**Comment by borisorlov21** [comment]
![sshot-002](https://github.com/rzc0d3r/ESET-KeyGen/assets/66428911/858a145d-aa08-4667-b8cf-dfd0f3ee2cac)

**Comment by rzc0d3r** [comment]
> ![sshot-002](https://user-images.githubusercontent.com/66428911/284687086-858a145d-aa08-4667-b8cf-dfd0f3ee2cac.png)

Скрин с старой версии

**Comment by rzc0d3r** [comment]
Ну по вашему первому скрину видно что использовали последнюю версию

**Comment by borisorlov21** [comment]
![sshot-003](https://github.com/rzc0d3r/ESET-KeyGen/assets/66428911/1b48ebd1-c2c9-41af-8d42-f01589a50e86)

**Comment by borisorlov21** [comment]
Две недели назад работала у меня 
![sshot-004](https://github.com/rzc0d3r/ESET-KeyGen/assets/66428911/2d99b5f9-402e-4292-89ef-528ee971e24e)
![sshot-005](https://github.com/rzc0d3r/ESET-KeyGen/assets/66428911/997f9db6-2691-4b99-a9a8-fdb3c841b850)

**Comment by borisorlov21** [comment]
У меня так работает последняя ваша версия  мой вин Windows 11 Pro N for Workstations
![sshot-001](https://github.com/rzc0d3r/ESET-KeyGen/assets/66428911/1fd681c7-6869-49a9-9a1c-6f5e66b85bd0)

**Comment by rzc0d3r** [comment]
у вас истекает сессия. У вас медленный интернет?. Или программа зависает долго при каждом действии

**Comment by rzc0d3r** [comment]
мне интересно как у вас происходит процесс от А до Я

**Comment by rzc0d3r** [comment]
было бы неплохо записать видео.

**Comment by borisorlov21** [comment]
Uploading ScreenRecorder-20231121-192818.600.mp4…

**Comment by borisorlov21** [comment]
https://github.com/rzc0d3r/ESET-KeyGen/assets/66428911/21cad951-7bef-4d84-b560-ce4aadc8be0f

**Comment by rzc0d3r** [comment]
Ну опять же. Старый код. Используйте последний релиз

**Comment by borisorlov21** [comment]
https://github.com/rzc0d3r/ESET-KeyGen/assets/66428911/bba04d8a-6b50-45e1-8989-d8a01553bc39

**Comment by borisorlov21** [comment]
![sshot-001](https://github.com/rzc0d3r/ESET-KeyGen/assets/66428911/4e839a74-0fd6-4b62-ac0d-b7e994c41f53)

**Comment by rzc0d3r** [comment]
Очень интересно. Попробуйте отключить антивирус есет. И убрать защиту браузера в есете

**Comment by rzc0d3r** [comment]
Так как это не нормально, что при регистрации вас сразу выкидывает с ошибкой что сессия была закончена. Кто то не контролирует это

**Comment by borisorlov21** [comment]
![sshot-002](https://github.com/rzc0d3r/ESET-KeyGen/assets/66428911/9b1f1cf8-df21-4bc5-9b36-db65943b8077)

**Comment by borisorlov21** [comment]
Мой йпи блокирован отключил фаервол включил впн и тоже самое  как разблокировать айпи

**Comment by borisorlov21** [comment]
на ноутбуке с ви-фи все сработало с откл фаером и вкл впн результат положительный

**Comment by rzc0d3r** [comment]
> на ноутбуке с ви-фи все сработало с откл фаером и вкл впн результат положительный

Возможно Санкции. Так проект работает?

**Comment by borisorlov21** [comment]
установил на чистую вин 11проверил  все работает незнаю как на долго будет функционировать.  непонятно по какой причине случилась блокировка айпи
