### ISSUE TITLE
мак

### ISSUE THREAD

**Issue by borisorlov21** [rzc0d3r/ESET-KeyGen#42]
может есть способ как в мак ос сгенерить  номер

**Comment by rzc0d3r** [comment]
Должен быть. Но только у меня нет устройств на MacOS. Я не смогу сделать поддержку. Мне нужно отправлять вам тестовые версии и таким образом разрабатывать версию под MacOS.

**Comment by borisorlov21** [comment]
ясно

**Comment by borisorlov21** [comment]
а библиотека пайтона у операционных систем у каждой своя как я понял и от виндоус неподходит буду пользоваться на виндоус спасибо 
👍🏻

**Comment by rzc0d3r** [comment]
> а библиотека пайтона у операционных систем у каждой своя как я понял и от виндоус неподходит буду пользоваться на виндоус спасибо 
> 👍🏻

Я почитал и библиотека доступна на MacOS. И он поддерживает браузер Safari

**Comment by borisorlov21** [comment]
где скачать библиотеку для мак

**Comment by borisorlov21** [comment]
у меня хакинтош

**Comment by rzc0d3r** [comment]
> у меня хакинтош

Какая версия MacOS у вас?

**Comment by borisorlov21** [comment]
это ясно а что потом

**Comment by borisorlov21** [comment]
13.6.1 (22G313)

**Comment by rzc0d3r** [comment]
> 13.6.1 (22G313)

От ссылка на последнюю версию Питона на МакОС

https://www.python.org/ftp/python/3.12.0/python-3.12.0-macos11.pkg

**Comment by borisorlov21** [comment]
а библиотека какую ставить

**Comment by rzc0d3r** [comment]
> а библиотека какую ставить
> 

Ну после установки у вас команда|```python``` должна в терминале запускать интерпретатор. Попробуйте сделать это

**Comment by borisorlov21** [comment]
как правильно написать

**Comment by borisorlov21** [comment]
я в питоне 0

**Comment by rzc0d3r** [comment]
> я в питоне 0

У вас есть телеграмм?

**Comment by borisorlov21** [comment]
нет

**Comment by rzc0d3r** [comment]
> нет
> 

Просто общаться через гитхаб очень не удобно.

**Comment by borisorlov21** [comment]
у меня недоверие ктелеграм

**Comment by borisorlov21** [comment]
могу вас поздравить и себя тоже установил пакеты pip3 install colorama pip3 install requests и pip3 install selenium
![Screen Shot 2023-11-30 at 22 28 46](https://github.com/rzc0d3r/ESET-KeyGen/assets/66428911/4ae9562f-2c0f-4f29-910b-93f8fa4d2337)
![Screen Shot 2023-11-30 at 22 34 05](https://github.com/rzc0d3r/ESET-KeyGen/assets/66428911/09071752-8566-4fb8-9e20-199b650b973d)
👍🏻❤️
устанавливал на 
![Screen Shot 2023-11-30 at 22 37 12](https://github.com/rzc0d3r/ESET-KeyGen/assets/66428911/6c993eb9-78ec-45eb-8590-87820eb257a3)

**Comment by rzc0d3r** [comment]
крутяк!

**Comment by rzc0d3r** [comment]
> попробовал на хак монтерей 13.6.1 (22G313) неполучается моргает терминал и нет его хотя дал доступ

значит ошибка и вылетает

**Comment by rzc0d3r** [comment]
попробуйте открыть терминал и потом вручную прописать путь к main.py
```python main.py```

**Comment by rzc0d3r** [comment]
> ![Screenshot 2023-11-30 at 23 28 02](https://private-user-images.githubusercontent.com/66428911/287061570-7e9eb0ab-cd19-4a98-8850-1450532c3d0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzNzY1NDIsIm5iZiI6MTcwMTM3NjI0MiwicGF0aCI6Ii82NjQyODkxMS8yODcwNjE1NzAtN2U5ZWIwYWItY2QxOS00YTk4LTg4NTAtMTQ1MDUzMmMzZDBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDIwMzA0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmMDc3NDlmMzkzOTM2ZGZjOGU4OTZhYzQ5YjU3MjEyNjJmMjQ3ZjQ3ZGRlYTVlYWMxMDhhZWZiMDIzYmQ2ZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bIGV0-Fs-gE1rLA_fUcP87a0jWk6HUFBVD50q54_fVA)

ну это я написал в случае если вы открыли терминал в папке проекта

**Comment by rzc0d3r** [comment]
> ![Screenshot 2023-11-30 at 23 33 34](https://private-user-images.githubusercontent.com/66428911/287062695-20128d63-a60a-4220-9c8a-665b638ad13f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzNzY3MzcsIm5iZiI6MTcwMTM3NjQzNywicGF0aCI6Ii82NjQyODkxMS8yODcwNjI2OTUtMjAxMjhkNjMtYTYwYS00MjIwLTljOGEtNjY1YjYzOGFkMTNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDIwMzM1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1NzgwNDU0YmUwMzc4NDEzNDI5MmE2YTVlMzQ5NDJjODg3NTgzODAyNDRmZjlhNWI3NGEzY2ZjOGVkODZhZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XuZ4ZG3ATFbKy4n8I1hfIb_0Vmn5CG5mE6KlPte4FcI)

python3 %путь к main.py%

**Comment by borisorlov21** [comment]
![Screenshot 2023-11-30 at 23 35 31](https://github.com/rzc0d3r/ESET-KeyGen/assets/66428911/2621f120-ef05-4173-9763-4707f85ebe9f)

**Comment by borisorlov21** [comment]
папка на десктопа
напишете

**Comment by borisorlov21** [comment]
![Screenshot 2023-11-30 at 23 41 25](https://github.com/rzc0d3r/ESET-KeyGen/assets/66428911/7173d9de-3e8e-4639-8ad2-4bd0423a977a)

**Comment by rzc0d3r** [comment]
посмотрел я в интернете

**Comment by rzc0d3r** [comment]
наверное так

**Comment by borisorlov21** [comment]
![Screenshot 2023-11-30 at 23 52 41](https://github.com/rzc0d3r/ESET-KeyGen/assets/66428911/45eac009-348d-49fa-8e7a-1f9cf07d20ef)
![Screenshot 2023-11-30 at 23 53 38](https://github.com/rzc0d3r/ESET-KeyGen/assets/66428911/ceaa8528-e33d-43e0-a6bd-b1439af44406)

**Comment by rzc0d3r** [comment]
python3 /Users/imacpro/Desktop/ESET-KeyGen-main/main.py

**Comment by rzc0d3r** [comment]
[main.zip](https://github.com/rzc0d3r/ESET-KeyGen/files/13517744/main.zip)
замените main.py на этот и попробуйте запустить

**Comment by borisorlov21** [comment]
![Screenshot 2023-12-01 at 00 28 59](https://github.com/rzc0d3r/ESET-KeyGen/assets/66428911/69e89d40-2958-45ed-a22b-849fc04e9fd0)
попробовал 2 раза все хорошо запускал с терминала python3 /Users/imacpro/Desktop/ESET-KeyGen-main/main.py с файла Майн в папке неработает

**Comment by borisorlov21** [comment]
попробовал со старым Майн с терминалаpython3 /Users/imacpro/Desktop/ESET-KeyGen-main/main.py запускает и генерит общем этот этот Майн работает с терминала и в папку не устанавливается файлик хромдрайвер

**Comment by borisorlov21** [comment]
на каталине с терминала не работает только с файла

**Comment by rzc0d3r** [comment]
> на каталине с терминала не работает только с файла

наверное потому что python по другому прописан

**Comment by rzc0d3r** [comment]
ну а так измененый файл рабочий теперь что на каталине что тут.
