### ISSUE TITLE
ModuleNotFoundError: No module named 'colorama'

### ISSUE THREAD

**Issue by sirmalev** [rzc0d3r/ESET-KeyGen#52]
installed the colorama but when i run the main.py file it writes that ...
ESET-KeyGen-main\main.py", line 3, in <module>
    import modules.logger as logger

\ESET-KeyGen-main\modules\logger.py", line 2, in <module>
    from colorama import Fore, Style, init
ModuleNotFoundError: No module named 'colorama'

**Comment by rzc0d3r** [comment]
Most likely you have two versions of python. One is in the PATH and the other is not in the PATH. Pip is used from the PATH and the program is run from the other python.

**Comment by sirmalev** [comment]
Yeah, you were right.
I had two versions of Python, I deleted one of them and now it works.
thank you very much.
