### ISSUE TITLE
Eset blocked this website

### ISSUE THREAD

**Issue by VoidDave** [rzc0d3r/ESET-KeyGen#53]
So for whatever reason eset decided to add this repo on some type of blacklist. It is reported as a dangerous site. I think this information will be handy for you

**Comment by rzc0d3r** [comment]
The project is working. You mean the antivirus is blocking the repository page?

**Comment by VoidDave** [comment]
Exacly. I noticed it few hours ago

**Comment by rzc0d3r** [comment]
Lmao. Really:

![IMG_20231214_005224](https://github.com/rzc0d3r/ESET-KeyGen/assets/106631540/fc7ddf59-310c-4c0b-afe6-25df57cfd49a)

**Comment by rzc0d3r** [comment]
So the antivirus completely blocks my page on Github.  Even the main one! Haha

**Comment by rzc0d3r** [comment]
The way to solve this is to disable internet protection in eset antivirus before entering my github page. And then download the release and do the necessary work, and then you can turn it back on again

**Comment by rzc0d3r** [comment]
**Thx!** https://github.com/rzc0d3r/ESET-KeyGen/commit/8f17bd6d3f30a839b00f023a3d934aacac89d1aa
