### ISSUE TITLE
[ FAILED ] Traceback (most recent call last)

### ISSUE THREAD

**Issue by etamtlosz** [rzc0d3r/ESET-KeyGen#54]
I am getting the following error. Chrome is landing on https://home.eset.com/error, while the lg looks like this:

```
C:\kit\eset keygen>python main.py
-- Chrome Driver Auto-Installer v1.1.4 (171123-1640) by rzc0d3r --

[  INFO  ] Chrome version: 120.0.6099.110
[  INFO  ] Chrome driver version: 120.0.6099.109
[  INFO  ] Initializing chrome-driver for Windows

-- ESET KeyGen v1.0.9.2 (211123-1059) by rzc0d3r --

[  INFO  ] Mail registration...
[   OK   ] Mail registration completed successfully!

[  INFO  ] [EMAIL] Register page loading...
[   OK   ] [EMAIL] Register page is loaded!

[  INFO  ] Bypassing cookies...
[   OK   ] Cookies successfully bypassed!

[  INFO  ] [PASSWD] Register page loading...
[   OK   ] [PASSWD] Register page is loaded!

[   OK   ] ESET Token: b9d85396-be5c-452b-b0e1-6609436d58fa

[  INFO  ] Account confirmation is in progress...
[   OK   ] Account successfully confirmed!

[  INFO  ] Request sending...
[  INFO  ] Waiting for permission to request...
[   OK   ] Access to the request was open!

[  INFO  ] Platforms loading...
[   OK   ] Windows platform is selected!

[  INFO  ] Request license page loading...
[  INFO  ] Sending a request for a license...
[  INFO  ] Waiting for confirmation of request...
[ FAILED ] Traceback (most recent call last):
  File "C:\kit\eset keygen\main.py", line 97, in <module>
    EsetKeyG.sendRequestForKey()
  File "C:\kit\eset keygen\modules\eset_keygen.py", line 40, in sendRequestForKey
    uCE(self.driver, f"return {CLICK_WITH_BOOL}({GET_EBAV}('ion-button', 'robot', 'common-base-modal-header-close-btn'))")
  File "C:\kit\eset keygen\modules\shared_tools.py", line 60, in untilConditionExecute
    raise RuntimeError('untilConditionExecute: the code did not return the desired value!')
RuntimeError: untilConditionExecute: the code did not return the desired value!

Press Enter...
```

**Comment by rzc0d3r** [comment]
Now works only account!

**Comment by rzc0d3r** [comment]
Use ```--account``` command argument.

**Comment by etamtlosz** [comment]
Cheers.

**Comment by ramosman22** [comment]
I'm getting the same error but at different point. 

```
PS C:\Users\User\Desktop> .\ESET-KeyGen_v1.0.9.2-211123-1059_win32.exe --account
-- Chrome Driver Auto-Installer v1.1.4 (171123-1640) by rzc0d3r --

[  INFO  ] Chrome version: 120.0.6099.110
[  INFO  ] Chrome driver version: 120.0.6099.109
[  INFO  ] Initializing chrome-driver for Windows

-- ESET Account Generator v1.0.9.2 (211123-1059) by rzc0d3r --

[  INFO  ] Mail registration...
[   OK   ] Mail registration completed successfully!


[  INFO  ] [EMAIL] Register page loading...
[   OK   ] [EMAIL] Register page is loaded!
[ FAILED ] Traceback (most recent call last):
  File "main.py", line 88, in <module>
  File "modules\eset_register.py", line 41, in createAccount
  File "selenium\webdriver\remote\webdriver.py", line 407, in execute_script
  File "selenium\webdriver\remote\webdriver.py", line 347, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 229, in check_response
selenium.common.exceptions.JavascriptException: Message: javascript error: Cannot set properties of null (setting 'value')
  (Session info: chrome=120.0.6099.110)

Press Enter...
```

**Comment by Lomic0** [comment]
yep, and one more error 

C:\Users\user\Downloads\ESET-KeyGen-main>python main.py --account
-- Chrome Driver Auto-Installer v1.1.4 (171123-1640) by rzc0d3r --

[  INFO  ] Chrome version: 120.0.6099.129
[  INFO  ] Chrome driver version: 120.0.6099.109
[  INFO  ] Initializing chrome-driver for Windows

-- ESET Account Generator v1.0.9.4 (191223-1432) by rzc0d3r --

[  INFO  ] Mail registration...
[   OK   ] Mail registration completed successfully!

[  INFO  ] [EMAIL] Register page loading...
[   OK   ] [EMAIL] Register page is loaded!

[  INFO  ] Bypassing cookies...
[   OK   ] Cookies successfully bypassed!
[ FAILED ] Traceback (most recent call last):
  File "C:\Users\user\Downloads\ESET-KeyGen-main\main.py", line 90, in <module>
    EsetReg.createAccount()
  File "C:\Users\user\Downloads\ESET-KeyGen-main\modules\eset_register.py", line 49, in createAccount
    exec_js(f"{GET_EBID}('Email').value='{self.email_obj.get_full_login()}'")
  File "C:\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 404, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 344, in execute
    self.error_handler.check_response(response)
  File "C:\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: javascript error: Cannot set properties of null (setting 'value')
  (Session info: chrome=120.0.6099.109)

Press Enter...

**Comment by rzc0d3r** [comment]
**Try the new version [v1.1.0.0 (211223-1312)](https://github.com/rzc0d3r/ESET-KeyGen/releases/tag/v1.1.0.0-211223-1312) !!!**
