### ISSUE TITLE
я

### ISSUE THREAD

**Issue by borisorlov21** [rzc0d3r/ESET-KeyGen#58]
20 и21 декабря несмог сгенерить а 22 с впн сработало но на сайт гитхаб без впн незайти неясно что это было 
![Screenshot 2023-12-22 at 21 26 16](https://github.com/rzc0d3r/ESET-KeyGen/assets/66428911/f8e54f1f-3425-4b0f-b627-1a6270b6cdb3)

**Comment by rzc0d3r** [comment]
Я описывал это в README. Антивирус Есета блокирует мою страничку гитхаба. Я для него теперь как вирусный сайт.

**Comment by rzc0d3r** [comment]
+ обновление было на сайте, я искал как его решить. Решил 22 числа и добавил обновление, от оно и заработало
