### ISSUE TITLE
Web Driver problem

### ISSUE THREAD

**Issue by mhkanon** [rzc0d3r/ESET-KeyGen#6]
When I run, I face this issue. How can I fix it?

[*] Initializing driver for Linux
Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 116.0.5845.110 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
!

[Screenshot 2023-08-30 at 1 09 24 PM](https://github.com/rzc0d3r/ESET-KeyGen/assets/24652688/4f62aaf2-591a-4cf7-b115-e407085bc6e1)

**Comment by rzc0d3r** [comment]
This problem is described in the manual. You need to update the driver to the version of your chrome. In your case it is 116. Download the driver of this version and replace the old one

**Comment by mhkanon** [comment]
> [*] Initializing driver for Linux
> Error getting version of chromedriver 116. Retrying with chromedriver 115 (attempt 1/5)
> Error getting version of chromedriver 115. Retrying with chromedriver 114 (attempt 2/5)
> Message: session not created: This version of ChromeDriver only supports Chrome version 114
> Current browser version is 116.0.5845.140 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

How can I fix it? chromewebdriver 116 is not released yet.
