### ISSUE TITLE
Unable to generate keys on Windows

### ISSUE THREAD

**Issue by AdityaGarg8** [rzc0d3r/ESET-KeyGen#61]
When I try the exe file on Windows, I get this error when I try to generate keys. I can generate accounts though

```
[ FAILED ] Traceback (most recent call last):
  File "main.py", line 109, in <module>
  File "modules/eset_keygen.py", line 24, in sendRequestForKey
  File "modules/shared_tools.py", line 61, in untilConditionExecute
RuntimeError: untilConditionExecute: the code did not return the desired value!
```

**Comment by rzc0d3r** [comment]
I get this:

![image](https://github.com/rzc0d3r/ESET-KeyGen/assets/106631540/af02df27-b381-453d-9635-fc735a2de6ae)

**Comment by AdityaGarg8** [comment]
![image](https://github.com/rzc0d3r/ESET-KeyGen/assets/85610623/5d5599dd-a241-413a-b1a9-c7f1bc63ed7e)
I get this with the latest exe

**Comment by AdityaGarg8** [comment]
I am able to generate accounts with this without any issue

**Comment by rzc0d3r** [comment]
> ![image](https://private-user-images.githubusercontent.com/85610623/292870865-5d5599dd-a241-413a-b1a9-c7f1bc63ed7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1OTU0ODAsIm5iZiI6MTcwMzU5NTE4MCwicGF0aCI6Ii84NTYxMDYyMy8yOTI4NzA4NjUtNWQ1NTk5ZGQtYTI0MS00MTNhLWIxYTktYzdmMWJjNjNlZDdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDEyNTMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5NWVhOGQ1OTc2ZTRlOGVlMDRhN2FkYWVhNmIyZjZhMjMyMTZhMTkyZWZlYzBlZDk2ZDRjZGIwOTRjYjIzZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UFlC70UGXSuK-4mFtWermGNuTAeXUHahNC27BJaBXUY) I get this with the latest exe

The problem is that it's probably affected by headless mode, but I don't get that error.

**Comment by AdityaGarg8** [comment]
I see, I anyways can use GitHub CI so its ok.

**Comment by rzc0d3r** [comment]
Extract this archive to root project folder with replace files
[modules.zip](https://github.com/rzc0d3r/ESET-KeyGen/files/13771687/modules.zip)

**Comment by AdityaGarg8** [comment]
It turns out that it is not setting the region correctly. My region is India and trial is not there so thats why it doesn't work

**Comment by AdityaGarg8** [comment]
![image](https://github.com/rzc0d3r/ESET-KeyGen/assets/85610623/de78cb41-be36-4630-9ce3-a4d35ee51fd4)

**Comment by AdityaGarg8** [comment]
Also, your software is now detected as a virus by Windows Defender :(

**Comment by rzc0d3r** [comment]
> Also, your software is now detected as a virus by Windows Defender :(

Because pyinstaller uses algorithms similar to upx, and that's what viruses do. So all files with such algorithms are considered viruses, although this is not always the case.

**Comment by rzc0d3r** [comment]
> ![image](https://private-user-images.githubusercontent.com/85610623/292873686-de78cb41-be36-4630-9ce3-a4d35ee51fd4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1OTcwNzUsIm5iZiI6MTcwMzU5Njc3NSwicGF0aCI6Ii84NTYxMDYyMy8yOTI4NzM2ODYtZGU3OGNiNDEtYmUzNi00NjMwLTljZTMtYTRkMzVlZTUxZmQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDEzMTkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwYzEyM2MxMjIyYjM1ZDAxZTEyZjZhOTU0MTJlODc1NmQwOTBlMWU5ZmYyZGU0Mjc1Nzc1ZGRjN2U2NWUxYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DxJ5VSWHpqAczxXDLZGU2ZnLPEHkcYLLuLrwT7ozcis)

It seems to be because of the country. I removed the country change in the last global update, as I haven't found a way to address this yet.

**Comment by AdityaGarg8** [comment]
I'll have to use a VPN then

**Comment by AdityaGarg8** [comment]
Should I keep it open?

**Comment by rzc0d3r** [comment]
> Стоит ли мне оставить вопрос открытым?

YES

**Comment by AdityaGarg8** [comment]
I don't how much about the code but can this be of some help?

https://www.browserstack.com/guide/python-selenium-select-dropdown#:~:text=start%20your%20testing.-,How%20to%20Select%20Option%20in%20Dropdown%20using%20Selenium%20Python,the%20Select%20class%20from%20it.

**Comment by rzc0d3r** [comment]
Try this [ESET-KeyGen_v1.1.0.1-pre.zip](https://github.com/rzc0d3r/ESET-KeyGen/files/13772337/ESET-KeyGen_v1.1.0.1-pre.zip)

**Comment by AdityaGarg8** [comment]
> Try this [ESET-KeyGen_v1.1.0.1-pre.zip](https://github.com/rzc0d3r/ESET-KeyGen/files/13772337/ESET-KeyGen_v1.1.0.1-pre.zip)

same error

**Comment by rzc0d3r** [comment]
> > Try this [ESET-KeyGen_v1.1.0.1-pre.zip](https://github.com/rzc0d3r/ESET-KeyGen/files/13772337/ESET-KeyGen_v1.1.0.1-pre.zip)
> 
> same error

I'll send you a new version right now. There you will have to manually select the country. Select Ukraine and in the console press enter

**Comment by AdityaGarg8** [comment]
ok

**Comment by rzc0d3r** [comment]
[ESET-KeyGen_v1.1.0.1-pre2.zip](https://github.com/rzc0d3r/ESET-KeyGen/files/13772417/ESET-KeyGen_v1.1.0.1-pre2.zip)

**Comment by AdityaGarg8** [comment]
manually selecting ukraine worked

**Comment by AdityaGarg8** [comment]
I guess thats not a very nice way though.

**Comment by rzc0d3r** [comment]
> I guess thats not a very nice way though.

I just wanted to see if the country had any effect on the restrictions. Well, as you can see, it does.
This still needs to be put back into the project somehow.

**Comment by AdityaGarg8** [comment]
```
<div class="select__single-value ltr-1dimb5e-singleValue">India</div>
```

I got this

**Comment by AdityaGarg8** [comment]
```
from selenium import webdriver
from selenium.webdriver.support.ui import Select
from selenium.webdriver.common.by import By

# Create a webdriver instance (make sure you have the appropriate driver installed)
driver = webdriver.Chrome()

# Open the webpage
driver.get("your_website_url_here")

# Find the element by its class name (you can use another locating strategy if needed)
country_element = driver.find_element(By.CLASS_NAME, "select__single-value")

# Use Selenium's Select class to interact with dropdowns
select = Select(country_element)

# Change the country to the desired one (replace 'NewCountry' with the actual country name)
new_country = 'NewCountry'
select.select_by_visible_text(new_country)

# You might need to wait for the changes to take effect (if there's any dynamic loading)
# You can use WebDriverWait for this purpose

# Perform any additional actions or submit the form if needed

# Close the browser window
driver.quit()
```

Can this work?

**Comment by rzc0d3r** [comment]
I found the new method I'm just laughing at how stupid I was and how much time I wasted!!

**Comment by AdityaGarg8** [comment]
Good to know. I am happy to test.

**Comment by rzc0d3r** [comment]
> Good to know. I am happy to test.

[ESET-KeyGen_v1.1.1.0-pre.zip](https://github.com/rzc0d3r/ESET-KeyGen/files/13772731/ESET-KeyGen_v1.1.1.0-pre.zip)

**Comment by AdityaGarg8** [comment]
![image](https://github.com/rzc0d3r/ESET-KeyGen/assets/85610623/140ce5e2-ec17-44e2-bc9c-7625c833a4ce)
It selected ukraine though

**Comment by rzc0d3r** [comment]
Code Refers to a dead DOM pointer. I'll see what I can do about it

**Comment by rzc0d3r** [comment]
[ESET-KeyGen_v1.1.1.0-pre2.zip](https://github.com/rzc0d3r/ESET-KeyGen/files/13773060/ESET-KeyGen_v1.1.1.0-pre2.zip)

**Comment by AdityaGarg8** [comment]
It works

**Comment by AdityaGarg8** [comment]
> [ESET-KeyGen_v1.1.1.0-pre2.zip](https://github.com/rzc0d3r/ESET-KeyGen/files/13773060/ESET-KeyGen_v1.1.1.0-pre2.zip)

Even macOS binary works now

<img width="682" alt="image" src="https://github.com/rzc0d3r/ESET-KeyGen/assets/85610623/ebb838b6-dcfd-4fec-af25-5b44cc1293e1">

**Comment by AdityaGarg8** [comment]
In case you update the readme for macOS, you may want to add that the binary has to be made executable by running `chmod a+x /path/to/binary` before running on the terminal.
