### ISSUE TITLE
The program cannot be started because the computer is missing api-ms-win-core-path-ll-l-0.dll . Try reinstalling the program.

### ISSUE THREAD

**Issue by stringer-popov** [rzc0d3r/ESET-KeyGen#64]
Hello.
I ran this script, but an error appeared:
The program cannot be started because the computer is missing api-ms-win-core-path-ll-l-0.dll . Try reinstalling the program.
Operating system window 7 is the maximum.
Tell me what to do.
![api-ms-win-core-path-ll-l-0](https://github.com/rzc0d3r/ESET-KeyGen/assets/125668727/bc7ce952-8e5f-4bb7-9978-702f9ff5c634)

**Comment by TrasserZero** [comment]
Try this - https://support.microsoft.com/en-us/topic/update-for-universal-c-runtime-in-windows-c0514201-7fe6-95a3-b0a5-287930f3560c

**Comment by rzc0d3r** [comment]
Starting with version 1.1.0.0 compiled exe files do not work on 7 windows, because new python is used. You need to download the source code and run main.py!

**Comment by stringer-popov** [comment]
And which installer should I choose?
![установщики анг](https://github.com/rzc0d3r/ESET-KeyGen/assets/125668727/07b1e4cf-edc0-4383-8e8b-005f76913a0f)

**Comment by rzc0d3r** [comment]
windows x86 executable installer

**Comment by rzc0d3r** [comment]
Я так понимаю, что вы русскоговорящий человек. Удалите текущую версию python и установить python 3.8.0 (В установщике поставьте галочку Add to PATH). Потом откройте командую строку и пропишите ```pip install selenium requests colorama```. Далее запускаете мой проект нажатием на main.py

**Comment by stringer-popov** [comment]
Здравствуйте, да я русскоязычный человек. Python ошибку выдаёт, правда я 64-битную версию установил.
![ошибки](https://github.com/rzc0d3r/ESET-KeyGen/assets/125668727/c1b54b63-9ea2-44f7-81f6-2560655aff15)

Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit
(AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> pip install selenium requests colorama
  File "<stdin>", line 1
    pip install selenium requests colorama
        ^
SyntaxError: invalid syntax
>>> python main.py --account
  File "<stdin>", line 1
    python main.py --account
           ^
SyntaxError: invalid syntax
>>> main.py --account
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'main' is not defined

**Comment by rzc0d3r** [comment]
Просто откройте командную строку. Win + R и напишите cmd. А потом только команды вводите

**Comment by rzc0d3r** [comment]
pip install requests, selenium, colorama

**Comment by rzc0d3r** [comment]
Потом напишите python, нажмите пробел и перетащить в окно командной строки main.py с проекта. И нажмите Enter

**Comment by rzc0d3r** [comment]
Потом напишите python, нажмите пробел и перетащить в окно командной строки main.py с проекта. И нажмите Enter.

Ну или же просто два раза кликните на main.py в проводнике, вместо этого всего

**Comment by rzc0d3r** [comment]
Если вам нужно передавать аргументы в main.py то через командную строку все делайте

**Comment by rzc0d3r** [comment]
Попробуйте эту версию [ESET-KeyGen-pre.zip](https://github.com/rzc0d3r/ESET-KeyGen/files/13809462/ESET-KeyGen-pre.zip)

**Comment by rzc0d3r** [comment]
Модули нужно устанавливать без разделение запятой просто ```pip install colorama selenium requests```

**Comment by stringer-popov** [comment]
Модули я прописал без запятой, этот шаг без проблем прошел. Только мол версия pip устарела.
ВНИМАНИЕ: вы используете версию pip 19.2.3, однако доступна версия 23.3.2.
Вам следует рассмотреть возможность обновления через команду «python -m pip install --upgrade pip».
и.
![1](https://github.com/rzc0d3r/ESET-KeyGen/assets/125668727/cc5513ca-4995-423b-a097-2bd0f0e3f8d6)

**Comment by stringer-popov** [comment]
а потом проблемы начались.
C:\Users\Дмитрий>python "D:\дистр\Защита\езет нод32\ключи лицензия\скрипт\main.p
y\main.py"
Traceback (последний вызов последний):
   Файл "D:\дистр\Защита\езет нод32\ключи лицензии\скрипт\main.py\main.py", строка
13, в <модуле>
     импортировать модули.chrome_driver_installer как chrome_driver_installer
ModuleNotFoundError: нет модуля с именем «модули».

python: невозможно открыть файл 'D:\\дистр\\Защита\\езет нод32\\ключи лицензии\\скрипт\\
main.py\\main.py': [Errno 2] Нет такого файла или каталога

C:\Users\Дмитрий>python D:\дистр\Защита\езет нод32\ключи лицензии\скрипт\main.py
\main.py --account
python: невозможно открыть файл 'D:\\дистр\\Защита\\езет': [Errno 2] Нет такого файла или каталога
Экори
![без запятой](https://github.com/rzc0d3r/ESET-KeyGen/assets/125668727/c9a27f22-0296-4056-9e41-a0081eaffc3f)

**Comment by stringer-popov** [comment]
А это с ESET-KeyGen-pre.
C:\Users\Дмитрий>python "D:\дистр\Защита\езет нод32\ключи лицензия\скрипт\ESET-K
eyGen-pre\main.py"
Traceback (последний вызов последний):
   Файл "D:\дистр\Защита\езет нод32\ключи лицензия\скрипт\ESET-KeyGen-pre\main.py
", строка 14, в <модуле>
     импортировать модули.logger как регистратор
   Файл "D:\дистр\Защита\езет нод32\ключи лицензии\скрипт\ESET-KeyGen-pre\modules
\logger.py", строка 1, в <модуле>
     из импорта Colorama Fore, Style, init
ModuleNotFoundError: нет модуля с именем «colorama».

C:\Users\Дмитрий>python D:\дистр\Защита\езет нод32\ключи лицензия\скрипт\ESET-Ke
yGen-pre\main.py --account
python: невозможно открыть файл 'D:\\дистр\\Защита\\езет': [Errno 2] Нет такого файла или каталога
Экори
![cmd](https://github.com/rzc0d3r/ESET-KeyGen/assets/125668727/df67600c-6e51-4638-ba64-af1e719cdca0)

**Comment by rzc0d3r** [comment]
А вы устанавливали colorama?

**Comment by rzc0d3r** [comment]
По скриншоту видно что нет. ```pip install colorama```

**Comment by rzc0d3r** [comment]
а также пути при вызове команд всегда берите в скобки. (Из-за пробелов путь обрывается)

**Comment by stringer-popov** [comment]
установил colorama.
![майн](https://github.com/rzc0d3r/ESET-KeyGen/assets/125668727/c493c36c-395d-4435-9289-d3afd21dcf30)

Но снова облом.
python: невозможно открыть файл 'D:\\дистр\\Защита\\езет нод32\\ключи лицензии\\скрипт\\
main.py\\main.py': [Errno 2] Нет такого файла или каталога

**Comment by stringer-popov** [comment]
а это при использовании ESET-KeyGen-pre.
![пре](https://github.com/rzc0d3r/ESET-KeyGen/assets/125668727/24b73f94-5b63-4fc9-b9ae-a8f227c776e6)

Traceback (последний вызов последний):
   Файл "D:\дистр\Защита\езет нод32\ключи лицензия\скрипт\ESET-KeyGen-pre\main.py
", строка 14, в <модуле>
     импортировать модули.logger как регистратор
   Файл "D:\дистр\Защита\езет нод32\ключи лицензии\скрипт\ESET-KeyGen-pre\modules
\logger.py", строка 1, в <модуле>
     из импорта Colorama Fore, Style, init
ModuleNotFoundError: нет модуля с именем «colorama».

**Comment by rzc0d3r** [comment]
А у вас случаем не две версии питона на компе?

**Comment by stringer-popov** [comment]
вроде две.
![Revo Uninstaller](https://github.com/rzc0d3r/ESET-KeyGen/assets/125668727/d09e2fc1-ecd1-4499-a8b4-856b15a40c89)

**Comment by TrasserZero** [comment]
Ох, парни, куда проще прямо в своей репе всё сделать =)
ПС - сорри за оффтоп..

**Comment by rzc0d3r** [comment]
> Ох, парни, куда проще прямо в своей репе всё сделать =) ПС - сорри за оффтоп..

Я тоже так думаю. Форкнуть и использовать Actions

**Comment by rzc0d3r** [comment]
> вроде две. ![Revo Uninstaller](https://private-user-images.githubusercontent.com/125668727/293716067-d09e2fc1-ecd1-4499-a8b4-856b15a40c89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMTE5MzIsIm5iZiI6MTcwNDIxMTYzMiwicGF0aCI6Ii8xMjU2Njg3MjcvMjkzNzE2MDY3LWQwOWUyZmMxLWVjZDEtNDQ5OS1hOGI0LTg1NmIxNWE0MGM4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMlQxNjA3MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZjgwYzE2OTgzNDVkYjZiOGVjMzA4M2M3NWJlNGU1Mzg1YWI5ZWM3ZTkwZDZlOGZhZjEwMmMyNjhhZmIwMDVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.x6yMma-rCaVNZSUKdqUGHVMVzGVntnn-FZ7LlqvD45Q)

Реально. Я думаю уже все устали от это кликать и что-то ковырять. Windows 7 не тестируемая платформа.
Сделайте форк моего проекта, далее зайди на  свою страничку на гитхабе. Вы увидите у себя мой проект, открываете его нажимаете Actions и там выбераете ESET Keys & Accounts Generator (MAIN), нажимаете Run workflow далее введите сколько вам нужно ключей и аккаунов, нажимаете Run workflow. Далее ждите пока не появится галочка. Нажимаете на нее и вам внизу страницы будет результат

**Comment by rzc0d3r** [comment]
быстро, легко, и главное не требует от вашего устройтва ничего

**Comment by rzc0d3r** [comment]
не зря же делали )

**Comment by stringer-popov** [comment]
я не знаю как сделать форк проекта.

**Comment by rzc0d3r** [comment]
> я не знаю как сделать форк проекта.

![image](https://github.com/rzc0d3r/ESET-KeyGen/assets/106631540/bd2514f6-9971-402f-9f52-43a687ef63ae)

**Comment by stringer-popov** [comment]
а долго он думать будет?
![долго](https://github.com/rzc0d3r/ESET-KeyGen/assets/125668727/ed2ac8dd-a363-4f22-a7c4-0131ba4ba64e)

**Comment by rzc0d3r** [comment]
Та не должен. В районе 45-90с

**Comment by rzc0d3r** [comment]
Хотя скорее всего вы ввели там 49594929305 ключей и аккаунтов. От оно уже 15м генерирует.

**Comment by AdityaGarg8** [comment]
@stringer-popov , can you test this: https://github.com/AdityaGarg8/ESET-KeyGen/releases/tag/vtest

**Comment by stringer-popov** [comment]
спасибо, появился ключ.
Когда я по названию fork нажал. Но вводил я 1 ключ и 1 аккаунт, мне 1 ключа хватит.
![ключ htl](https://github.com/rzc0d3r/ESET-KeyGen/assets/125668727/de49252a-9566-4750-8fc5-a5260ef2aad5)
![название](https://github.com/rzc0d3r/ESET-KeyGen/assets/125668727/d1bc0778-1d6a-47e7-89a1-7a77187da9e9)

**Comment by stringer-popov** [comment]
А тариф у антивируса можно выбирать?

**Comment by rzc0d3r** [comment]
К сожелению нет. Только 31 день
