### ISSUE TITLE
I can't run it, what's the problem?

### ISSUE THREAD

**Issue by ReLoadTR** [rzc0d3r/ESET-KeyGen#65]
![Screenshot_3](https://github.com/rzc0d3r/ESET-KeyGen/assets/147206354/1ed38639-91b2-4e23-b0bd-5823f6127519)

**Comment by rzc0d3r** [comment]
what version of python?

**Comment by ReLoadTR** [comment]
> what version of python?

3.12.0

**Comment by rzc0d3r** [comment]
You can see from the screenshot that Python thinks the module in the folder is not a module. Try using the command line to open inside the project folder

**Comment by rzc0d3r** [comment]
> > what version of python?
> 
> 3.12.0

I'm also using this version but I don't have this error. Although I do the same as you

**Comment by ReLoadTR** [comment]
![Screenshot_1](https://github.com/rzc0d3r/ESET-KeyGen/assets/147206354/de5091d7-7ed4-453e-943a-5aa9ddeaece3)

**Comment by rzc0d3r** [comment]
Create an empty file named ```__init__.py``` in the project directory in ESET-KeyGen-main/modules

**Comment by ReLoadTR** [comment]
![image](https://github.com/rzc0d3r/ESET-KeyGen/assets/147206354/fe9fefc4-793c-4533-9c39-9debfe867726)

I guess it won't happen

**Comment by rzc0d3r** [comment]
try just main.py

**Comment by rzc0d3r** [comment]
You may need to reinstall the libraries via pip install -r requirements

**Comment by ReLoadTR** [comment]
> try just main.py without python

I tried like this and it didn't work

> You may need to reinstall the libraries via pip install -r requirements

pip install -r requirements.txt got the update but it still didn't work

**Comment by rzc0d3r** [comment]
Use the Github Actions way for now. I'll post an update so there won't be any more problems with imports. Strange bug.

**Comment by rzc0d3r** [comment]
try it [ESET-KeyGen-pre.zip](https://github.com/rzc0d3r/ESET-KeyGen/files/13809443/ESET-KeyGen-pre.zip)

**Comment by ReLoadTR** [comment]
![image](https://github.com/rzc0d3r/ESET-KeyGen/assets/147206354/afc50c26-f146-4880-9d4c-54732effc0d2)

I give up, let's close the issue.

**Comment by rzc0d3r** [comment]
> ![image](https://private-user-images.githubusercontent.com/147206354/293714602-afc50c26-f146-4880-9d4c-54732effc0d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMDY5ODMsIm5iZiI6MTcwNDIwNjY4MywicGF0aCI6Ii8xNDcyMDYzNTQvMjkzNzE0NjAyLWFmYzUwYzI2LWYxNDYtNDg4MC05ZDRjLTU0NzMyZWZmYzBkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMlQxNDQ0NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZGU4ZGRmMzg1NmJjMThjYWJiZjYyZjQ1MzA1MTdmNTBjOWI3NTlhNjMzMjdhNTJiOGJjOTM5ZmMyMjllMDQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.f_kx-tklxxxNGM3bocJ1VFGlZs88aYm4jfZEyZutK84)
> 
> I give up, let's close the issue.

```
pip uninstall selenium
pip install selenium
```

**Comment by ReLoadTR** [comment]
finally worked
thank you so much
