### ISSUE TITLE
Expire

### ISSUE THREAD

**Issue by MrNico98** [rzc0d3r/ESET-KeyGen#66]
![image](https://github.com/rzc0d3r/ESET-KeyGen/assets/136261932/aaa9aeb7-feb8-4461-b52b-5dca9a69a1fe)

i create a key and expire on this day?

**Comment by rzc0d3r** [comment]
no. Out Date Format: MONTH/DAY/YEAR (31 days)

**Comment by MrNico98** [comment]
is active for 31days?
