### ISSUE TITLE
error on pip

### ISSUE THREAD

**Issue by MrNico98** [rzc0d3r/ESET-KeyGen#67]
![image](https://github.com/rzc0d3r/ESET-KeyGen/assets/136261932/852173c2-549f-4fc7-9d33-63626e9718b8)

how i can fix?

**Comment by rzc0d3r** [comment]
python -m pip install colorama selenium requests

**Comment by MrNico98** [comment]
thx fix

**Comment by MrNico98** [comment]
thx fix
