### ISSUE TITLE
@stringer-popov , can you test this: https://github.com/AdityaGarg8/ESET-KeyGen/releases/tag/vtest

### ISSUE THREAD

**Issue by stringer-popov** [rzc0d3r/ESET-KeyGen#69]
@stringer-popov , can you test this: https://github.com/AdityaGarg8/ESET-KeyGen/releases/tag/vtest

![cmd](https://github.com/rzc0d3r/ESET-KeyGen/assets/125668727/832b2f25-9ff4-4ea7-861d-59c068fd084c)
      
                                    Project Version: v1.1.1.0
                                                Project Devs: rzc0d3r, AdityaGar
g8, k0re,
                                                              Fasjeit, alejanpa1
7

-- Chrome Driver Auto-Installer --

[  INFO  ] Chrome version: 109.0.5414.120
[  INFO  ] Chrome driver version: None

[ FAILED ] Chrome driver not detected, download attempt...
[ FAILED ] Traceback (most recent call last):
  File "main.py", line 85, in <module>
  File "main.py", line 51, in chrome_driver_installer_menu
  File "modules\chrome_driver_installer.py", line 89, in get_driver_download_url

  File "_collections_abc.py", line 660, in get
  File "requests\structures.py", line 52, in __getitem__
AttributeError: 'list' object has no attribute 'lower'

Press Enter...

**Comment by rzc0d3r** [comment]
Скачайте код по этой кнопке и используйте эту версию. Я ее протестировал и она должна теперь работать на 7 винде!

![image](https://github.com/rzc0d3r/ESET-KeyGen/assets/106631540/e3c419a2-aa8a-49fc-907b-bc9c041c84bf)

**Comment by rzc0d3r** [comment]
https://github.com/rzc0d3r/ESET-KeyGen/releases/download/v1.2.0.0/ESET-KeyGen_v1.2.0.0_win32.exe

**Comment by rzc0d3r** [comment]
Попробуйте эту экспериментальную сборку

**Comment by rzc0d3r** [comment]
К сожалению сайт есета отвергает версию хрома для 32 битной 7 винды

**Comment by rzc0d3r** [comment]
Я буду работать в этом направлении. Пока что не ясно как, но я попробую все что в моих силах.

**Comment by stringer-popov** [comment]
Благодарю, эта версия работает.
![работает](https://github.com/rzc0d3r/ESET-KeyGen/assets/125668727/22cf3327-cf4f-40ee-825e-d8b9823d365e)
