### ISSUE TITLE
This is NOT A KEYGEN. Just a 30-day Free Trial request.

### ISSUE THREAD

**Issue by e-t-l** [rzc0d3r/ESET-KeyGen#7]
As the title says, this script is (by the definition of the word) absolutely *not* a KeyGen. It does not *generate* valid ESET keys. All it does is automate the process of requesting a 30-day free trial from the ESET website by supplying a nonsense email address. 

In order to use ESET with any effectiveness, you must run this script every 30 days to renew your trial... and hope ESET doesn't blacklist your IP because of it. If you don't mind doing that, I suppose it's mildly convenient. Very misleading title, though.

**Comment by rzc0d3r** [comment]
I'm not hiding it. But it's still better than doing it all manually. You can also use the ESET-License-Generator repository. There you can create a database of accounts and use them at any time. 

* Under the hood it's not a keygen, but the result of the work is a key, and that's close to a keygen :)
