### ISSUE TITLE
A way to choose the NOD32 edition

### ISSUE THREAD

**Issue by ns-studios** [rzc0d3r/ESET-KeyGen#72]
Is there a way to choose which NOD32 edition the key is being generated for?
I normally use Internet Security, but it generated Smart Security  Premium key for me.
How can I tell it to generate the Internet Security key?

**Comment by rzc0d3r** [comment]
Impossible. The key theoretically adapts to your version, if not, then install the version specified in the key. And just disable unnecessary functions in the antivirus itself
