### ISSUE TITLE
Choose the OS edition

### ISSUE THREAD

**Issue by soladify** [rzc0d3r/ESET-KeyGen#76]
Is it possible to implement the choice of operating system (Windows / Mac OS / Android) ?
As I understand it, the key is generated (Smart Security Premium only for Windows) without the ability to select edition AV or operating system..

**Comment by rzc0d3r** [comment]
> Is it possible to implement the choice of operating system (Windows / Mac OS / Android) ? As I understand it, the key is generated (Smart Security Premium only for Windows) without the ability to select edition AV or operating system..

Have you tried using the key in a different OS? People wrote me that it seems to work.

**Comment by soladify** [comment]
> > Is it possible to implement the choice of operating system (Windows / Mac OS / Android) ? As I understand it, the key is generated (Smart Security Premium only for Windows) without the ability to select edition AV or operating system..
> 
> Have you tried using the key in a different OS? People wrote me that it seems to work.

I tested it on Android, v. 7.1.11.0 - the key was not accepted - no new updates found. 
I reinstalled it manually, version 8.2.15.0-0 was installed. This version accepted the key ESET HOME Security Premium without any problems. Issue can be closed, thank you.
