### ISSUE TITLE
Message: javascript error: Cannot read properties of undefined (reading 'click')

### ISSUE THREAD

**Issue by Lplus7** [rzc0d3r/ESET-KeyGen#8]
Hello mate, I got this issue:

[*] Initializing driver for Windows

[*] [EMAIL] Register page loading...
[+] [EMAIL] Register page is loaded!

[*] [PASSWD] Register page loading...
[+] [PASSWD] Register page is loaded!

[+] ESET Token: 409c25f0-2f90-4919-82cd-4b69bef0647d

[*] Account confirmation is in progress...
[+] Account successfully confirmed!

[*] License page loading...
[+] License page is loaded!

[*] Request sending...
[*] Waiting for permission to request...
Message: javascript error: Cannot read properties of undefined (reading 'click')
  (Session info: chrome=117.0.5938.132)
Stacktrace:
	GetHandleVerifier [0x00007FF6ADA37D32+55474]
	(No symbol) [0x00007FF6AD9A77E2]
	(No symbol) [0x00007FF6AD85E0EB]
	(No symbol) [0x00007FF6AD862B1D]
	(No symbol) [0x00007FF6AD86495A]
	(No symbol) [0x00007FF6AD8D8584]
	(No symbol) [0x00007FF6AD8BF15A]
	(No symbol) [0x00007FF6AD8D7EF2]
	(No symbol) [0x00007FF6AD8BEF33]
	(No symbol) [0x00007FF6AD893D41]
	(No symbol) [0x00007FF6AD894F84]
	GetHandleVerifier [0x00007FF6ADD9B772+3609330]
	GetHandleVerifier [0x00007FF6ADDF1A90+3962384]
	GetHandleVerifier [0x00007FF6ADDE9F1F+3930783]
	GetHandleVerifier [0x00007FF6ADAD3CC6+694342]
	(No symbol) [0x00007FF6AD9B2238]
	(No symbol) [0x00007FF6AD9AE4A4]
	(No symbol) [0x00007FF6AD9AE5D2]
	(No symbol) [0x00007FF6AD99EE33]
	BaseThreadInitThunk [0x00007FF90DD554E0+16]
	RtlUserThreadStart [0x00007FF90DFA485B+43]

Press Enter...

Process finished with exit code 0

**Comment by rzc0d3r** [comment]
Try use vpn

**Comment by rzc0d3r** [comment]
Where do you life? Country Name.

**Comment by rzc0d3r** [comment]
Try [this version](https://github.com/rzc0d3r/ESET-KeyGen/blob/alpha/ESET%20KeyGen.py).
Do not use vpn, etc.
Test the new version.
I have a guess what this is related to.

**Comment by Lplus7** [comment]
Russia 😅
Yep, connection is clear

Will try, thanks a lot!🙏

**Comment by Lplus7** [comment]
Works perfectly, outstanding work, mate! Thanks!
![image](https://github.com/rzc0d3r/ESET-KeyGen/assets/115026663/2f9344cd-27e1-4eb0-91d2-e2a49536d5a8)

**Comment by rzc0d3r** [comment]
thanks for the feedback!
