### ISSUE TITLE
Is there a way to download and unzip the web driver only

### ISSUE THREAD

**Issue by AdityaGarg8** [rzc0d3r/ESET-KeyGen#85]
I had an ideal to make the CI more efficient, but need a way that makes the script download the webdriver only.

**Comment by rzc0d3r** [comment]
?

**Comment by rzc0d3r** [comment]
The script already downloads only the webdriver

**Comment by AdityaGarg8** [comment]
Currently what happens is that in order to generate keys/account, it first generates 1 key/account so that the web driver is installed. It doesn't run processes parallely as all will attempt to install the web driver then causing problems.

This wastes time as first it generates just 1 key then it generates other together.

So if it can just download the web driver upon running a Command, we can run all the processes parallely. Infact, we can also run keys and account process parallely as well!

**Comment by AdityaGarg8** [comment]
That's up to you. I just wanted any way

**Comment by rzc0d3r** [comment]
Added [```--only-update```](https://github.com/rzc0d3r/ESET-KeyGen/blob/main/wiki/CommandLineArguments.md) command line argument, [v1.3.0.2](https://github.com/rzc0d3r/ESET-KeyGen/releases/tag/v1.3.0.2)

**Comment by rzc0d3r** [comment]
Try this version.
Rewritten to selenium-webdriver manager. T
Removed ```--skip-webdriver-menu``` argument, added ```--skip-webdriver-update``` and ```--only-update```

[ESET-KeyGen-v1.3.1.0.zip](https://github.com/rzc0d3r/ESET-KeyGen/files/14181141/ESET-KeyGen-v1.3.1.0.zip)

**Comment by rzc0d3r** [comment]
You probably want to run the first time with --only-update and then all other runs with --skip-webdriver-update.

**Comment by rzc0d3r** [comment]
Also update before running the library!
```pip install -r requirements.txt```

**Comment by AdityaGarg8** [comment]
Thanks, I'll try that later
