### ISSUE TITLE
Please create a project for keygen of ESET nod32 ANTIVIRUS(not ESET smart security)

### ISSUE THREAD

**Issue by happymary888** [rzc0d3r/ESET-KeyGen#87]
The current project by you is great.But my PC installed eset ANTIVIRUS,after entering the license by keygen,it automatically change the product to ESET smart security premium.
ESET smart security premium then causes lots of network problems,so I have to uninstall it.
Please create a project for keygen of ESET nod32 ANTIVIRUS,so I can install ANTIVIRUS again.
Thanks!

**Comment by rzc0d3r** [comment]
Understand me, if I could find a way to do it, I would. But at the moment I haven't found a way to do it. Perhaps you can change the license through the antivirus itself in the Licenses/ESET HOME tab

**Comment by happymary888** [comment]
THANK YOU!
