### ISSUE TITLE
Google Chrome Missing

### ISSUE THREAD

**Issue by RyanGamez298** [rzc0d3r/ESET-KeyGen#90]
When I use it, it tells me that google chrome is missing when i have downloaded it what do i do

**Comment by rzc0d3r** [comment]
OC?
Current chrome path?

How did you install it? Through the installer or through a custom path?

**Comment by RyanGamez298** [comment]
Through the installer

**Comment by RyanGamez298** [comment]
it just shows this

[ FAILED ] Traceback (most recent call last):
  File "main.py", line 107, in <module>
  File "main.py", line 40, in webdriver_installer_menu
RuntimeError: Google Chrome is not detected on your device!

**Comment by RyanGamez298** [comment]
ok

**Comment by RyanGamez298** [comment]
google doesnt have a path in any of my drives

**Comment by RyanGamez298** [comment]
it just shows a normal program when i search it

**Comment by RyanGamez298** [comment]
no actually just found it 
![Screenshot (4)](https://github.com/rzc0d3r/ESET-KeyGen/assets/83865094/39dc4202-6960-44c5-bda9-63b49a5dbbea)

**Comment by rzc0d3r** [comment]
> it just shows a normal program when i search it
> 

Run chrome and through Task Manager open its path

**Comment by RyanGamez298** [comment]
i found it

**Comment by rzc0d3r** [comment]
All I've added is this location. Redownload source code of the project and try to run it.

**Comment by RyanGamez298** [comment]
ok ill try

**Comment by RyanGamez298** [comment]
it shows the same error

**Comment by rzc0d3r** [comment]
Open cmd and write this ```echo %CHROMEPATH%``` and take screenshot

**Comment by RyanGamez298** [comment]
it says %CHROMEPATH%

**Comment by rzc0d3r** [comment]
Redownload source code (Not in release tab) of the project and try to run it.

**Comment by RyanGamez298** [comment]
ok

**Comment by RyanGamez298** [comment]
it works thanks for your help, your response time is very good
