### ISSUE TITLE
Always Register page loading and end with failed

### ISSUE THREAD

**Issue by advancejar** [rzc0d3r/ESET-KeyGen#91]
Always Register page loading and end with failed

![no](https://github.com/rzc0d3r/ESET-KeyGen/assets/58756119/d72e92e9-4885-416f-83e5-10dc0138befa)

**Comment by rzc0d3r** [comment]
try run with ```--no-headless``` and take screenshot

**Comment by advancejar** [comment]
under normal circumstances, chrome can visit login.eset.com/Regitster
![1](https://github.com/rzc0d3r/ESET-KeyGen/assets/58756119/f19721e6-7280-4a17-af4d-59105a41f678)

Under chromedrive control,chrome can't visit the website
![2](https://github.com/rzc0d3r/ESET-KeyGen/assets/58756119/53dbba56-c87b-4d32-bcfc-67309a0dd79e)

Maybe there's some kind of test out there。

**Comment by advancejar** [comment]
> Vpn?

no , diect

**Comment by rzc0d3r** [comment]
I mean you should try a vpn

**Comment by advancejar** [comment]
In my experience, DrissionPage(https://github.com/g1879/DrissionPage) will not be detected by the website

**Comment by advancejar** [comment]
use vpn is ok.

**Comment by rzc0d3r** [comment]
> use vpn is ok.

Well, most likely, your country has restrictions that can be circumvented by using a VPN/PROXY

**Comment by advancejar** [comment]
> > use vpn is ok.
> 
> Well, most likely, your country has restrictions that can be circumvented by using a VPN/PROXY

It shouldn't be, normal access to eset website is fine, may be eset detects our chromedriver driven chrome.

**Comment by rzc0d3r** [comment]
Uh, no. There's nothing wrong with it.

**Comment by advancejar** [comment]
I use gtihub action to generate code, better than local machine.
close?

**Comment by rzc0d3r** [comment]
Yes.
