### ISSUE TITLE
Error on 32bit Windows 7

### ISSUE THREAD

**Issue by stevekat** [rzc0d3r/ESET-KeyGen#92]
Gets with this error under Win7 32bit:

```
[ FAILED ] Traceback (most recent call last):
  File "main.py", line 107, in <module>
  File "main.py", line 38, in webdriver_installer_menu
  File "modules\webdriver_installer.py", line 35, in get_chrome_version
  File "modules\webdriver_installer.py", line 17, in get_platform
IndexError: list assignment index out of range
```

Probably in webdriver_installer.py, line 17 must be 

`result[1] = ['win32']`

instead

`result[2] = ['win32']`

**Comment by rzc0d3r** [comment]
Yes, my stupid mistake. Try v1.3.0.5 release pls.

**Comment by rzc0d3r** [comment]
Try [v1.3.1.0](https://github.com/rzc0d3r/ESET-KeyGen/releases/tag/v1.3.1.0)

**Comment by stevekat** [comment]
**ESET-KeyGen_v1.3.1.0_win32.exe** 
it no longer gives this error but show another one:

under Windows7 - 32bit

```
[  INFO  ] Bypassing cookies...
[ FAILED ] Cookies were not bypassed (it doesn't affect the algorithm, I think :D)

[  INFO  ] [PASSWD] Register page loading...
[ FAILED ] Traceback (most recent call last):
  File "main.py", line 128, in <module>
  File "modules\eset_register.py", line 50, in createAccount
  File "modules\shared_tools.py", line 61, in untilConditionExecute
RuntimeError: untilConditionExecute: the code did not return the desired value!
```

Is the problem not in the not latest Chrome browser for win7 ?

under Windows10 - 64bit gives another error:

```
[  INFO  ] Sending a request for a license...
[   OK   ] Request successfully sent!

[  INFO  ] License uploads...
[ FAILED ] Traceback (most recent call last):
  File "main.py", line 136, in <module>
  File "modules\eset_keygen.py", line 41, in getLicenseData
  File "modules\shared_tools.py", line 61, in untilConditionExecute
RuntimeError: untilConditionExecute: the code did not return the desired value!
```

**ESET-KeyGen_v1.3.1.0_win64.exe** work fine under the same Windows10 - 64bit

**Comment by rzc0d3r** [comment]
in the first screenshot it looks like the site is not loading (maybe the site is checking the browser version, try the latest release under 7 windows)

**Comment by rzc0d3r** [comment]
and the second one looks like a rare bug in the new algorithm, I'm going to try to change something to something more stable now

**Comment by rzc0d3r** [comment]
Try [v1.3.1.1](https://github.com/rzc0d3r/ESET-KeyGen/releases/tag/v1.3.1.1)

**Comment by stevekat** [comment]
**under Windows 7 - 32bit**

ESET-KeyGen_v1.3.1.1_win32.exe

Error is the same:

```
[  INFO  ] Google Chrome version: 109.0.5414.120
[  INFO  ] Google Chrome webdriver version: 109.0.5414.74
```

```
[  INFO  ] Bypassing cookies...
[ FAILED ] Cookies were not bypassed (it doesn't affect the algorithm, I think : D)

[  INFO  ] [PASSWD] Register page loading...
[ FAILED ] Traceback (most recent call last):
  File "main.py", line 128, in <module>
  File "modules\eset_register.py", line 50, in createAccount
  File "modules\shared_tools.py", line 61, in untilConditionExecute
RuntimeError: untilConditionExecute: the code did not return the desired value!
```

I tested Chrome V109, ESET HOME works without a problem.
Chrome V109 is the latest version for Windows 7.
Later versions of Chrome do not support Windows 7.

Windows 7 will probably not be supported from this project.
Although the first releases worked.


**under Windows10 - 64bit**

ESET-KeyGen_v1.3.1.1_win32.exe and 
ESET-KeyGen_v1.3.1.1_win64.exe

works fine with V2 Algorithm

```
[  INFO  ] [V1] License uploads...
[ FAILED ] [V1] Algorithm error, attempt through a new algorithm...

[  INFO  ] [V2] License uploads...
[   OK   ] [V2] License is uploaded!

[  INFO  ] [V2] Getting information from the license...
[   OK   ] [V2] Information successfully received!
```

**Comment by rzc0d3r** [comment]
Try run project with ```no-headless``` argument and take screenshots

**Comment by rzc0d3r** [comment]
And well may also be the reason in vpn and some hidden restrictions on the part of the site. Try a VPN as well

**Comment by rzc0d3r** [comment]
It seems to me that if I put a virtual machine with 7 Windows, everything will work for me. I'll check that tonight (around 15-17 UTC+2).

**Comment by rzc0d3r** [comment]
I checked and indeed the site does not load on Windows 7, but start with the key ```--no-headless``` everything starts working!

**Comment by rzc0d3r** [comment]
should I add the ```--no-headless``` key automatically if the system is windows 7? (In code)

**Comment by stevekat** [comment]
This release work fine under Windows 7 32 bit.
The first two runs gave errors, but then it worked.
