### ISSUE TITLE
ESET всё сломал

### ISSUE THREAD

**Issue by TrasserZero** [rzc0d3r/ESET-KeyGen#93]
[  INFO  ] Request license page loading...
[  INFO  ] Sending a request for a license...
[  INFO  ] Waiting for confirmation of request...
[ FAILED ] Traceback (most recent call last):
  File "/home/runner/work/ESET-KeyGen/ESET-KeyGen/ESET-KeyGen/main.py", line 135, in <module>
    EsetKeyG.sendRequestForKey()
  File "/home/runner/work/ESET-KeyGen/ESET-KeyGen/ESET-KeyGen/modules/eset_keygen.py", line 37, in sendRequestForKey
    uCE(self.driver, f"return {CLICK_WITH_BOOL}({GET_EBAV}('ion-button', 'robot', 'common-base-modal-header-close-btn'))")
  File "/home/runner/work/ESET-KeyGen/ESET-KeyGen/ESET-KeyGen/modules/shared_tools.py", line 61, in untilConditionExecute
    raise RuntimeError('untilConditionExecute: the code did not return the desired value!')
RuntimeError: untilConditionExecute: the code did not return the desired value!

cat: './*KEYS.txt': No such file or directory
Error: Process completed with exit code 1.

**Comment by WWFyb3NsYXYg** [comment]
![image](https://github.com/rzc0d3r/ESET-KeyGen/assets/87089735/1343b1e7-f63d-4ec8-97a6-7ddba2ab281b)

**Comment by rzc0d3r** [comment]
Вечерком сяду почекаем чё там

**Comment by rzc0d3r** [comment]
Пробуем [v1.3.1.0](https://github.com/rzc0d3r/ESET-KeyGen/releases/tag/v1.3.1.0)

**Comment by TrasserZero** [comment]
Всё взлетело, спасибо =)
