### ISSUE TITLE
Does not support the Firefox develepor variant.

### ISSUE THREAD

**Issue by DogancanYr** [rzc0d3r/ESET-KeyGen#98]
I think it has firefox support.

**Comment by rzc0d3r** [comment]
you need to specify a specific path to the executable (But I need to rewrite the entire argument passing system for this). I'll do it later and not so fast. Okay?

**Comment by rzc0d3r** [comment]
Try [v1.3.1.3](https://github.com/rzc0d3r/ESET-KeyGen/releases/tag/v1.3.1.3)

Added command line argument ```--custom-browser-location``` through a space you specify the full path in quotes to the browser binary file.
Read more about it [here](https://github.com/rzc0d3r/ESET-KeyGen/blob/main/wiki/CommandLineArguments.md)

**Comment by rzc0d3r** [comment]
works?

**Comment by DogancanYr** [comment]
> works?

Yes .
That was really fast.

Also, it would be better if it didn't start automatically on startup and listed the Command Line Arguments at that time.

**Comment by rzc0d3r** [comment]
That's cool.
What do you mean exactly?

**Comment by DogancanYr** [comment]
> That's cool. What do you mean exactly?

It shows it directly without entering the --help command
(add the --start command to start it.)
This is generally what the software I use does.

**Comment by rzc0d3r** [comment]
It's like at startup all accepting arguments are output and only upon receiving obligatory arguments start the whole project?

**Comment by DogancanYr** [comment]
> It's like at startup all accepting arguments are output and only upon receiving necessary arguments start the whole project?

Yes.

**Comment by rzc0d3r** [comment]
It's just that my program doesn't require mandatory arguments (for convenience, so that I don't have to create shortcuts with different sets of arguments).

**Comment by rzc0d3r** [comment]
Like, you run it, you get it.

**Comment by DogancanYr** [comment]
At least it doesn't occur to people that it only works in Chrome (for those who skip the arguments part.)

**Comment by rzc0d3r** [comment]
I can explicitly ask you to specify the browser, and without that the project will give an error that you didn't specify the browser you are using

**Comment by rzc0d3r** [comment]
like the console app

**Comment by DogancanYr** [comment]
Yeah, that could be it.

**Comment by rzc0d3r** [comment]
Example

![image](https://github.com/rzc0d3r/ESET-KeyGen/assets/106631540/94b9a5da-2a7c-43f7-bc55-aadd4d058e13)

**Comment by DogancanYr** [comment]
> Example
> 
> ![image](https://private-user-images.githubusercontent.com/106631540/307153419-94b9a5da-2a7c-43f7-bc55-aadd4d058e13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MzcxMjUsIm5iZiI6MTcwODYzNjgyNSwicGF0aCI6Ii8xMDY2MzE1NDAvMzA3MTUzNDE5LTk0YjlhNWRhLTJhN2MtNDNmNy1iYzU1LWFhZGQ0ZDA1OGUxMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMlQyMTIwMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00N2RhNjMyZDRiZDFiY2RiN2E4OWZiZDhkMjFmMjBiYTc0YTA2YjBlNTI3MDlkNTIzYjM1Yzc3ZWI0ZjkwZjM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JnecwNBy3iHgq5ltveXvZjQOmNPK-7pjpg1R99HGEOU)

It looks good. Thank you really .

**Comment by rzc0d3r** [comment]
I'll post an update soon.
