### ISSUE TITLE
Unable to use CI anymore

### ISSUE THREAD

**Issue by AdityaGarg8** [rzc0d3r/ESET-KeyGen#99]
In the --only-update line of the CI, it is now asking me to add --key or --account

**Comment by AdityaGarg8** [comment]
![Screenshot_20240224_112100_Chrome](https://github.com/rzc0d3r/ESET-KeyGen/assets/85610623/b6607851-2ac7-430c-a1ed-be8bde688456)

**Comment by AdityaGarg8** [comment]
This pr fixes it

https://github.com/rzc0d3r/ESET-KeyGen/pull/100

**Comment by rzc0d3r** [comment]
The project is now fully console-based. I'll clean up all 'input' and 'wait for keyboard press' today. And the --cli --force key will be removed because the project will already without input

**Comment by rzc0d3r** [comment]
I'll keep these keys, though. Sometimes you have to get consent or a waiver from the user

**Comment by rzc0d3r** [comment]
Although from --force is only needed to skip the update menu. It can be replaced by --skip-webdriver-menu

**Comment by rzc0d3r** [comment]
Github Actions gives an error related to token and authentication. Yesterday I received a notification that the token is about to expire and you are recommended to recreate it by clicking on the button in the email. I did so and after that Github Actions scripts stopped authenticating and thus giving an error.

**Comment by AdityaGarg8** [comment]
> Github Actions gives an error related to token and authentication. Yesterday I received a notification that the token is about to expire and you are recommended to recreate it by clicking on the button in the email. I did so and after that Github Actions scripts stopped authenticating and thus giving an error.

You need to update the PAT secret in your settings with new token

**Comment by rzc0d3r** [comment]
I updated the token, but I didn't update the PAT secret. It's all working now.
